# Generated by the CuNi Vyper backend.
# "Trust Provable, in all things."
# 
# STRUCTURE — two delimited regions, one law (same logic or refuse):
# - Logic core (CUNI-LOGIC-CORE markers): `@internal @pure` Vyper
#   functions, one per CuNi `def`, underscore-prefixed per the Vyper
#   docs' own internal/external pattern. `dec` is int256 scaled 10^4
#   (docs/DECIMAL.md) — deliberately NOT Vyper's native `decimal`
#   (scale 10^10): CuNi proves the semantics it was given. No driver
#   here: a pure contract has no stdout; the `say` driver runs only
#   in the Python reference (`--emit-vyper-ref`).
# - Contract shell (CUNI-VYPER-SHELL markers): one `@external @pure`
#   wrapper per CuNi `def`, returning the computed value (`dec`
#   values cross the ABI scaled by 10^4). Requires the Vyper
#   compiler; NOT compiled by `cuni check` (no Vyper toolchain on
#   the check machine).
# 
# HONEST BOUNDARIES: logic gate-proven via the Python reference;
# shell not compiled here; nothing has executed on-chain.

# CUNI-LOGIC-CORE-START
@internal
@pure
def _fee(amount: int256) -> int256:
    if (amount <= 1000000):
        return (((amount * 100) / 10000) + 2500)
    return (((amount * 50) / 10000) + 2500)

@internal
@pure
def _double(n: int256) -> int256:
    return (n * 2)

@internal
@pure
def _ok(amount: int256) -> bool:
    return (amount >= 0)

# CUNI-LOGIC-CORE-END

# CUNI-VYPER-SHELL-START
# Requires: Vyper >= 0.4.0. This shell is NOT compiled by `cuni check` —
# no Vyper toolchain on the check machine.

@external
@pure
def fee(amount: int256) -> int256:
    # CuNi `dec` crosses the ABI scaled by 10^4 (docs/DECIMAL.md).
    return self._fee(amount)

@external
@pure
def double(n: int256) -> int256:
    return self._double(n)

@external
@pure
def ok(amount: int256) -> bool:
    return self._ok(amount)
# CUNI-VYPER-SHELL-END
