//! Native Lua backend for the CuNi AST (targets Lua 5.4).
//!
//! Emits idiomatic Lua that runs under `lua5.4` with no dependencies.
//! Stdout must be byte-identical to the Python backend: `say` prints via
//! `_cuni_repr` (Python-repr-like), integer division truncates toward zero,
//! and `fail`/`??` reuse one error channel. Note Lua is 1-indexed — the
//! `for i, x in xs` loop synthesizes a 0-based `i` to match.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub fn generate(program: &Program) -> String {
    let mut cg = Codegen::new(program);
    cg.gen_program(program);
    cg.out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    List,
    Map,
    Other,
}

struct FnInfo {
    fallible: bool,
}

struct Codegen {
    fn_info: HashMap<String, FnInfo>,
    typ_names: HashSet<String>,
    out: String,
    tmp: usize,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_info = HashMap::new();
        let mut typ_names = HashSet::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    fn_info.insert(
                        f.name.clone(),
                        FnInfo {
                            fallible: f.fallible,
                        },
                    );
                }
                Item::Typ(t) => {
                    typ_names.insert(t.name.clone());
                }
                _ => {}
            }
        }
        Codegen {
            fn_info,
            typ_names,
            out: String::new(),
            tmp: 0,
        }
    }

    fn fresh(&mut self) -> String {
        self.tmp += 1;
        format!("_t{}", self.tmp)
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) {
        self.line(0, "-- Generated by the CuNi Lua backend. Do not hand-edit.");
        self.out.push('\n');
        // ---- stdlib shims ----
        self.line(0, "local function say(x)");
        self.line(
            1,
            "if type(x) == \"string\" then print(x) else print(_cuni_repr(x)) end",
        );
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_repr(x)");
        self.line(1, "local t = type(x)");
        self.line(
            1,
            "if t == \"string\" then return \"'\" .. x:gsub(\"'\", \"\\\\'\") .. \"'\" end",
        );
        self.line(
            1,
            "if t == \"boolean\" then return x and \"True\" or \"False\" end",
        );
        self.line(1, "if x == nil then return \"None\" end");
        self.line(1, "if t == \"number\" then return _cuni_num_str(x) end");
        self.line(1, "if t == \"table\" then");
        self.line(2, "if x._cuni_kind == \"list\" then");
        self.line(3, "local parts = {}");
        self.line(3, "for i = 1, #x do parts[#parts+1] = _cuni_repr(x[i]) end");
        self.line(3, "return \"[\" .. table.concat(parts, \", \") .. \"]\"");
        self.line(2, "elseif x._cuni_kind == \"map\" then");
        self.line(3, "local parts = {}");
        self.line(3, "for k, v in pairs(x._cuni_map) do parts[#parts+1] = _cuni_repr(k) .. \": \" .. _cuni_repr(v) end");
        self.line(3, "return \"{\" .. table.concat(parts, \", \") .. \"}\"");
        self.line(2, "elseif x._cuni_kind == \"typ\" then");
        self.line(3, "return x._cuni_repr_s");
        self.line(2, "end");
        self.line(1, "end");
        self.line(1, "return tostring(x)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_num_str(x)");
        self.line(
            1,
            "if x % 1 == 0 and math.abs(x) < 1e15 then return string.format(\"%d\", x) end",
        );
        self.line(1, "local s = tostring(x)");
        self.line(1, "return s");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_interp_str(x)");
        self.line(1, "if type(x) == \"string\" then return x end");
        self.line(1, "return _cuni_repr(x)");
        self.line(0, "end");
        self.out.push('\n');
        // Lists are tagged tables: {_cuni_kind="list", ...elements}.
        self.line(0, "function _cuni_list(...)");
        self.line(1, "local t = {_cuni_kind = \"list\"}");
        self.line(
            1,
            "for i = 1, select(\"#\", ...) do t[i] = select(i, ...) end",
        );
        self.line(1, "return t");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_map(...)");
        self.line(1, "local t = {_cuni_kind = \"map\", _cuni_map = {}}");
        self.line(1, "local n = select(\"#\", ...)");
        self.line(
            1,
            "for i = 1, n, 2 do t._cuni_map[select(i, ...)] = select(i+1, ...) end",
        );
        self.line(1, "return t");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function range(n)");
        self.line(1, "n = math.tointeger(n) or 0");
        self.line(1, "if n <= 0 then return _cuni_list() end");
        self.line(1, "local t = {_cuni_kind = \"list\"}");
        self.line(1, "for i = 0, n-1 do t[#t+1] = i end");
        self.line(1, "return t");
        self.line(0, "end");
        self.out.push('\n');
        self.line(
            0,
            "function abs(n) return math.abs(math.tointeger(n) or n) end",
        );
        self.line(0, "function min(a, b) a = math.tointeger(a) or a; b = math.tointeger(b) or b; if a <= b then return a else return b end end");
        self.line(0, "function max(a, b) a = math.tointeger(a) or a; b = math.tointeger(b) or b; if a >= b then return a else return b end end");
        self.out.push('\n');
        self.line(0, "function _cuni_slice(xs, a, b)");
        self.line(1, "a = math.tointeger(a) or 0; b = math.tointeger(b) or 0");
        self.line(1, "local n = xs._cuni_kind == \"list\" and #xs or #xs");
        self.line(1, "if a < 0 or b < 0 or a > n or b > n or a > b then");
        self.line(
            2,
            "if type(xs) == \"string\" then return \"\" else return _cuni_list() end",
        );
        self.line(1, "end");
        self.line(
            1,
            "if type(xs) == \"string\" then return xs:sub(a+1, b) end",
        );
        self.line(1, "local t = {_cuni_kind = \"list\"}");
        self.line(1, "for i = a+1, b do t[#t+1] = xs[i] end");
        self.line(1, "return t");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_div(a, b)");
        self.line(
            1,
            "if math.type(a) == \"integer\" and math.type(b) == \"integer\" and b ~= 0 then",
        );
        self.line(2, "local q = a // b");
        self.line(2, "local r = a % b");
        self.line(2, "if r ~= 0 and (a < 0) ~= (b < 0) then return q + 1 end");
        self.line(2, "return q");
        self.line(1, "end");
        self.line(1, "return a / b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "function _cuni_len(x)");
        self.line(1, "if type(x) == \"string\" then return #x end");
        self.line(1, "if x._cuni_kind == \"list\" then return #x end");
        self.line(1, "if x._cuni_kind == \"map\" then local n = 0; for _ in pairs(x._cuni_map) do n = n + 1 end; return n end");
        self.line(1, "return #x");
        self.line(0, "end");
        self.out.push('\n');
        // Named typ construction: Circle(kwargs{r=2.0}).
        self.line(0, "function kwargs(t) return {kwargs = t} end");
        self.out.push('\n');

        let mut top_scope: HashMap<String, VarKind> = HashMap::new();
        for item in &program.items {
            self.gen_item(item, &mut top_scope, 0);
            self.out.push('\n');
        }
    }

    fn gen_item(&mut self, item: &Item, scope: &mut HashMap<String, VarKind>, indent: usize) {
        match item {
            Item::Use(u) => {
                self.line(
                    indent,
                    &format!(
                        "-- use {} — portable CuNi module, not resolved by this backend",
                        u.name
                    ),
                );
            }
            Item::Ext(ext) => {
                let params = ext
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(indent, &format!("function {}({})", ext.name, params));
                let lua_line = ext
                    .targets
                    .iter()
                    .find(|(t, _)| *t == "lua")
                    .map(|(_, raw)| raw.clone())
                    .unwrap_or_else(|| "error(\"no lua: mapping given\")".to_string());
                self.line(indent + 1, &lua_line);
                self.line(indent, "end");
            }
            Item::Typ(t) => {
                // Typs become tables with a metatable-free constructor.
                self.line(indent, &format!("function {}(...)", t.name));
                self.line(indent + 1, "local args = {...}");
                self.line(
                    indent + 1,
                    &format!(
                        "local self = {{_cuni_kind = \"typ\", _cuni_name = \"{}\"}}",
                        t.name
                    ),
                );
                self.line(indent + 1, "local kw = (#args == 1 and type(args[1]) == \"table\" and args[1].kwargs) or nil");
                for (i, f) in t.fields.iter().enumerate() {
                    self.line(
                        indent + 1,
                        &format!(
                            "self.{0} = (kw and kw.{0} ~= nil) and kw.{0} or args[{1}]",
                            f.name,
                            i + 1
                        ),
                    );
                }
                let field_reprs: Vec<String> = t
                    .fields
                    .iter()
                    .map(|f| format!("\"{0}=\" .. _cuni_repr(self.{0})", f.name))
                    .collect();
                self.line(
                    indent + 1,
                    &format!(
                        "self._cuni_repr_s = \"{0}(\" .. table.concat({{{1}}}, \", \") .. \")\"",
                        t.name,
                        field_reprs.join(", ")
                    ),
                );
                self.line(indent + 1, "return self");
                self.line(indent, "end");
            }
            Item::Iface(i) => {
                self.line(
                    indent,
                    &format!(
                        "-- iface {} — checked by CuNi typeck, documentary here",
                        i.name
                    ),
                );
            }
            Item::Enum(e) => {
                self.line(indent, &format!("{} = {{}}", e.name));
                for (i, v) in e.variants.iter().enumerate() {
                    self.line(indent, &format!("{}.{} = {}", e.name, v.name, i));
                }
            }
            Item::Def(f) => {
                let params = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                // Lua has no `return` outside functions; top-level `ret` in a
                // ?? handler needs pcall. Functions are real Lua functions.
                self.line(indent, &format!("function {}({})", f.name, params));
                let mut fn_scope: HashMap<String, VarKind> = HashMap::new();
                if f.body.is_empty() {
                    self.line(
                        indent + 1,
                        "error(\"CuNi stub body (`...`) — not yet written\")",
                    );
                } else {
                    for s in &f.body {
                        self.gen_stmt(indent + 1, s, &mut fn_scope);
                    }
                }
                self.line(indent, "end");
                if f.is_link {
                    self.line(
                        indent,
                        &format!(
                            "-- link {}: HTTP handler/client not emitted by the Lua backend v1",
                            f.name
                        ),
                    );
                }
            }
            Item::Stmt(s) => self.gen_stmt(indent, s, scope),
        }
    }

    fn gen_stmt(&mut self, indent: usize, stmt: &Stmt, scope: &mut HashMap<String, VarKind>) {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                let kind = ty
                    .as_ref()
                    .map(kind_of_type)
                    .or_else(|| kind_of_literal(value))
                    .unwrap_or(VarKind::Other);
                scope.insert(name.clone(), kind);
                self.gen_binding(indent, name, value, scope);
            }
            StmtKind::Assign { target, value } => {
                self.line(
                    indent,
                    &format!(
                        "{} = {}",
                        self.gen_expr(target, scope),
                        self.gen_expr(value, scope)
                    ),
                );
            }
            StmtKind::Ret(Some(e)) => {
                // Top-level `ret` has no Lua function to return from; the
                // ?? handler wraps in pcall (see gen_binding) and a top-level
                // ret becomes do-return via a sentinel. For v1: only valid
                // inside functions; top-level ret raises a clear error.
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("return {}", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let text = self.gen_expr(e, scope);
                self.line(
                    indent,
                    &format!("error({{_cuni_fail = true, msg = {}}})", text),
                );
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                self.line(indent, &format!("if {} then", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, then_body, scope);
                if let Some(else_body) = else_body {
                    self.line(indent, "else");
                    self.gen_block(indent + 1, else_body, scope);
                }
                self.line(indent, "end");
            }
            StmtKind::For {
                binding: (a, b),
                iter,
                body,
            } => {
                let iter_kind = if let ExprKind::Ident(name) = &iter.kind {
                    scope.get(name).copied()
                } else {
                    None
                };
                let it = self.gen_expr(iter, scope);
                match b {
                    Some(b) if iter_kind == Some(VarKind::Map) => {
                        self.line(
                            indent,
                            &format!("for {}_k, {}_v in pairs({}._cuni_map) do", a, b, it),
                        );
                        self.line(indent + 1, &format!("local {} = {}_k", a, a));
                        self.line(indent + 1, &format!("local {} = {}_v", b, b));
                    }
                    Some(b) => {
                        // 0-based index to match Python's enumerate.
                        self.line(indent, &format!("for {}_i = 1, #{} do", a, it));
                        self.line(indent + 1, &format!("local {} = {}_i - 1", a, a));
                        self.line(indent + 1, &format!("local {} = {}[{}_i]", b, it, a));
                    }
                    None => {
                        self.line(indent, &format!("for _, {} in ipairs({}) do", a, it));
                    }
                }
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::Whl { cond, body } => {
                self.line(indent, &format!("while {} do", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::ExprStmt(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &text);
            }
            StmtKind::Todo => {
                self.line(
                    indent,
                    "error(\"CuNi stub body (`...`) — not yet written\")",
                );
            }
        }
    }

    fn gen_block(&mut self, indent: usize, stmts: &[Stmt], scope: &mut HashMap<String, VarKind>) {
        if stmts.is_empty() {
            self.line(indent, "-- pass");
        } else {
            for s in stmts {
                self.gen_stmt(indent, s, scope);
            }
        }
    }

    fn gen_binding(
        &mut self,
        indent: usize,
        name: &str,
        value: &Expr,
        scope: &mut HashMap<String, VarKind>,
    ) {
        if let ExprKind::Unwrap { expr, handler } = &value.kind {
            let is_fallible_call = matches!(&expr.kind, ExprKind::Call { callee, .. } if matches!(&callee.kind, ExprKind::Ident(fname) if self.fn_info.get(fname).map_or(false, |i| i.fallible))
            );
            let inner = self.gen_expr(expr, scope);
            let ok = self.fresh();
            let res = self.fresh();
            if is_fallible_call {
                // pcall captures fail(); handler runs on error.
                // Pre-declare so the binding escapes the if-block (Lua scoping).
                self.line(indent, &format!("local {}", name));
                self.line(
                    indent,
                    &format!(
                        "local {}, {} = pcall(function() return {} end)",
                        ok, res, inner
                    ),
                );
                self.line(indent, &format!("if not {} then", ok));
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = {}", name, res));
                self.line(indent, "end");
            } else {
                self.line(indent, &format!("local {}", name));
                self.line(indent, &format!("local {}_u = {}", name, inner));
                self.line(indent, &format!("if {}_u == nil then", name));
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = {}_u", name, name));
                self.line(indent, "end");
            }
        } else {
            self.line(
                indent,
                &format!("local {} = {}", name, self.gen_expr(value, scope)),
            );
        }
    }

    fn gen_expr(&self, expr: &Expr, scope: &HashMap<String, VarKind>) -> String {
        match &expr.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Float(f) => {
                let s = f.to_string();
                if s.contains('.') || s.contains('e') {
                    s
                } else {
                    format!("{}.0", s)
                }
            }
            ExprKind::Bool(true) => "true".to_string(),
            ExprKind::Bool(false) => "false".to_string(),
            ExprKind::Str(s) => format!("{:?}", s),
            ExprKind::InterpStr(parts) => {
                let mut s = String::new();
                for (i, p) in parts.iter().enumerate() {
                    if i > 0 {
                        s.push_str(" .. ");
                    }
                    match p {
                        StrPartExpr::Text(t) => {
                            s.push_str(&format!("{:?}", t));
                        }
                        StrPartExpr::Expr(e) => {
                            s.push_str(&_cuni_interp(e, scope, self));
                        }
                    }
                }
                if s.is_empty() {
                    "\"\"".to_string()
                } else {
                    s
                }
            }
            ExprKind::NoneLit => "nil".to_string(),
            ExprKind::Ident(name) => name.clone(),
            ExprKind::List(items) => format!(
                "_cuni_list({})",
                items
                    .iter()
                    .map(|e| self.gen_expr(e, scope))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Map(pairs) => format!(
                "_cuni_map({})",
                pairs
                    .iter()
                    .map(|(k, v)| format!(
                        "{}, {}",
                        self.gen_expr(k, scope),
                        self.gen_expr(v, scope)
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Call { callee, args } => {
                if let ExprKind::Field { base, name } = &callee.kind {
                    if name == "push" {
                        let b = self.gen_expr(base, scope);
                        let a = args
                            .iter()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .collect::<Vec<_>>()
                            .join(", ");
                        return format!("{}[#{}+1] = {}", b, b, a);
                    }
                    if name == "len" {
                        return format!("_cuni_len({})", self.gen_expr(base, scope));
                    }
                    if name == "slice" && args.len() == 2 {
                        return format!(
                            "_cuni_slice({}, {}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope),
                            self.gen_expr(args[1].expr(), scope)
                        );
                    }
                }
                let callee_s = self.gen_expr(callee, scope);
                if self.typ_names.contains(&callee_s) {
                    if args.iter().all(|a| a.is_named()) && !args.is_empty() {
                        let parts: Vec<String> = args
                            .iter()
                            .filter_map(|a| match a {
                                CallArg::Named { name, value, .. } => {
                                    Some(format!("{} = {}", name, self.gen_expr(value, scope)))
                                }
                                _ => None,
                            })
                            .collect();
                        return format!("{}(kwargs{{{}}})", callee_s, parts.join(", "));
                    }
                    return format!(
                        "{}({})",
                        callee_s,
                        args.iter()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .collect::<Vec<_>>()
                            .join(", ")
                    );
                }
                // stdlib shims that take plain calls
                if callee_s == "say" && args.len() == 1 {
                    return format!("say({})", self.gen_expr(args[0].expr(), scope));
                }
                format!(
                    "{}({})",
                    callee_s,
                    args.iter()
                        .map(|a| self.gen_expr(a.expr(), scope))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
            ExprKind::Index { base, index } => {
                let b = self.gen_expr(base, scope);
                let i = self.gen_expr(index, scope);
                // Maps live in _cuni_map (0-based keys as written); lists are
                // 1-based in Lua so CuNi's 0-based index shifts by one.
                let is_map = matches!(&base.kind, ExprKind::Ident(name) if scope.get(name) == Some(&VarKind::Map));
                if is_map {
                    format!("({}._cuni_map[{}])", b, i)
                } else {
                    format!("({}[{}+1])", b, i)
                }
            }
            ExprKind::Field { base, name } => format!("{}.{}", self.gen_expr(base, scope), name),
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_expr(lhs, scope);
                let r = self.gen_expr(rhs, scope);
                if matches!(op, BinOp::Div) {
                    format!("_cuni_div({}, {})", l, r)
                } else {
                    format!("({} {} {})", l, lua_binop(*op), r)
                }
            }
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("(not {})", self.gen_expr(expr, scope)),
                UnOp::Neg => format!("(-{})", self.gen_expr(expr, scope)),
            },
            ExprKind::Unwrap { .. } => {
                "nil  -- UNSUPPORTED: ?? outside a let/mut binding".to_string()
            }
        }
    }
}

fn _cuni_interp(e: &Expr, scope: &HashMap<String, VarKind>, cg: &Codegen) -> String {
    format!("_cuni_interp_str({})", cg.gen_expr(e, scope))
}

fn kind_of_type(ty: &Type) -> VarKind {
    match ty {
        Type::Generic(name, _) if name == "list" => VarKind::List,
        Type::Generic(name, _) if name == "map" => VarKind::Map,
        _ => VarKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<VarKind> {
    match &e.kind {
        ExprKind::List(_) => Some(VarKind::List),
        ExprKind::Map(_) => Some(VarKind::Map),
        _ => None,
    }
}

fn lua_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "~=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
    }
}
