//! Kotlin backend — custom core-subset native seat (seat id `kt`).
//!
//! Kotlin is statically typed with mandatory parameter types, so this seat is
//! a custom emitter rather than a [`crate::codegen_core`] spec (the core spec
//! emits untyped parameter lists, which kotlinc rejects). It covers exactly
//! the core subset (see codegen_core docs) and refuses everything else with
//! the same honest `Err`s.
//!
//! Emitted shape:
//! ```kotlin
//! // Generated by the CuNi core-subset backend. Do not hand-edit.
//! fun cuni_mod(a: Long, b: Long): Long = ((a % b) + b) % b
//! fun cuni_say(x: Long) = println(x)
//! fun cuni_say(x: String) = println(x)
//! fun cuni_say(x: Boolean) = println(if (x) "True" else "False")
//!
//! fun add(a: Long, b: Long): Long {
//!     return (a + b)
//! }
//!
//! fun main() {
//!     var x: Long = 10L
//!     cuni_say(x)
//! }
//! ```
//!
//! Semantics notes (verified against the py seat, which is the gate's gold):
//! - CuNi `int` (i64) -> Kotlin `Long`; `str` -> `String`; `bool` -> `Boolean`.
//! - Integer `/` on `Long`s truncates toward zero natively (CuNi semantics,
//!   no helper needed). `%` truncates in Kotlin, so every `%` goes through
//!   `cuni_mod` (Python-floored `((a % b) + b) % b`; a zero divisor throws
//!   `ArithmeticException`, crashing the seat the way Python's
//!   `ZeroDivisionError` crashes the gold — a run failure, never silent
//!   divergence).
//! - `say` is type-routed at emit time to the `Long`/`String`/`Boolean`
//!   overloads; booleans print `True`/`False`.
//! - `==`/`!=` are structural in Kotlin (correct for `String`); `<`/`>`/`<=`
//!   /`>=` on `String` use `Comparable.compareTo` (same byte order as the py
//!   seat for the ASCII fixtures; lexicographic by UTF-16 code unit).
//! - Function parameters are Kotlin `val`s, so a body that assigns to a
//!   parameter gets a `var` copy (`var n: Long = n`) first — the same
//!   observable behavior as CuNi's parameter binding, without a kotlinc
//!   "val cannot be reassigned" failure.
//! - `def main` is refused (clash with `fun main`), as is any `def` starting
//!   with `cuni_` (helper collision).
//!
//! Wiring note: `emit.rs`/`main.rs` dispatch is left to the parent — this file
//! only provides `generate`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn kt_ty(t: Ty) -> &'static str {
    match t {
        Ty::Int => "Long",
        Ty::Str => "String",
        Ty::Bool => "Boolean",
    }
}

/// Kotlin string literal. `$` is escaped: it starts string templates even in
/// a plain `"..."` literal. Non-ASCII passes through raw (kotlinc reads
/// UTF-8), matching the py seat's raw passthrough.
fn kt_str(s: &str) -> String {
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            '\n' => r.push_str("\\n"),
            '\t' => r.push_str("\\t"),
            '\r' => r.push_str("\\r"),
            '$' => r.push_str("\\$"),
            c if (c as u32) < 0x20 => r.push_str(&format!("\\u{:04x}", c as u32)),
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

const HELPERS: &str = concat!(
    "fun cuni_mod(a: Long, b: Long): Long = ((a % b) + b) % b\n",
    "fun cuni_say(x: Long) = println(x)\n",
    "fun cuni_say(x: String) = println(x)\n",
    "fun cuni_say(x: Boolean) = println(if (x) \"True\" else \"False\")\n",
);

struct Emitter {
    out: String,
    level: usize,
    /// Function name -> return type. Fully populated before any body is
    /// generated, so forward references are fine.
    fn_ret: HashMap<String, Ty>,
    /// Scope stack: source name -> type. Kotlin has real block scoping, so
    /// nested `var`s shadow legally; a duplicate in the *same* frame is
    /// refused (typeck rejects it before emit, so this is a backstop).
    frames: Vec<HashMap<String, Ty>>,
    in_func: bool,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        level: 0,
        fn_ret: HashMap::new(),
        frames: Vec::new(),
        in_func: false,
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            self.out.push_str(&"    ".repeat(self.level));
            self.out.push_str(text);
        }
        self.out.push('\n');
    }

    fn lookup(&self, name: &str) -> Option<Ty> {
        for f in self.frames.iter().rev() {
            if let Some(t) = f.get(name) {
                return Some(*t);
            }
        }
        None
    }

    fn bind(&mut self, name: &str, ty: Ty) -> Result<(), String> {
        let frame = self.frames.last_mut().expect("scope frame");
        if frame.contains_key(name) {
            return Err(format!(
                "duplicate binding `{}` in one block: beyond core subset; refusing",
                name
            ));
        }
        frame.insert(name.to_string(), ty);
        Ok(())
    }

    fn check_ann(&self, name: &str, ty: &Option<Type>, vt: Ty, kw: &str) -> Result<(), String> {
        if let Some(t) = ty {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!(
                    "{} {}: annotated type disagrees with value type; refusing",
                    kw, name
                ));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        if f.name == "main" {
            return Err("def main: collides with the Kotlin entry point; refusing".into());
        }
        if f.name.starts_with("cuni_") {
            return Err(format!(
                "def {}: reserved cuni_ prefix (collides with helpers); refusing",
                f.name
            ));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        self.out
            .push_str("// Generated by the CuNi core-subset backend. Do not hand-edit.\n");
        self.out.push_str(HELPERS);
        // First pass: collect def signatures, refuse non-core items.
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    if self.fn_ret.contains_key(&f.name) {
                        return Err(format!("def {}: duplicate definition; refusing", f.name));
                    }
                    self.fn_ret.insert(f.name.clone(), ty_of(&f.ret_type)?);
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        self.out.push('\n');
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
                self.out.push('\n');
            }
        }
        self.line("fun main() {");
        self.level += 1;
        self.frames.push(HashMap::new());
        for s in script {
            self.gen_stmt(s)?;
        }
        self.frames.pop();
        self.level -= 1;
        self.line("}");
        Ok(())
    }

    /// Names assigned anywhere inside a def body (recursively). Parameters in
    /// this set get a `var` copy, because Kotlin parameters are `val`s.
    fn collect_assigned(s: &Stmt, out: &mut HashSet<String>) {
        match &s.kind {
            StmtKind::Assign { target, .. } => {
                if let ExprKind::Ident(n) = &target.kind {
                    out.insert(n.clone());
                }
            }
            StmtKind::If {
                then_body,
                else_body,
                ..
            } => {
                for s in then_body {
                    Self::collect_assigned(s, out);
                }
                if let Some(eb) = else_body {
                    for s in eb {
                        Self::collect_assigned(s, out);
                    }
                }
            }
            StmtKind::Whl { body, .. } => {
                for s in body {
                    Self::collect_assigned(s, out);
                }
            }
            _ => {}
        }
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        let ret = ty_of(&f.ret_type)?;
        let mut assigned: HashSet<String> = HashSet::new();
        for s in &f.body {
            Self::collect_assigned(s, &mut assigned);
        }
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, kt_ty(ty_of(&p.ty).expect("checked"))))
            .collect();
        self.line(&format!(
            "fun {}({}): {} {{",
            f.name,
            params.join(", "),
            kt_ty(ret)
        ));
        self.level += 1;
        let was_in_func = self.in_func;
        self.in_func = true;
        self.frames.push(HashMap::new());
        for p in &f.params {
            let pt = ty_of(&p.ty)?;
            self.bind(&p.name, pt)?;
            if assigned.contains(&p.name) {
                // Kotlin parameters are vals; copy to a mutable local so
                // `param = ...` bodies compile with CuNi semantics.
                self.line(&format!("var {0}: {1} = {0}", p.name, kt_ty(pt)));
            }
        }
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        self.frames.pop();
        self.in_func = was_in_func;
        self.level -= 1;
        self.line("}");
        Ok(())
    }

    fn gen_block(&mut self, body: &[Stmt]) -> Result<(), String> {
        self.frames.push(HashMap::new());
        for s in body {
            self.gen_stmt(s)?;
        }
        self.frames.pop();
        Ok(())
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "let")?;
                self.bind(name, vt)?;
                self.line(&format!("var {}: {} = {}", name, kt_ty(vt), v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "mut")?;
                self.bind(name, vt)?;
                self.line(&format!("var {}: {} = {}", name, kt_ty(vt), v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                let tname = match &target.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => {
                        return Err(
                            "complex assignment target: beyond core subset; refusing".into()
                        )
                    }
                };
                if self.lookup(&tname).is_none() {
                    return Err(format!("unknown variable `{}`: refusing", tname));
                }
                let (v, _) = self.gen_expr(value)?;
                self.line(&format!("{} = {}", tname, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                if !self.in_func {
                    return Err("top-level ret: no return slot; refusing".into());
                }
                match e {
                    Some(x) => {
                        let (v, _) = self.gen_expr(x)?;
                        self.line(&format!("return {}", v));
                    }
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                }
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.line(&format!("if ({}) {{", c));
                self.level += 1;
                self.gen_block(then_body)?;
                self.level -= 1;
                if let Some(eb) = else_body {
                    self.line("} else {");
                    self.level += 1;
                    self.gen_block(eb)?;
                    self.level -= 1;
                }
                self.line("}");
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.line(&format!("while ({}) {{", c));
                self.level += 1;
                self.gen_block(body)?;
                self.level -= 1;
                self.line("}");
                Ok(())
            }
            StmtKind::ExprStmt(e) => {
                // Only `say(...)` calls allowed as bare expression statements.
                match &e.kind {
                    ExprKind::Call { callee, args } => {
                        if let ExprKind::Ident(n) = &callee.kind {
                            if n == "say" {
                                if args.len() != 1 {
                                    return Err(
                                        "say: exactly one argument in core subset; refusing".into()
                                    );
                                }
                                let (v, _) = self.gen_expr(args[0].expr())?;
                                self.line(&format!("cuni_say({})", v));
                                return Ok(());
                            }
                        }
                        Err("bare call (non-say): beyond core subset; refusing".into())
                    }
                    _ => Err("bare expression: beyond core subset; refusing".into()),
                }
            }
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((format!("{}L", n), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b { "true".to_string() } else { "false".to_string() },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((kt_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let t = self
                    .lookup(n)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((n.clone(), t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self
                    .fn_ret
                    .get(&name)
                    .copied()
                    .ok_or_else(|| format!("call to unknown function `{}`: refusing", name))?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("({} + {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        return Err("mixed-type `+`: beyond core subset; refusing".into());
                    }
                    BinOp::Sub => {
                        require_ints(lt, rt, "-")?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        require_ints(lt, rt, "*")?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        require_ints(lt, rt, "/")?;
                        // Long `/` truncates toward zero: CuNi semantics.
                        Ok((format!("({} / {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        require_ints(lt, rt, "%")?;
                        // Kotlin `%` truncates; the helper floors.
                        Ok((format!("cuni_mod({}, {})", l, r), Ty::Int))
                    }
                    // `==` is structural in Kotlin: right for Long, String,
                    // and Boolean alike.
                    BinOp::Eq => Ok((format!("({} == {})", l, r), Ty::Bool)),
                    BinOp::Ne => Ok((format!("({} != {})", l, r), Ty::Bool)),
                    // `<` etc. work on Long and on String (Comparable).
                    BinOp::Lt => Ok((format!("({} < {})", l, r), Ty::Bool)),
                    BinOp::Gt => Ok((format!("({} > {})", l, r), Ty::Bool)),
                    BinOp::Le => Ok((format!("({} <= {})", l, r), Ty::Bool)),
                    BinOp::Ge => Ok((format!("({} >= {})", l, r), Ty::Bool)),
                    BinOp::And => {
                        require_bools(lt, rt, "and")?;
                        Ok((format!("({} && {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        require_bools(lt, rt, "or")?;
                        Ok((format!("({} || {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(!{})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }
}

fn require_ints(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Int && r == Ty::Int {
        Ok(())
    } else {
        Err(format!("`{}` on non-int: beyond core subset; refusing", op))
    }
}

fn require_bools(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Bool && r == Ty::Bool {
        Ok(())
    } else {
        Err(format!("`{}` on non-bool: beyond core subset; refusing", op))
    }
}
