//! Dart backend — core-subset native seat, hand-written (not over
//! [`crate::codegen_core`]).
//!
//! Core's `LangSpec` cannot express Dart: it hard-codes the comparison as
//! `({l} {op} {r})`, but Dart's `String` defines no `<`/`>`/`<=`/`>=`
//! operators (only `==`), so string ordering must go through
//! `compareTo`. This emitter mirrors the core subset's structure and
//! refusal list exactly, with Dart operators.
//!
//! Emits plain Dart (runs with `dart run.dart`, no packages): `void main()`
//! entry point, `var` bindings, `print`, `while`, and `+` for string
//! concatenation.
//!
//! Semantic choices:
//! - Dart `/` on ints yields a double, so CuNi's truncating-toward-zero int
//!   division goes through `cuni_div(a, b) => a ~/ b` (`~/` truncates toward
//!   zero; verified: `-7 ~/ 2 == -3`).
//! - Dart `%` is always non-negative (Euclidean), which differs from
//!   Python-floored `%` for negative divisors (`7 % -2 == 1` in Dart vs
//!   `-1` in Python), so `cuni_mod` adjusts: `e = a % b; e == 0 ? 0 :
//!   (b < 0 ? e + b : e)` (verified against Python on all sign combos).
//! - String ordering comparisons use `compareTo` (`(l.compareTo(r) < 0)`);
//!   `==`/`!=` are native. Numeric comparisons are native operators.
//! - `cuni_say(x, ty)` prints via `print`; the `ty` tag renders bools as
//!   `True`/`False` since Dart's native literals are `true`/`false`.
//! - `def`s emit without return/parameter types (implicit `dynamic`); that
//!   is valid Dart and keeps the emitter honest about CuNi's dynamic core.
//! - `$` is escaped in string literals (Dart interpolates `$`).
//!
//! Honest caveat: Dart ints are 64-bit (wraparound beyond ±2^63), and
//! `compareTo` orders by UTF-16 code unit (identical to Python's code-point
//! order for BMP text); both are Dart's own semantics, not CuNi lies.
//!
//! Refuses everything beyond the core subset (same list as codegen_core).

use crate::ast::*;
use std::collections::{HashMap, HashSet};

/// Minimal type for `+` routing (numeric vs string concat).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn dart_str(s: &str) -> String {
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            '\n' => r.push_str("\\n"),
            '\t' => r.push_str("\\t"),
            '\r' => r.push_str("\\r"),
            '$' => r.push_str("\\$"),
            c if (c as u32) < 0x20 => r.push_str(&format!("\\u{{{}}}", c as u32)),
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

struct Emitter {
    out: String,
    level: usize,
    fns: HashSet<String>,
    fn_ret: HashMap<String, Ty>,
    scope: HashMap<String, Ty>,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        level: 0,
        fns: HashSet::new(),
        fn_ret: HashMap::new(),
        scope: HashMap::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            self.out.push_str(&"  ".repeat(self.level));
            self.out.push_str(text);
        }
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        self.line("// Generated by the CuNi core-subset backend. Do not hand-edit.");
        self.line("void cuni_say(Object? x, String ty) {");
        self.level += 1;
        self.line("if (ty == \"bool\") { print((x as bool) ? \"True\" : \"False\"); }");
        self.line("else { print(x); }");
        self.level -= 1;
        self.line("}");
        self.line("int cuni_div(int a, int b) => a ~/ b;");
        self.line("int cuni_mod(int a, int b) {");
        self.level += 1;
        self.line("int e = a % b;");
        self.line("if (e == 0) { return 0; }");
        self.line("return b < 0 ? e + b : e;");
        self.level -= 1;
        self.line("}");
        self.out.push('\n');
        let mut script_stmts: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    self.fns.insert(f.name.clone());
                }
                Item::Stmt(s) => script_stmts.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
                self.out.push('\n');
            }
        }
        self.line("void main() {");
        self.level += 1;
        for s in script_stmts {
            self.gen_stmt(s)?;
        }
        self.level -= 1;
        self.line("}");
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        let ret_ty = ty_of(&f.ret_type)?;
        self.fn_ret.insert(f.name.clone(), ret_ty);
        let outer = std::mem::take(&mut self.scope);
        for p in &f.params {
            self.scope.insert(p.name.clone(), ty_of(&p.ty)?);
        }
        let params: Vec<String> = f.params.iter().map(|p| p.name.clone()).collect();
        self.line(&format!("{}({}) {{", f.name, params.join(", ")));
        self.level += 1;
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        self.level -= 1;
        self.line("}");
        self.scope = outer;
        Ok(())
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                if let Some(t) = ty {
                    let at = ty_of(t)?;
                    if at != vt {
                        return Err(format!(
                            "let {}: annotated {:?} disagrees with value; refusing",
                            name, t
                        ));
                    }
                }
                self.scope.insert(name.clone(), vt);
                self.line(&format!("var {} = {};", name, v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                if let Some(t) = ty {
                    let at = ty_of(t)?;
                    if at != vt {
                        return Err(format!(
                            "mut {}: annotated {:?} disagrees with value; refusing",
                            name, t
                        ));
                    }
                }
                self.scope.insert(name.clone(), vt);
                self.line(&format!("var {} = {};", name, v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                if !matches!(target.kind, ExprKind::Ident(_)) {
                    return Err("complex assignment target: beyond core subset; refusing".into());
                }
                let (t, _) = self.gen_expr(target)?;
                let (v, _) = self.gen_expr(value)?;
                self.line(&format!("{} = {};", t, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                let v = match e {
                    Some(x) => self.gen_expr(x)?.0,
                    None => String::new(),
                };
                self.line(&format!("return {};", v));
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.line(&format!("if ({}) {{", c));
                self.level += 1;
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.level -= 1;
                if let Some(eb) = else_body {
                    self.line("} else {");
                    self.level += 1;
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.level -= 1;
                }
                self.line("}");
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.line(&format!("while ({}) {{", c));
                self.level += 1;
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.level -= 1;
                self.line("}");
                Ok(())
            }
            StmtKind::ExprStmt(e) => match &e.kind {
                ExprKind::Call { callee, args } => {
                    if let ExprKind::Ident(n) = &callee.kind {
                        if n == "say" {
                            if args.len() != 1 {
                                return Err(
                                    "say: exactly one argument in core subset; refusing".into()
                                );
                            }
                            let (v, vt) = self.gen_expr(args[0].expr())?;
                            let tys = match vt {
                                Ty::Int => "int",
                                Ty::Str => "str",
                                Ty::Bool => "bool",
                            };
                            self.line(&format!("cuni_say({}, \"{}\");", v, tys));
                            return Ok(());
                        }
                    }
                    Err("bare call (non-say): beyond core subset; refusing".into())
                }
                _ => Err("bare expression: beyond core subset; refusing".into()),
            },
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((n.to_string(), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b { "true".into() } else { "false".into() },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((dart_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let t = self
                    .scope
                    .get(n)
                    .copied()
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((n.clone(), t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self.fn_ret.get(&name).copied().ok_or_else(|| {
                    format!("call to unknown function `{}`: refusing", name)
                })?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if let CallArg::Named { .. } = a {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                let both_str = lt == Ty::Str && rt == Ty::Str;
                // Dart String has no ordering operators; use compareTo.
                if both_str {
                    let cmp = match op {
                        BinOp::Eq => return Ok((format!("({} == {})", l, r), Ty::Bool)),
                        BinOp::Ne => return Ok((format!("({} != {})", l, r), Ty::Bool)),
                        BinOp::Lt => format!("({}.compareTo({}) < 0)", l, r),
                        BinOp::Gt => format!("({}.compareTo({}) > 0)", l, r),
                        BinOp::Le => format!("({}.compareTo({}) <= 0)", l, r),
                        BinOp::Ge => format!("({}.compareTo({}) >= 0)", l, r),
                        BinOp::Add => {
                            return Ok((format!("({} + {})", l, r), Ty::Str));
                        }
                        _ => {
                            return Err(format!(
                                "string `{:?}`: beyond core subset; refusing",
                                op
                            ))
                        }
                    };
                    return Ok((cmp, Ty::Bool));
                }
                let o: &str = match op {
                    BinOp::Add => {
                        self.require_ints(lt, rt, "+")?;
                        "+"
                    }
                    BinOp::Sub => {
                        self.require_ints(lt, rt, "-")?;
                        "-"
                    }
                    BinOp::Mul => {
                        self.require_ints(lt, rt, "*")?;
                        "*"
                    }
                    // Dart `/` on ints yields a double; ~/ truncates (CuNi).
                    BinOp::Div => {
                        self.require_ints(lt, rt, "/")?;
                        return Ok((format!("cuni_div({}, {})", l, r), Ty::Int));
                    }
                    BinOp::Mod => {
                        self.require_ints(lt, rt, "%")?;
                        return Ok((format!("cuni_mod({}, {})", l, r), Ty::Int));
                    }
                    BinOp::Eq => "==",
                    BinOp::Ne => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Le => "<=",
                    BinOp::Ge => ">=",
                    BinOp::And => {
                        self.require_bools(lt, rt, "and")?;
                        "&&"
                    }
                    BinOp::Or => {
                        self.require_bools(lt, rt, "or")?;
                        "||"
                    }
                };
                let result_ty = match op {
                    BinOp::Add | BinOp::Sub | BinOp::Mul => Ty::Int,
                    _ => Ty::Bool,
                };
                Ok((format!("({} {} {})", l, o, r), result_ty))
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(!{})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }

    fn require_ints(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Int && r == Ty::Int {
            Ok(())
        } else {
            Err(format!("`{}` on non-int: beyond core subset; refusing", op))
        }
    }

    fn require_bools(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Bool && r == Ty::Bool {
            Ok(())
        } else {
            Err(format!("`{}` on non-bool: beyond core subset; refusing", op))
        }
    }
}
