//! Native Ruby backend for the CuNi AST.
//!
//! Emits idiomatic Ruby that runs under `ruby` with no dependencies.
//! Stdout must be byte-identical to the Python backend (the exactness
//! reference): `say` prints via a `_cuni_repr` that mirrors Python's
//! `repr` for containers/bools/None, integer division truncates toward
//! zero like `_cuni_div`, and `fail`/`??` reuse one `CuNiError`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub fn generate(program: &Program) -> String {
    let mut cg = Codegen::new(program);
    cg.gen_program(program);
    cg.out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    List,
    Map,
    Other,
}

struct FnInfo {
    fallible: bool,
}

struct Codegen {
    fn_info: HashMap<String, FnInfo>,
    typ_names: HashSet<String>,
    enum_names: HashSet<String>,
    out: String,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_info = HashMap::new();
        let mut typ_names = HashSet::new();
        let mut enum_names = HashSet::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    fn_info.insert(
                        f.name.clone(),
                        FnInfo {
                            fallible: f.fallible,
                        },
                    );
                }
                Item::Typ(t) => {
                    typ_names.insert(t.name.clone());
                }
                Item::Enum(e) => {
                    enum_names.insert(e.name.clone());
                }
                _ => {}
            }
        }
        Codegen {
            fn_info,
            typ_names,
            enum_names,
            out: String::new(),
        }
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) {
        self.line(0, "# Generated by the CuNi Ruby backend. Do not hand-edit.");
        self.out.push('\n');
        // ---- stdlib shims (mirror codegen_py's semantics exactly) ----
        self.line(0, "def say(x)");
        self.line(1, "puts(x.is_a?(String) ? x : _cuni_repr(x))");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_repr(x)");
        self.line(1, "case x");
        self.line(1, "when String then x.inspect.tr('\"', \"'\")");
        self.line(1, "when TrueClass then \"True\"");
        self.line(1, "when FalseClass then \"False\"");
        self.line(1, "when NilClass then \"None\"");
        self.line(
            1,
            "when Array then \"[\" + x.map { |e| _cuni_repr(e) }.join(\", \") + \"]\"",
        );
        self.line(
            1,
            "when Hash then \"{\" + x.map { |k, v| \"#{_cuni_repr(k)}: #{_cuni_repr(v)}\" }.join(\", \") + \"}\"",
        );
        self.line(1, "when Float then _cuni_float_str(x)");
        self.line(1, "else x.to_s");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        // Interpolation prints like Python f-strings (str(), not repr()):
        // bare strings stay bare, containers keep their repr.
        self.line(0, "def _cuni_interp_str(x)");
        self.line(1, "x.is_a?(String) ? x : _cuni_repr(x)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_float_str(x)");
        self.line(1, "s = x.to_s");
        self.line(1, "s.include?(\".\") || s.include?(\"e\") ? s : s + \".0\"");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def range(n)");
        self.line(1, "n = n.to_i");
        self.line(1, "return [] if n <= 0");
        self.line(1, "(0...n).to_a");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def abs(n)");
        self.line(1, "n.to_i.abs");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def min(a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "a <= b ? a : b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def max(a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "a >= b ? a : b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_slice(xs, a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "n = xs.length");
        self.line(
            1,
            "return (xs.is_a?(String) ? \"\" : []) if a < 0 || b < 0 || a > n || b > n || a > b",
        );
        self.line(1, "xs[a...b] || (xs.is_a?(String) ? \"\" : [])");
        self.line(0, "end");
        self.out.push('\n');
        // Integer division truncates toward zero (matches _cuni_div in py).
        self.line(0, "def _cuni_div(a, b)");
        self.line(1, "if a.is_a?(Integer) && b.is_a?(Integer) && b != 0");
        self.line(2, "q = a.div(b)");
        self.line(2, "r = a % b");
        self.line(2, "return (r != 0 && (a < 0) != (b < 0)) ? q + 1 : q");
        self.line(1, "end");
        self.line(1, "a.to_f / b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "class CuNiError < StandardError; end");
        self.out.push('\n');

        let mut script_stmts: Vec<&Stmt> = Vec::new();
        let mut top_scope: HashMap<String, VarKind> = HashMap::new();
        for item in &program.items {
            if let Item::Stmt(s) = item {
                script_stmts.push(s);
            } else {
                self.gen_item(item, &mut top_scope);
                self.out.push('\n');
            }
        }

        self.line(0, "def main");
        if script_stmts.is_empty() {
            self.line(1, "# no top-level statements");
        } else {
            for s in script_stmts {
                self.gen_stmt(1, s, &mut top_scope);
            }
        }
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "main");
    }

    fn gen_item(&mut self, item: &Item, scope: &mut HashMap<String, VarKind>) {
        match item {
            Item::Use(u) => {
                self.line(
                    0,
                    &format!(
                        "# use {} — portable CuNi module, not resolved by this backend",
                        u.name
                    ),
                );
            }
            Item::Ext(ext) => {
                let params = ext
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(0, &format!("def {}({})", ext.name, params));
                let rb_line = ext
                    .targets
                    .iter()
                    .find(|(t, _)| *t == "rb")
                    .map(|(_, raw)| raw.clone())
                    .unwrap_or_else(|| {
                        "raise NotImplementedError('no rb: mapping given')".to_string()
                    });
                self.line(1, &rb_line);
                self.line(0, "end");
            }
            Item::Typ(t) => {
                self.line(0, &format!("class {}", t.name));
                if !t.fields.is_empty() {
                    let attrs = t
                        .fields
                        .iter()
                        .map(|f| format!(":{}", f.name))
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(1, &format!("attr_accessor {}", attrs));
                    // Accept both positional (field order) and keyword construction.
                    self.line(1, "def initialize(*args, **kwargs)");
                    for (i, f) in t.fields.iter().enumerate() {
                        self.line(
                            2,
                            &format!("@{0} = kwargs.fetch(:{0}, args[{1}])", f.name, i),
                        );
                    }
                    self.line(1, "end");
                }
                self.line(0, "end");
            }
            Item::Iface(i) => {
                self.line(0, &format!("module {}", i.name));
                for m in &i.methods {
                    let params = m
                        .params
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(1, &format!("def {}({})", m.name, params));
                    self.line(2, "raise NotImplementedError");
                    self.line(1, "end");
                }
                self.line(0, "end");
            }
            Item::Enum(e) => {
                self.line(0, &format!("module {}", e.name));
                for (i, v) in e.variants.iter().enumerate() {
                    self.line(1, &format!("{} = {}", v.name, i));
                }
                self.line(0, "end");
            }
            Item::Def(f) => {
                let params = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(0, &format!("def {}({})", f.name, params));
                let mut fn_scope: HashMap<String, VarKind> = HashMap::new();
                if f.body.is_empty() {
                    self.line(1, "raise NotImplementedError  # CuNi stub body (`...`)");
                } else {
                    for s in &f.body {
                        self.gen_stmt(1, s, &mut fn_scope);
                    }
                }
                self.line(0, "end");
                if f.is_link {
                    self.line(
                        0,
                        &format!(
                            "# link {}: HTTP handler/client not emitted by the Ruby backend v1",
                            f.name
                        ),
                    );
                }
            }
            Item::Stmt(s) => self.gen_stmt(0, s, scope),
        }
    }

    fn gen_stmt(&mut self, indent: usize, stmt: &Stmt, scope: &mut HashMap<String, VarKind>) {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                let kind = ty
                    .as_ref()
                    .map(kind_of_type)
                    .or_else(|| kind_of_literal(value))
                    .unwrap_or(VarKind::Other);
                scope.insert(name.clone(), kind);
                self.gen_binding(indent, name, value, scope);
            }
            StmtKind::Assign { target, value } => {
                self.line(
                    indent,
                    &format!(
                        "{} = {}",
                        self.gen_expr(target, scope),
                        self.gen_expr(value, scope)
                    ),
                );
            }
            StmtKind::Ret(Some(e)) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("return {}", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("raise CuNiError.new({})", text));
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                self.line(indent, &format!("if {}", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, then_body, scope);
                if let Some(else_body) = else_body {
                    self.line(indent, "else");
                    self.gen_block(indent + 1, else_body, scope);
                }
                self.line(indent, "end");
            }
            StmtKind::For {
                binding: (a, b),
                iter,
                body,
            } => {
                let iter_kind = if let ExprKind::Ident(name) = &iter.kind {
                    scope.get(name).copied()
                } else {
                    None
                };
                let it = self.gen_expr(iter, scope);
                let header = match b {
                    Some(b) if iter_kind == Some(VarKind::Map) => {
                        format!("{}.each do |{}, {}|", it, a, b)
                    }
                    Some(b) => format!("{}.each_with_index do |{}, {}|", it, b, a),
                    None => format!("{}.each do |{}|", it, a),
                };
                // Note: `for i, x in xs` binds (i, x); each_with_index yields
                // |element, index|, so the block params are swapped to |x, i|.
                self.line(indent, &header);
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::Whl { cond, body } => {
                self.line(indent, &format!("while {}", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::ExprStmt(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &text);
            }
            StmtKind::Todo => {
                self.line(
                    indent,
                    "raise NotImplementedError  # CuNi stub body (`...`) — not yet written",
                );
            }
        }
    }

    fn gen_block(&mut self, indent: usize, stmts: &[Stmt], scope: &mut HashMap<String, VarKind>) {
        if stmts.is_empty() {
            self.line(indent, "# pass");
        } else {
            for s in stmts {
                self.gen_stmt(indent, s, scope);
            }
        }
    }

    fn gen_binding(
        &mut self,
        indent: usize,
        name: &str,
        value: &Expr,
        scope: &mut HashMap<String, VarKind>,
    ) {
        if let ExprKind::Unwrap { expr, handler } = &value.kind {
            let is_fallible_call = matches!(&expr.kind, ExprKind::Call { callee, .. } if matches!(&callee.kind, ExprKind::Ident(fname) if self.fn_info.get(fname).map_or(false, |i| i.fallible))
            );
            let inner = self.gen_expr(expr, scope);
            if is_fallible_call {
                self.line(indent, "begin");
                self.line(indent + 1, &format!("_unwrapped = {}", inner));
                self.line(indent, "rescue StandardError");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
                self.line(indent, "end");
            } else {
                self.line(indent, &format!("_unwrapped = {}", inner));
                self.line(indent, "if _unwrapped.nil?");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
                self.line(indent, "end");
            }
        } else {
            self.line(
                indent,
                &format!("{} = {}", name, self.gen_expr(value, scope)),
            );
        }
    }

    fn gen_expr(&self, expr: &Expr, scope: &HashMap<String, VarKind>) -> String {
        match &expr.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Float(f) => {
                let s = f.to_string();
                if s.contains('.') || s.contains('e') {
                    s
                } else {
                    format!("{}.0", s)
                }
            }
            ExprKind::Bool(true) => "true".to_string(),
            ExprKind::Bool(false) => "false".to_string(),
            ExprKind::Str(s) => format!("{:?}", s),
            ExprKind::InterpStr(parts) => {
                let mut s = String::from("\"");
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => {
                            s.push_str(
                                &t.replace('\\', "\\\\")
                                    .replace('"', "\\\"")
                                    .replace("#{", "\\#{"),
                            );
                        }
                        StrPartExpr::Expr(e) => {
                            s.push_str("#{");
                            s.push_str(&_cuni_interp(e, scope, self));
                            s.push('}');
                        }
                    }
                }
                s.push('"');
                s
            }
            ExprKind::NoneLit => "nil".to_string(),
            ExprKind::Ident(name) => name.clone(),
            ExprKind::List(items) => format!(
                "[{}]",
                items
                    .iter()
                    .map(|e| self.gen_expr(e, scope))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Map(pairs) => format!(
                "{{{}}}",
                pairs
                    .iter()
                    .map(|(k, v)| format!(
                        "{} => {}",
                        self.gen_expr(k, scope),
                        self.gen_expr(v, scope)
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Call { callee, args } => {
                if let ExprKind::Field { base, name } = &callee.kind {
                    if name == "push" {
                        return format!(
                            "{}.push({})",
                            self.gen_expr(base, scope),
                            args.iter()
                                .map(|a| self.gen_expr(a.expr(), scope))
                                .collect::<Vec<_>>()
                                .join(", ")
                        );
                    }
                    if name == "len" {
                        return format!("{}.length", self.gen_expr(base, scope));
                    }
                    if name == "slice" && args.len() == 2 {
                        return format!(
                            "_cuni_slice({}, {}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope),
                            self.gen_expr(args[1].expr(), scope)
                        );
                    }
                }
                let callee_s = self.gen_expr(callee, scope);
                // Typ constructor -> .new (positional or keyword).
                if self.typ_names.contains(&callee_s) {
                    if args.iter().all(|a| a.is_named()) && !args.is_empty() {
                        let parts: Vec<String> = args
                            .iter()
                            .filter_map(|a| match a {
                                CallArg::Named { name, value, .. } => {
                                    Some(format!("{}: {}", name, self.gen_expr(value, scope)))
                                }
                                _ => None,
                            })
                            .collect();
                        return format!("{}.new({})", callee_s, parts.join(", "));
                    }
                    return format!(
                        "{}.new({})",
                        callee_s,
                        args.iter()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .collect::<Vec<_>>()
                            .join(", ")
                    );
                }
                format!(
                    "{}({})",
                    callee_s,
                    args.iter()
                        .map(|a| self.gen_expr(a.expr(), scope))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
            ExprKind::Index { base, index } => format!(
                "{}[{}]",
                self.gen_expr(base, scope),
                self.gen_expr(index, scope)
            ),
            ExprKind::Field { base, name } => {
                let b = self.gen_expr(base, scope);
                // Enum variant access: Color.Green -> Color::Green
                if matches!(&base.kind, ExprKind::Ident(n) if self.enum_names.contains(n)) {
                    format!("{}::{}", b, name)
                } else {
                    format!("{}.{}", b, name)
                }
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_expr(lhs, scope);
                let r = self.gen_expr(rhs, scope);
                if matches!(op, BinOp::Div) {
                    format!("_cuni_div({}, {})", l, r)
                } else {
                    format!("({} {} {})", l, rb_binop(*op), r)
                }
            }
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("(!{})", self.gen_expr(expr, scope)),
                UnOp::Neg => format!("(-{})", self.gen_expr(expr, scope)),
            },
            ExprKind::Unwrap { .. } => {
                "nil  # UNSUPPORTED: ?? outside a let/mut binding".to_string()
            }
        }
    }
}

/// Interpolated values print like `say` (no quotes around strings).
fn _cuni_interp(e: &Expr, scope: &HashMap<String, VarKind>, cg: &Codegen) -> String {
    let v = cg.gen_expr(e, scope);
    format!("_cuni_interp_str({})", v)
}

fn kind_of_type(ty: &Type) -> VarKind {
    match ty {
        Type::Generic(name, _) if name == "list" => VarKind::List,
        Type::Generic(name, _) if name == "map" => VarKind::Map,
        _ => VarKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<VarKind> {
    match &e.kind {
        ExprKind::List(_) => Some(VarKind::List),
        ExprKind::Map(_) => Some(VarKind::Map),
        _ => None,
    }
}

fn rb_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}
