//! Ada backend — custom core-subset native seat (seat id `ada`).
//!
//! GNAT-targeted Ada: `Long_Long_Integer` for ints (`/` truncates toward
//! zero and `mod` is Python-floored natively — verified by hand for all sign
//! combinations), `Unbounded_String` for strings (no silent truncation or
//! blank-padding; `&` concatenates, `To_String` renders exactly), `Boolean`
//! for bools. Types are tracked and declarations are collected per program
//! unit (specification part before executable statements), like the `pas`
//! seat. `and`/`or` use the short-circuiting `and then`/`or else` forms to
//! match CuNi semantics. `say` is type-routed at emit time (`Img` strips the
//! leading blank of `'Image`; bools print `True`/`False`).
//!
//! Refuses everything beyond the core subset with the same honest `Err`s as
//! the core — including assignment to (constant `in`-mode) parameters, which
//! has no exact Ada mapping.
//!
//! Wiring note: `emit.rs`/`main.rs` dispatch is left to the parent — this file
//! only provides `generate`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

/// Ada string literal wrapped in `To_Unbounded_String`: `"` doubles;
/// control characters become `Character'Val(n)` chunks joined by `&`.
fn ada_str(s: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    // `cur` always starts as the `"` opener; `cur.len() > 1` means it holds
    // real content.
    let mut cur = String::from("\"");
    let mut in_lit = true;
    for c in s.chars() {
        if (c as u32) < 0x20 || (c as u32) == 0x7f {
            if in_lit {
                if cur.len() > 1 {
                    cur.push('"');
                    parts.push(format!("To_Unbounded_String({})", cur));
                }
                cur = String::from("\"");
                in_lit = false;
            }
            parts.push(format!(
                "To_Unbounded_String(Character'Val({}) & \"\")",
                c as u32
            ));
        } else {
            in_lit = true;
            if c == '"' {
                cur.push_str("\"\"");
            } else {
                cur.push(c);
            }
        }
    }
    if in_lit && cur.len() > 1 {
        cur.push('"');
        parts.push(format!("To_Unbounded_String({})", cur));
    }
    if parts.is_empty() {
        return "To_Unbounded_String(\"\")".to_string();
    }
    parts.join(" & ")
}

fn decl_of(name: &str, ty: Ty) -> String {
    match ty {
        Ty::Int => format!("{} : Long_Long_Integer;", name),
        Ty::Str => format!("{} : Unbounded_String;", name),
        Ty::Bool => format!("{} : Boolean;", name),
    }
}

fn ada_type_of(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "Long_Long_Integer",
        Ty::Str => "Unbounded_String",
        Ty::Bool => "Boolean",
    }
}

const HEADER: &str = concat!(
    "-- Generated by the CuNi core-subset backend. Do not hand-edit.\n",
    "with Ada.Text_IO; use Ada.Text_IO;\n",
    "with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;\n",
    "\n",
    "procedure Cuni_Main is\n",
    "   -- 'Image leaves a leading blank on non-negatives; strip it.\n",
    "   function Img (I : Long_Long_Integer) return String is\n",
    "      S : constant String := Long_Long_Integer'Image (I);\n",
    "   begin\n",
    "      if S (S'First) = ' ' then\n",
    "         return S (S'First + 1 .. S'Last);\n",
    "      end if;\n",
    "      return S;\n",
    "   end Img;\n",
    "   function Bool_Img (B : Boolean) return String is\n",
    "   begin\n",
    "      if B then\n",
    "         return \"True\";\n",
    "      else\n",
    "         return \"False\";\n",
    "      end if;\n",
    "   end Bool_Img;\n",
);

/// One scoping unit (the main procedure or one function): declarations are
/// collected while the body is generated, then emitted ahead of it.
struct Unit {
    body: String,
    decls: Vec<(String, Ty)>,
    declared: HashSet<String>,
    /// Lowercase of every declared name and parameter: Ada is
    /// case-insensitive, so a new binding that collides only by case is
    /// refused rather than silently aliasing.
    taken_lower: HashSet<String>,
    level: usize,
    /// Scope stack: source name -> (type, emitted name).
    frames: Vec<HashMap<String, (Ty, String)>>,
    /// Emitted names of parameters (assignment to them is refused: `in`
    /// mode parameters are constant).
    params: HashSet<String>,
    in_func: bool,
}

impl Unit {
    fn new() -> Self {
        Unit {
            body: String::new(),
            decls: Vec::new(),
            declared: HashSet::new(),
            taken_lower: HashSet::new(),
            level: 0,
            frames: Vec::new(),
            params: HashSet::new(),
            in_func: false,
        }
    }

    fn bl(&mut self, text: &str) {
        if !text.is_empty() {
            self.body.push_str(&"   ".repeat(self.level));
            self.body.push_str(text);
        }
        self.body.push('\n');
    }
}

struct Emitter {
    out: String,
    /// Function name -> (params, return type). Fully populated before any
    /// body is generated, so forward references are fine.
    sigs: HashMap<String, (Vec<(String, Ty)>, Ty)>,
    order: Vec<String>,
    counter: u32,
    unit: Unit,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        sigs: HashMap::new(),
        order: Vec::new(),
        counter: 0,
        unit: Unit::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn lookup(&self, name: &str) -> Option<(Ty, String)> {
        for f in self.unit.frames.iter().rev() {
            if let Some(v) = f.get(name) {
                return Some(v.clone());
            }
        }
        None
    }

    /// Bind `name` to a fresh local, renaming (`x__1`, …) when the name is
    /// already visible or was ever declared in this unit. A binding that
    /// collides only by case is refused.
    fn bind(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let reuse = self.lookup(name).is_some() || self.unit.declared.contains(name);
        let emitted = if reuse {
            self.counter += 1;
            format!("{}__{}", name, self.counter)
        } else {
            name.to_string()
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "binding `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower);
        if !self.unit.declared.contains(&emitted) {
            self.unit.declared.insert(emitted.clone());
            self.unit.decls.push((emitted.clone(), ty));
        }
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn bind_param(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let emitted = match self.lookup(name) {
            Some(_) => {
                self.counter += 1;
                format!("{}__{}", name, self.counter)
            }
            None => name.to_string(),
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "parameter `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower.clone());
        // Ada identifiers are case-insensitive; reserve the exact emitted
        // spelling too so a later local cannot shadow the parameter name.
        self.unit.declared.insert(emitted.clone());
        self.unit.params.insert(emitted.clone());
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn check_ann(&self, name: &str, ty: &Option<Type>, vt: Ty, kw: &str) -> Result<(), String> {
        if let Some(t) = ty {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!(
                    "{} {}: annotated type disagrees with value type; refusing",
                    kw, name
                ));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        if f.name.to_lowercase().starts_with("cuni_") {
            return Err(format!(
                "def {}: reserved cuni_ prefix (collides with helpers); refusing",
                f.name
            ));
        }
        if f.name.eq_ignore_ascii_case("cuni_main") || f.name.eq_ignore_ascii_case("main") {
            return Err("def main: collides with the Ada main procedure; refusing".into());
        }
        if f.name.eq_ignore_ascii_case("img") || f.name.eq_ignore_ascii_case("bool_img") {
            return Err(format!(
                "def {}: collides with the Img/Bool_Img helpers (Ada is case-insensitive); refusing",
                f.name
            ));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    /// `function Add (A : Long_Long_Integer; B : Long_Long_Integer) return Long_Long_Integer`
    fn fn_sig(&self, name: &str, pinfo: &[(String, Ty)], ret: Ty) -> String {
        let params: Vec<String> = pinfo
            .iter()
            .map(|(n, t)| format!("{} : {}", n, ada_type_of(*t)))
            .collect();
        format!(
            "function {} ({}) return {}",
            ada_ident(name),
            params.join("; "),
            ada_type_of(ret)
        )
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        // First pass: collect def signatures, refuse non-core items.
        let mut seen_lower: HashSet<String> = HashSet::new();
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    if !seen_lower.insert(f.name.to_lowercase()) {
                        return Err(format!(
                            "def {}: duplicate (case-insensitive) definition; refusing",
                            f.name
                        ));
                    }
                    let mut params = Vec::new();
                    for p in &f.params {
                        params.push((p.name.clone(), ty_of(&p.ty)?));
                    }
                    let ret = ty_of(&f.ret_type)?;
                    self.sigs.insert(f.name.clone(), (params, ret));
                    self.order.push(f.name.clone());
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        // Second pass: function bodies (any order — signatures are complete).
        // Records the actual (possibly renamed) parameter lists so the
        // forward specs carry exact signatures.
        let mut bodies: Vec<(String, Vec<(String, Ty)>, Ty, String)> = Vec::new();
        for name in self.order.clone() {
            let f = program
                .items
                .iter()
                .find_map(|it| match it {
                    Item::Def(f) if f.name == name => Some(f),
                    _ => None,
                })
                .expect("def present");
            let (pinfo, ret, code) = self.gen_def(f)?;
            bodies.push((name, pinfo, ret, code));
        }
        // Main procedure unit.
        self.unit = Unit::new();
        self.unit.level = 1;
        self.unit.frames.push(HashMap::new());
        for s in script {
            self.gen_stmt(s)?;
        }
        let main_unit = std::mem::replace(&mut self.unit, Unit::new());

        self.out.push_str(HEADER);
        // Forward specs so forward references and mutual recursion compile.
        for (name, pinfo, ret, _) in &bodies {
            self.out
                .push_str(&format!("   {};\n", self.fn_sig(name, pinfo, *ret)));
        }
        for (n, t) in &main_unit.decls {
            self.out.push_str(&format!("   {}\n", decl_of(n, *t)));
        }
        // Function bodies are declarations in Ada: they must precede
        // `begin` (the forward specs above already cover mutual recursion).
        for (_, _, _, code) in &bodies {
            self.out.push_str(code);
        }
        self.out.push_str("begin\n");
        self.out.push_str(&main_unit.body);
        self.out.push_str("end Cuni_Main;\n");
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(Vec<(String, Ty)>, Ty, String), String> {
        let (params, ret) = self
            .sigs
            .get(&f.name)
            .cloned()
            .ok_or_else(|| format!("internal: missing signature for `{}`", f.name))?;
        let saved = std::mem::replace(&mut self.unit, Unit::new());
        self.unit.level = 2;
        self.unit.in_func = true;
        self.unit.frames.push(HashMap::new());
        let mut pinfo: Vec<(String, Ty)> = Vec::new();
        for (n, t) in &params {
            let emitted = self.bind_param(n, *t)?;
            pinfo.push((emitted, *t));
        }
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        let finished = std::mem::replace(&mut self.unit, saved);

        let mut s = String::new();
        s.push_str(&format!("   {} is\n", self.fn_sig(&f.name, &pinfo, ret)));
        for (n, t) in &finished.decls {
            s.push_str(&format!("      {}\n", decl_of(n, *t)));
        }
        s.push_str("   begin\n");
        for line in finished.body.lines() {
            if line.trim().is_empty() {
                s.push('\n');
            } else {
                s.push_str("   ");
                s.push_str(line);
                s.push('\n');
            }
        }
        s.push_str(&format!("   end {};\n", ada_ident(&f.name)));
        Ok((pinfo, ret, s))
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "let")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "mut")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                let tname = match &target.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => {
                        return Err(
                            "complex assignment target: beyond core subset; refusing".into()
                        )
                    }
                };
                let (_, emitted) = self
                    .lookup(&tname)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", tname))?;
                if self.unit.params.contains(&emitted) {
                    return Err(format!(
                        "assignment to parameter `{}`: Ada `in`-mode parameters are constant; refusing",
                        tname
                    ));
                }
                let (v, _) = self.gen_expr(value)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                if !self.unit.in_func {
                    return Err("top-level ret: no return slot in the main procedure; refusing".into());
                }
                match e {
                    Some(x) => {
                        let (v, _) = self.gen_expr(x)?;
                        self.unit.bl(&format!("return {};", v));
                    }
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                }
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("if {} then", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                if let Some(eb) = else_body {
                    self.unit.bl("else");
                    self.unit.level += 1;
                    self.unit.frames.push(HashMap::new());
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.unit.frames.pop();
                    self.unit.level -= 1;
                }
                self.unit.bl("end if;");
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("while {} loop", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                self.unit.bl("end loop;");
                Ok(())
            }
            StmtKind::ExprStmt(e) => {
                // Only `say(...)` calls allowed as bare expression statements.
                match &e.kind {
                    ExprKind::Call { callee, args } => {
                        if let ExprKind::Ident(n) = &callee.kind {
                            if n == "say" {
                                if args.len() != 1 {
                                    return Err(
                                        "say: exactly one argument in core subset; refusing".into()
                                    );
                                }
                                let (v, vt) = self.gen_expr(args[0].expr())?;
                                match vt {
                                    Ty::Int => self.unit.bl(&format!("Put_Line (Img ({}));", v)),
                                    Ty::Str => {
                                        self.unit.bl(&format!("Put_Line (To_String ({}));", v))
                                    }
                                    Ty::Bool => {
                                        self.unit.bl(&format!("Put_Line (Bool_Img ({}));", v))
                                    }
                                }
                                return Ok(());
                            }
                        }
                        Err("bare call (non-say): beyond core subset; refusing".into())
                    }
                    _ => Err("bare expression: beyond core subset; refusing".into()),
                }
            }
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((n.to_string(), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b { "True".into() } else { "False".into() },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((ada_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let (t, emitted) = self
                    .lookup(n)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((emitted, t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self
                    .sigs
                    .get(&name)
                    .map(|(_, r)| *r)
                    .ok_or_else(|| format!("call to unknown function `{}`: refusing", name))?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{} ({})", ada_ident(&name), as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("({} & {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        return Err("mixed-type `+`: beyond core subset; refusing".into());
                    }
                    BinOp::Sub => {
                        require_ints(lt, rt, &BinOp::Sub)?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        require_ints(lt, rt, &BinOp::Mul)?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        require_ints(lt, rt, &BinOp::Div)?;
                        // Ada integer `/` truncates toward zero (CuNi).
                        Ok((format!("({} / {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        require_ints(lt, rt, &BinOp::Mod)?;
                        // Ada `mod` is Python-floored (CuNi).
                        Ok((format!("({} mod {})", l, r), Ty::Int))
                    }
                    BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Gt | BinOp::Le | BinOp::Ge => {
                        let o = ada_cmp_op(op);
                        if lt == Ty::Str && rt == Ty::Str {
                            // Unbounded_String has no ordering operators;
                            // compare the exact String views instead.
                            return Ok((
                                format!("(To_String ({}) {} To_String ({}))", l, o, r),
                                Ty::Bool,
                            ));
                        }
                        require_same(lt, rt, op)?;
                        Ok((format!("({} {} {})", l, o, r), Ty::Bool))
                    }
                    BinOp::And => {
                        require_bools(lt, rt, "and")?;
                        // Short-circuiting form, matching CuNi semantics.
                        Ok((format!("({} and then {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        require_bools(lt, rt, "or")?;
                        Ok((format!("({} or else {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(not {})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }
}

/// Ada identifiers are case-insensitive; capitalize the first letter for
/// idiomatic output (purely cosmetic — semantics unchanged).
fn ada_ident(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn ada_cmp_op(op: &BinOp) -> &'static str {
    match op {
        BinOp::Eq => "=",
        BinOp::Ne => "/=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        _ => "=",
    }
}

fn require_ints(l: Ty, r: Ty, op: &BinOp) -> Result<(), String> {
    if l == Ty::Int && r == Ty::Int {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-int: beyond core subset; refusing",
            op_sym(op)
        ))
    }
}

fn require_bools(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Bool && r == Ty::Bool {
        Ok(())
    } else {
        Err(format!("`{}` on non-bool: beyond core subset; refusing", op))
    }
}

fn require_same(l: Ty, r: Ty, op: &BinOp) -> Result<(), String> {
    if l == r && l != Ty::Str {
        Ok(())
    } else {
        Err(format!(
            "`{}` on mismatched types: beyond core subset; refusing",
            op_sym(op)
        ))
    }
}

fn op_sym(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
    }
}
