//! Pascal backend — custom core-subset native seat (seat id `pas`).
//!
//! Pascal is statically typed with mandatory declarations, so this seat is a
//! custom emitter rather than a [`crate::codegen_core`] spec: it tracks every
//! binding's type (`Int`/`Str`/`Bool`), collects declarations per program unit
//! (`var` sections before executable statements), and refuses anything outside
//! the core subset with the same honest `Err`s as the core. Targets Free
//! Pascal (and Delphi where noted); no mode directive is required.
//!
//! Emitted shape:
//! ```pascal
//! { Generated by the CuNi core-subset backend. Do not hand-edit. }
//! program Main;
//!
//! var
//!   x: int64;
//!
//! procedure cuni_say_int(x: int64);
//! begin
//!   writeln(x);
//! end;
//!
//! function cuni_mod(a, b: int64): int64;
//! begin
//!   cuni_mod := ((a mod b) + b) mod b;
//! end;
//!
//! function add(a: int64; b: int64): int64; forward;
//!
//! function add(a: int64; b: int64): int64;
//! var
//!   t: int64;
//! begin
//!   t := (a + b);
//!   add := (t);
//!   exit;
//! end;
//!
//! begin
//!   x := 5;
//!   cuni_say_int(x);
//! end.
//! ```
//!
//! Semantics notes:
//! - Integer `/` maps to Pascal's `div`, which truncates toward zero — CuNi
//!   semantics, no helper needed. `%` maps to `cuni_mod(a, b) =
//!   ((a mod b) + b) mod b`: Pascal's `mod` truncates like C, and the double
//!   application yields Python-floor semantics (verified by hand for all sign
//!   combinations).
//! - Strings are `AnsiString` (dynamic length, exact — *not* `ShortString`,
//!   which would silently truncate at 255 chars in FPC's default mode).
//!   Concatenation is `+`. Literals escape `'` as `''`; control characters
//!   become `#nn` (`'a'#10'b'`).
//! - `say` is type-routed at emit time to `cuni_say_int` / `cuni_say_str` /
//!   `cuni_say_bool` (`writeln` procedures). Booleans print `True`/`False`
//!   (native `writeln(True)` would print `TRUE`).
//! - Function results are assigned to the function name (`add := expr`) — the
//!   portable convention that works in every Pascal mode (`Result` needs
//!   Delphi/objfpc mode). Every `ret` is followed by `exit;`: without it, a
//!   `ret` inside a branch would fall through to later statements.
//! - Pascal value parameters are copies by default, so rebinding a parameter
//!   never touches the caller — no Fortran-style refusal needed.
//! - A `forward;` declaration is emitted for every user function, so forward
//!   references and mutual recursion compile.
//! - Then/else bodies are always wrapped in `begin`/`end` (no dangling else,
//!   and no semicolon is ever emitted between `end` and `else`).
//! - Block-scoped rebinding (`let` of an already-visible name) is renamed
//!   (`x__1`, …) so shadowing cannot collide in Pascal's flat scopes.
//! - `def main` is refused (case-insensitive clash with `program Main`), as is
//!   any `def` starting with `cuni_` (helper collision). A top-level or bare
//!   `ret` is refused — the main program block has no return slot.
//!
//! Wiring note: `emit.rs`/`main.rs` dispatch is left to the parent — this file
//! only provides `generate`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

/// Pascal string literal: `'`-quoted with `''` doubling; control characters
/// become `#nn` (which concatenates implicitly: `'a'#10'b'`).
fn pas_str(s: &str) -> String {
    let mut r = String::new();
    let mut in_lit = false;
    for c in s.chars() {
        if (c as u32) < 0x20 || (c as u32) == 0x7f {
            if in_lit {
                r.push('\'');
                in_lit = false;
            }
            r.push_str(&format!("#{}", c as u32));
        } else {
            if !in_lit {
                r.push('\'');
                in_lit = true;
            }
            if c == '\'' {
                r.push_str("''");
            } else {
                r.push(c);
            }
        }
    }
    if in_lit {
        r.push('\'');
    }
    if r.is_empty() {
        r.push_str("''");
    }
    r
}

fn decl_of(name: &str, ty: Ty) -> String {
    match ty {
        Ty::Int => format!("{}: int64", name),
        Ty::Str => format!("{}: AnsiString", name),
        Ty::Bool => format!("{}: boolean", name),
    }
}

fn ret_type_of(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "int64",
        Ty::Str => "AnsiString",
        Ty::Bool => "boolean",
    }
}

const HELPERS: &str = concat!(
    "procedure cuni_say_int(x: int64);\n",
    "begin\n",
    "  writeln(x);\n",
    "end;\n",
    "\n",
    "procedure cuni_say_str(const s: AnsiString);\n",
    "begin\n",
    "  writeln(s);\n",
    "end;\n",
    "\n",
    "procedure cuni_say_bool(b: boolean);\n",
    "begin\n",
    "  if b then\n",
    "    writeln('True')\n",
    "  else\n",
    "    writeln('False');\n",
    "end;\n",
    "\n",
    "function cuni_mod(a, b: int64): int64;\n",
    "begin\n",
    "  cuni_mod := ((a mod b) + b) mod b;\n",
    "end;\n",
);

/// One scoping unit (the main program or one function): declarations are
/// collected while the body is generated, then emitted ahead of it.
struct Unit {
    body: String,
    decls: Vec<(String, Ty)>,
    declared: HashSet<String>,
    /// Lowercase of every declared name, parameter, and (in functions) the
    /// function name: Pascal is case-insensitive, so a new binding that
    /// collides only by case is refused rather than silently aliasing.
    taken_lower: HashSet<String>,
    level: usize,
    /// Scope stack: source name -> (type, emitted name).
    frames: Vec<HashMap<String, (Ty, String)>>,
    in_func: bool,
    /// Function name when inside a def (for `name := expr` returns).
    func_name: String,
}

impl Unit {
    fn new() -> Self {
        Unit {
            body: String::new(),
            decls: Vec::new(),
            declared: HashSet::new(),
            taken_lower: HashSet::new(),
            level: 0,
            frames: Vec::new(),
            in_func: false,
            func_name: String::new(),
        }
    }

    fn bl(&mut self, text: &str) {
        if !text.is_empty() {
            self.body.push_str(&"  ".repeat(self.level));
            self.body.push_str(text);
        }
        self.body.push('\n');
    }
}

struct Emitter {
    out: String,
    /// Function name -> (params, return type). Fully populated before any
    /// body is generated, so forward references are fine.
    sigs: HashMap<String, (Vec<(String, Ty)>, Ty)>,
    /// Definition order (for forward declarations and bodies).
    order: Vec<String>,
    counter: u32,
    unit: Unit,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        sigs: HashMap::new(),
        order: Vec::new(),
        counter: 0,
        unit: Unit::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn lookup(&self, name: &str) -> Option<(Ty, String)> {
        for f in self.unit.frames.iter().rev() {
            if let Some(v) = f.get(name) {
                return Some(v.clone());
            }
        }
        None
    }

    /// Bind `name` to a fresh local. If the name is already visible *or* was
    /// ever declared in this unit (declarations hoist to the unit's `var`
    /// section, so a later same-name binding would collide), the emitted name
    /// is renamed (`x__1`). A binding that collides only by case is refused —
    /// Pascal would silently alias it.
    fn bind(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let reuse = self.lookup(name).is_some() || self.unit.declared.contains(name);
        let emitted = if reuse {
            self.counter += 1;
            format!("{}__{}", name, self.counter)
        } else {
            name.to_string()
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "binding `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower);
        if !self.unit.declared.contains(&emitted) {
            self.unit.declared.insert(emitted.clone());
            self.unit.decls.push((emitted.clone(), ty));
        }
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    /// Bind a parameter: enters the scope (with rename on collision, e.g.
    /// against the function name) but adds no local declaration — the
    /// parameter is declared in the function signature.
    fn bind_param(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let emitted = match self.lookup(name) {
            Some(_) => {
                self.counter += 1;
                format!("{}__{}", name, self.counter)
            }
            None => name.to_string(),
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "parameter `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower);
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn check_ann(&self, name: &str, ty: &Option<Type>, vt: Ty, kw: &str) -> Result<(), String> {
        if let Some(t) = ty {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!(
                    "{} {}: annotated type disagrees with value type; refusing",
                    kw, name
                ));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        if f.name.to_lowercase().starts_with("cuni_") {
            return Err(format!(
                "def {}: reserved cuni_ prefix (collides with helpers); refusing",
                f.name
            ));
        }
        if f.name.eq_ignore_ascii_case("main") {
            return Err("def main: collides with `program Main` (Pascal is case-insensitive); refusing".into());
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    /// `function name(a: int64; b: int64): int64` (no trailing `;`).
    fn fn_sig(&self, name: &str, pinfo: &[(String, Ty)], ret: Ty) -> String {
        let params: Vec<String> = pinfo
            .iter()
            .map(|(n, t)| format!("{}: {}", n, ret_type_of(*t)))
            .collect();
        format!(
            "function {}({}): {}",
            name,
            params.join("; "),
            ret_type_of(ret)
        )
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        // First pass: collect def signatures, refuse non-core items.
        let mut seen_lower: HashSet<String> = HashSet::new();
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    if !seen_lower.insert(f.name.to_lowercase()) {
                        return Err(format!(
                            "def {}: duplicate (case-insensitive) definition; refusing",
                            f.name
                        ));
                    }
                    let mut params = Vec::new();
                    for p in &f.params {
                        params.push((p.name.clone(), ty_of(&p.ty)?));
                    }
                    let ret = ty_of(&f.ret_type)?;
                    self.sigs.insert(f.name.clone(), (params, ret));
                    self.order.push(f.name.clone());
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        // Second pass: function bodies (any order — signatures are complete).
        // The actual (possibly renamed) parameter lists are recorded so the
        // forward declarations carry exact signatures.
        let mut bodies: Vec<(String, Vec<(String, Ty)>, Ty, String)> = Vec::new();
        for name in self.order.clone() {
            let f = program
                .items
                .iter()
                .find_map(|it| match it {
                    Item::Def(f) if f.name == name => Some(f),
                    _ => None,
                })
                .expect("def present");
            let (pinfo, ret, code) = self.gen_def(f)?;
            bodies.push((name, pinfo, ret, code));
        }
        // Main program unit.
        self.unit = Unit::new();
        self.unit.level = 1;
        self.unit.frames.push(HashMap::new());
        for s in script {
            self.gen_stmt(s)?;
        }
        let main_unit = std::mem::replace(&mut self.unit, Unit::new());

        self.out.push_str(
            "{ Generated by the CuNi core-subset backend. Do not hand-edit. }\n",
        );
        self.out.push_str("program Main;\n\n");
        if !main_unit.decls.is_empty() {
            self.out.push_str("var\n");
            for (n, t) in &main_unit.decls {
                self.out.push_str(&format!("  {};\n", decl_of(n, *t)));
            }
            self.out.push('\n');
        }
        self.out.push_str(HELPERS);
        self.out.push('\n');
        // Forward declarations (exact signatures) so mutual recursion compiles.
        for (name, pinfo, ret, _) in &bodies {
            self.out
                .push_str(&format!("{}; forward;\n", self.fn_sig(name, pinfo, *ret)));
        }
        self.out.push('\n');
        for (_, _, _, code) in &bodies {
            self.out.push_str(code);
            self.out.push('\n');
        }
        self.out.push_str("begin\n");
        self.out.push_str(&main_unit.body);
        self.out.push_str("end.\n");
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(Vec<(String, Ty)>, Ty, String), String> {
        let (params, ret) = self
            .sigs
            .get(&f.name)
            .cloned()
            .ok_or_else(|| format!("internal: missing signature for `{}`", f.name))?;
        let saved = std::mem::replace(&mut self.unit, Unit::new());
        self.unit.level = 1;
        self.unit.in_func = true;
        self.unit.func_name = f.name.clone();
        self.unit.frames.push(HashMap::new());
        // Pre-bind the function name so a user binding with the same name
        // renames instead of clobbering the return slot.
        self.unit.frames[0].insert(
            f.name.clone(),
            (ret, f.name.clone()),
        );
        self.unit.declared.insert(f.name.clone());
        self.unit.taken_lower.insert(f.name.to_lowercase());
        let mut pinfo: Vec<(String, Ty)> = Vec::new();
        for (n, t) in &params {
            let emitted = self.bind_param(n, *t)?;
            pinfo.push((emitted, *t));
        }
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        let finished = std::mem::replace(&mut self.unit, saved);

        let mut s = String::new();
        s.push_str(&format!("{};\n", self.fn_sig(&f.name, &pinfo, ret)));
        if !finished.decls.is_empty() {
            s.push_str("var\n");
            for (n, t) in &finished.decls {
                s.push_str(&format!("  {};\n", decl_of(n, *t)));
            }
        }
        s.push_str("begin\n");
        s.push_str(&finished.body);
        s.push_str("end;\n");
        Ok((pinfo, ret, s))
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "let")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "mut")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                let tname = match &target.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => {
                        return Err(
                            "complex assignment target: beyond core subset; refusing".into()
                        )
                    }
                };
                let (_, emitted) = self
                    .lookup(&tname)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", tname))?;
                let (v, _) = self.gen_expr(value)?;
                self.unit.bl(&format!("{} := {};", emitted, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                if !self.unit.in_func {
                    return Err(
                        "top-level ret: the main program block has no return slot; refusing"
                            .into(),
                    );
                }
                match e {
                    Some(x) => {
                        let (v, _) = self.gen_expr(x)?;
                        let fname = self.unit.func_name.clone();
                        // Assign to the function name, then exit: without
                        // `exit` a `ret` inside a branch would fall through.
                        self.unit.bl(&format!("{} := {};", fname, v));
                        self.unit.bl("exit;");
                    }
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                }
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                // No semicolon may precede `else`, so the then-block closes
                // with a bare `end`.
                self.unit.bl(&format!("if ({}) then", c));
                self.unit.bl("begin");
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                if let Some(eb) = else_body {
                    self.unit.bl("end");
                    self.unit.bl("else");
                    self.unit.bl("begin");
                    self.unit.level += 1;
                    self.unit.frames.push(HashMap::new());
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.unit.frames.pop();
                    self.unit.level -= 1;
                    self.unit.bl("end;");
                } else {
                    self.unit.bl("end;");
                }
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("while ({}) do", c));
                self.unit.bl("begin");
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                self.unit.bl("end;");
                Ok(())
            }
            StmtKind::ExprStmt(e) => {
                // Only `say(...)` calls allowed as bare expression statements.
                match &e.kind {
                    ExprKind::Call { callee, args } => {
                        if let ExprKind::Ident(n) = &callee.kind {
                            if n == "say" {
                                if args.len() != 1 {
                                    return Err(
                                        "say: exactly one argument in core subset; refusing".into()
                                    );
                                }
                                let (v, vt) = self.gen_expr(args[0].expr())?;
                                let helper = match vt {
                                    Ty::Int => "cuni_say_int",
                                    Ty::Str => "cuni_say_str",
                                    Ty::Bool => "cuni_say_bool",
                                };
                                self.unit.bl(&format!("{}({});", helper, v));
                                return Ok(());
                            }
                        }
                        Err("bare call (non-say): beyond core subset; refusing".into())
                    }
                    _ => Err("bare expression: beyond core subset; refusing".into()),
                }
            }
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((n.to_string(), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b {
                    "True".to_string()
                } else {
                    "False".to_string()
                },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((pas_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let (t, emitted) = self
                    .lookup(n)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((emitted, t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self
                    .sigs
                    .get(&name)
                    .map(|(_, r)| *r)
                    .ok_or_else(|| format!("call to unknown function `{}`: refusing", name))?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("({} + {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        return Err("mixed-type `+`: beyond core subset; refusing".into());
                    }
                    BinOp::Sub => {
                        require_ints(lt, rt, "-")?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        require_ints(lt, rt, "*")?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        require_ints(lt, rt, "/")?;
                        // Pascal's `div` truncates toward zero (CuNi).
                        Ok((format!("({} div {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        require_ints(lt, rt, "%")?;
                        // Pascal's `mod` truncates; the helper floors.
                        Ok((format!("cuni_mod({}, {})", l, r), Ty::Int))
                    }
                    BinOp::Eq => Ok((format!("({} = {})", l, r), Ty::Bool)),
                    BinOp::Ne => Ok((format!("({} <> {})", l, r), Ty::Bool)),
                    BinOp::Lt => Ok((format!("({} < {})", l, r), Ty::Bool)),
                    BinOp::Gt => Ok((format!("({} > {})", l, r), Ty::Bool)),
                    BinOp::Le => Ok((format!("({} <= {})", l, r), Ty::Bool)),
                    BinOp::Ge => Ok((format!("({} >= {})", l, r), Ty::Bool)),
                    BinOp::And => {
                        require_bools(lt, rt, "and")?;
                        Ok((format!("({} and {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        require_bools(lt, rt, "or")?;
                        Ok((format!("({} or {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(not {})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }
}

fn require_ints(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Int && r == Ty::Int {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-int: beyond core subset; refusing",
            op
        ))
    }
}

fn require_bools(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Bool && r == Ty::Bool {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-bool: beyond core subset; refusing",
            op
        ))
    }
}
