//! Objective-C backend — custom core-subset native seat (seat id `m-objc`).
//!
//! Objective-C is a strict superset of C, so this seat emits plain C (no
//! Foundation — it may not be installed) and is compiled with
//! `gcc -x objective-c`; the `.m` extension plus the ObjC compiler driver is
//! what makes it the seat. It is *not* the full `c` seat's Val runtime: that
//! runtime's `%` truncates like C while CuNi needs Python-floored modulo, so
//! this seat is a small dedicated emitter with a `cuni_mod` helper.
//!
//! Types are tracked (`Int`/`Str`/`Bool`) and declarations are collected per
//! program unit: `long long` for ints (C `/` truncates toward zero — CuNi
//! semantics), `const char *` for strings (`cuni_concat` builds fresh
//! buffers; literals escape `"`/`\\`/controls), `long long` 0/1 for bools
//! (`True`/`False` at print). `say` is type-routed at emit time.
//! Refuses everything beyond the core subset with the same honest `Err`s as
//! the core.
//!
//! Wiring note: `emit.rs`/`main.rs` dispatch is left to the parent — this file
//! only provides `generate`. The Rust module is `codegen_m_objc` (the seat id
//! `m-objc` is not a valid Rust identifier).

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

/// C string literal: `"`-quoted; `"` and `\` escaped; controls become
/// 3-digit octal escapes (unambiguous, unlike `\x`).
fn c_str(s: &str) -> String {
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            '\n' => r.push_str("\\n"),
            '\t' => r.push_str("\\t"),
            '\r' => r.push_str("\\r"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                r.push_str(&format!("\\{:03o}", c as u32))
            }
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

fn decl_of(name: &str, ty: Ty) -> String {
    match ty {
        Ty::Int => format!("long long {};", name),
        Ty::Str => format!("const char *{};", name),
        Ty::Bool => format!("long long {};", name),
    }
}

fn c_type_of(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "long long",
        Ty::Str => "const char *",
        Ty::Bool => "long long",
    }
}

const HEADER: &str = concat!(
    "// CuNi Objective-C seat: plain C (no Foundation), compiled with gcc -x objective-c.\n",
    "// Generated by the CuNi core-subset backend. Do not hand-edit.\n",
    "#include <stdio.h>\n",
    "#include <stdlib.h>\n",
    "#include <string.h>\n",
    "\n",
    "/* Python-floored modulo (C's % truncates). */\n",
    "static long long cuni_mod(long long a, long long b) { return ((a % b) + b) % b; }\n",
    "static char *cuni_concat(const char *a, const char *b) {\n",
    "    size_t n = strlen(a) + strlen(b);\n",
    "    char *p = (char *)malloc(n + 1);\n",
    "    strcpy(p, a);\n",
    "    strcat(p, b);\n",
    "    return p;\n",
    "}\n",
    "static void cuni_say_int(long long x) { printf(\"%lld\\n\", x); }\n",
    "static void cuni_say_str(const char *x) { printf(\"%s\\n\", x ? x : \"\"); }\n",
    "static void cuni_say_bool(long long x) { printf(\"%s\\n\", x ? \"True\" : \"False\"); }\n",
    "\n",
);

/// One scoping unit (main or one function): declarations are collected while
/// the body is generated, then emitted ahead of it.
struct Unit {
    body: String,
    decls: Vec<(String, Ty)>,
    declared: HashSet<String>,
    level: usize,
    /// Scope stack: source name -> (type, emitted name).
    frames: Vec<HashMap<String, (Ty, String)>>,
    in_func: bool,
}

impl Unit {
    fn new() -> Self {
        Unit {
            body: String::new(),
            decls: Vec::new(),
            declared: HashSet::new(),
            level: 0,
            frames: Vec::new(),
            in_func: false,
        }
    }

    fn bl(&mut self, text: &str) {
        if !text.is_empty() {
            self.body.push_str(&"    ".repeat(self.level));
            self.body.push_str(text);
        }
        self.body.push('\n');
    }
}

struct Emitter {
    out: String,
    /// Function name -> (params, return type). Fully populated before any
    /// body is generated, so forward references are fine.
    sigs: HashMap<String, (Vec<(String, Ty)>, Ty)>,
    order: Vec<String>,
    counter: u32,
    unit: Unit,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        sigs: HashMap::new(),
        order: Vec::new(),
        counter: 0,
        unit: Unit::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn lookup(&self, name: &str) -> Option<(Ty, String)> {
        for f in self.unit.frames.iter().rev() {
            if let Some(v) = f.get(name) {
                return Some(v.clone());
            }
        }
        None
    }

    /// Bind `name` to a fresh local, renaming (`x__1`, …) on shadowing or on
    /// collision with an already-declared name (declarations hoist, so a
    /// later same-name binding would collide).
    fn bind(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let reuse = self.lookup(name).is_some() || self.unit.declared.contains(name);
        let emitted = if reuse {
            self.counter += 1;
            format!("{}__{}", name, self.counter)
        } else {
            name.to_string()
        };
        if !self.unit.declared.contains(&emitted) {
            self.unit.declared.insert(emitted.clone());
            self.unit.decls.push((emitted.clone(), ty));
        }
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn bind_param(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let emitted = match self.lookup(name) {
            Some(_) => {
                self.counter += 1;
                format!("{}__{}", name, self.counter)
            }
            None => name.to_string(),
        };
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn check_ann(&self, name: &str, ty: &Option<Type>, vt: Ty, kw: &str) -> Result<(), String> {
        if let Some(t) = ty {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!(
                    "{} {}: annotated type disagrees with value type; refusing",
                    kw, name
                ));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        if f.name.starts_with("cuni_") {
            return Err(format!(
                "def {}: reserved cuni_ prefix (collides with helpers); refusing",
                f.name
            ));
        }
        if f.name == "main" {
            return Err("def main: collides with the C entry point; refusing".into());
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        // First pass: collect def signatures, refuse non-core items.
        let mut seen: HashSet<String> = HashSet::new();
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    if !seen.insert(f.name.clone()) {
                        return Err(format!("def {}: duplicate definition; refusing", f.name));
                    }
                    let mut params = Vec::new();
                    for p in &f.params {
                        params.push((p.name.clone(), ty_of(&p.ty)?));
                    }
                    let ret = ty_of(&f.ret_type)?;
                    self.sigs.insert(f.name.clone(), (params, ret));
                    self.order.push(f.name.clone());
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        // Second pass: function bodies (any order — signatures are complete).
        let mut fns: Vec<String> = Vec::new();
        for name in self.order.clone() {
            let f = program
                .items
                .iter()
                .find_map(|it| match it {
                    Item::Def(f) if f.name == name => Some(f),
                    _ => None,
                })
                .expect("def present");
            fns.push(self.gen_def(f)?);
        }
        // Main unit.
        self.unit = Unit::new();
        self.unit.level = 1;
        self.unit.frames.push(HashMap::new());
        for s in script {
            self.gen_stmt(s)?;
        }
        let main_unit = std::mem::replace(&mut self.unit, Unit::new());

        self.out.push_str(HEADER);
        // Forward declarations so forward references and recursion compile.
        for name in &self.order {
            let (params, ret) = self.sigs.get(name).expect("sig present");
            let ps: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{} {}", c_type_of(*t), n))
                .collect();
            self.out.push_str(&format!(
                "static {} {}({});\n",
                c_type_of(*ret),
                name,
                ps.join(", ")
            ));
        }
        if !self.order.is_empty() {
            self.out.push('\n');
        }
        for code in &fns {
            self.out.push_str(code);
            self.out.push('\n');
        }
        self.out.push_str("int main(void) {\n");
        for (n, t) in &main_unit.decls {
            self.out.push_str(&format!("    {}\n", decl_of(n, *t)));
        }
        self.out.push_str(&main_unit.body);
        self.out.push_str("    return 0;\n}\n");
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<String, String> {
        let (params, ret) = self
            .sigs
            .get(&f.name)
            .cloned()
            .ok_or_else(|| format!("internal: missing signature for `{}`", f.name))?;
        let saved = std::mem::replace(&mut self.unit, Unit::new());
        self.unit.level = 1;
        self.unit.in_func = true;
        self.unit.frames.push(HashMap::new());
        let mut pinfo: Vec<(String, Ty)> = Vec::new();
        for (n, t) in &params {
            let emitted = self.bind_param(n, *t)?;
            pinfo.push((emitted, *t));
        }
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        let finished = std::mem::replace(&mut self.unit, saved);

        let ps: Vec<String> = pinfo
            .iter()
            .map(|(n, t)| format!("{} {}", c_type_of(*t), n))
            .collect();
        let mut s = String::new();
        s.push_str(&format!(
            "static {} {}({}) {{\n",
            c_type_of(ret),
            f.name,
            ps.join(", ")
        ));
        for (n, t) in &finished.decls {
            s.push_str(&format!("    {}\n", decl_of(n, *t)));
        }
        for line in finished.body.lines() {
            s.push_str("    ");
            s.push_str(line);
            s.push('\n');
        }
        s.push_str("}\n");
        Ok(s)
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "let")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} = {};", emitted, v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "mut")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} = {};", emitted, v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                let tname = match &target.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => {
                        return Err(
                            "complex assignment target: beyond core subset; refusing".into()
                        )
                    }
                };
                let (_, emitted) = self
                    .lookup(&tname)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", tname))?;
                let (v, _) = self.gen_expr(value)?;
                self.unit.bl(&format!("{} = {};", emitted, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                if !self.unit.in_func {
                    return Err("top-level ret: no return slot in main; refusing".into());
                }
                match e {
                    Some(x) => {
                        let (v, _) = self.gen_expr(x)?;
                        self.unit.bl(&format!("return {};", v));
                    }
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                }
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("if ({}) {{", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                if let Some(eb) = else_body {
                    self.unit.bl("} else {");
                    self.unit.level += 1;
                    self.unit.frames.push(HashMap::new());
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.unit.frames.pop();
                    self.unit.level -= 1;
                }
                self.unit.bl("}");
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("while ({}) {{", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                self.unit.bl("}");
                Ok(())
            }
            StmtKind::ExprStmt(e) => {
                // Only `say(...)` calls allowed as bare expression statements.
                match &e.kind {
                    ExprKind::Call { callee, args } => {
                        if let ExprKind::Ident(n) = &callee.kind {
                            if n == "say" {
                                if args.len() != 1 {
                                    return Err(
                                        "say: exactly one argument in core subset; refusing".into()
                                    );
                                }
                                let (v, vt) = self.gen_expr(args[0].expr())?;
                                let helper = match vt {
                                    Ty::Int => "cuni_say_int",
                                    Ty::Str => "cuni_say_str",
                                    Ty::Bool => "cuni_say_bool",
                                };
                                self.unit.bl(&format!("{}({});", helper, v));
                                return Ok(());
                            }
                        }
                        Err("bare call (non-say): beyond core subset; refusing".into())
                    }
                    _ => Err("bare expression: beyond core subset; refusing".into()),
                }
            }
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((n.to_string(), Ty::Int)),
            ExprKind::Bool(b) => Ok((if *b { "1".into() } else { "0".into() }, Ty::Bool)),
            ExprKind::Str(s) => Ok((c_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let (t, emitted) = self
                    .lookup(n)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((emitted, t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self
                    .sigs
                    .get(&name)
                    .map(|(_, r)| *r)
                    .ok_or_else(|| format!("call to unknown function `{}`: refusing", name))?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("cuni_concat({}, {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        return Err("mixed-type `+`: beyond core subset; refusing".into());
                    }
                    BinOp::Sub => {
                        require_ints(lt, rt, "-")?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        require_ints(lt, rt, "*")?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        require_ints(lt, rt, "/")?;
                        // C integer division truncates toward zero (CuNi).
                        Ok((format!("({} / {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        require_ints(lt, rt, "%")?;
                        // C's % truncates; the helper floors.
                        Ok((format!("cuni_mod({}, {})", l, r), Ty::Int))
                    }
                    BinOp::Eq => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) == 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, "==")?;
                        Ok((format!("({} == {})", l, r), Ty::Bool))
                    }
                    BinOp::Ne => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) != 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, "!=")?;
                        Ok((format!("({} != {})", l, r), Ty::Bool))
                    }
                    BinOp::Lt => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) < 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, "<")?;
                        Ok((format!("({} < {})", l, r), Ty::Bool))
                    }
                    BinOp::Gt => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) > 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, ">")?;
                        Ok((format!("({} > {})", l, r), Ty::Bool))
                    }
                    BinOp::Le => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) <= 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, "<=")?;
                        Ok((format!("({} <= {})", l, r), Ty::Bool))
                    }
                    BinOp::Ge => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("(strcmp({}, {}) >= 0)", l, r), Ty::Bool));
                        }
                        require_same(lt, rt, ">=")?;
                        Ok((format!("({} >= {})", l, r), Ty::Bool))
                    }
                    BinOp::And => {
                        require_bools(lt, rt, "and")?;
                        Ok((format!("({} && {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        require_bools(lt, rt, "or")?;
                        Ok((format!("({} || {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(!{})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }
}

fn require_ints(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Int && r == Ty::Int {
        Ok(())
    } else {
        Err(format!("`{}` on non-int: beyond core subset; refusing", op))
    }
}

fn require_bools(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Bool && r == Ty::Bool {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-bool: beyond core subset; refusing",
            op
        ))
    }
}

fn require_same(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == r && l != Ty::Str {
        Ok(())
    } else {
        Err(format!(
            "`{}` on mismatched types: beyond core subset; refusing",
            op
        ))
    }
}
