//! Nim backend — custom core-subset native seat (seat id `nim`).
//!
//! Nim is statically typed with mandatory declarations, so this seat is a
//! custom emitter rather than a [`crate::codegen_core`] spec (same precedent
//! as `pas`/`f90`): it tracks every binding's type (`Int`/`Str`/`Bool`),
//! emits typed `let`/`var` declarations and `proc` signatures, and refuses
//! anything outside the core subset with the same honest `Err`s as the core.
//! Targets Nim 2.x (verified: `nim c -r`).
//!
//! Semantics notes (all verified against the real toolchain):
//! - `div` truncates toward zero (CuNi); `mod` follows the dividend
//!   (C-style), so `cuni_mod` normalizes to Python-floored.
//! - `echo` prints ints/strings natively; booleans route through
//!   `cuni_say_bool` to print `True`/`False`.
//! - `&` concatenates strings; string `<`/`==` compare lexicographically
//!   natively; `and`/`or`/`not` are native keywords.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn nim_ty(t: Ty) -> &'static str {
    match t {
        Ty::Int => "int64",
        Ty::Str => "string",
        Ty::Bool => "bool",
    }
}

/// Quote a string literal for Nim (`"..."`, `\xNN` for control chars).
fn nim_str(s: &str) -> String {
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            '\n' => r.push_str("\\n"),
            '\t' => r.push_str("\\t"),
            '\r' => r.push_str("\\r"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                r.push_str(&format!("\\x{:02X}", c as u32))
            }
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

const HEADER: &str = r#"# Generated by the CuNi core-subset backend. Do not hand-edit.
proc cuni_say_int(x: int64): void = echo x
proc cuni_say_str(x: string): void = echo x
proc cuni_say_bool(x: bool): void = echo (if x: "True" else: "False")
proc cuni_mod(a, b: int64): int64 = ((a mod b) + b) mod b
"#;

struct Emitter {
    out: String,
    level: usize,
    fns: HashSet<String>,
    fn_ret: HashMap<String, Ty>,
    scope: HashMap<String, Ty>,
}

impl Emitter {
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            self.out.push_str(&"  ".repeat(self.level));
            self.out.push_str(text);
        }
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        self.out.push_str(HEADER);
        let mut script_stmts: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    self.fns.insert(f.name.clone());
                }
                Item::Stmt(s) => script_stmts.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        self.out.push('\n');
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
                self.out.push('\n');
            }
        }
        for s in script_stmts {
            self.gen_stmt(s)?;
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        let ret_ty = ty_of(&f.ret_type)?;
        self.fn_ret.insert(f.name.clone(), ret_ty);
        let outer = std::mem::take(&mut self.scope);
        for p in &f.params {
            self.scope.insert(p.name.clone(), ty_of(&p.ty)?);
        }
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, nim_ty(ty_of(&p.ty).unwrap())))
            .collect();
        self.line(&format!(
            "proc {}({}): {} =",
            f.name,
            params.join(", "),
            nim_ty(ret_ty)
        ));
        self.level += 1;
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        self.level -= 1;
        self.scope = outer;
        Ok(())
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                if let Some(t) = ty {
                    let at = ty_of(t)?;
                    if at != vt {
                        return Err(format!(
                            "let {}: annotated type disagrees with value; refusing",
                            name
                        ));
                    }
                }
                self.scope.insert(name.clone(), vt);
                self.line(&format!("let {}: {} = {}", name, nim_ty(vt), v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                if let Some(t) = ty {
                    let at = ty_of(t)?;
                    if at != vt {
                        return Err(format!(
                            "mut {}: annotated type disagrees with value; refusing",
                            name
                        ));
                    }
                }
                self.scope.insert(name.clone(), vt);
                self.line(&format!("var {}: {} = {}", name, nim_ty(vt), v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                if !matches!(target.kind, ExprKind::Ident(_)) {
                    return Err("complex assignment target: beyond core subset; refusing".into());
                }
                let (t, _) = self.gen_expr(target)?;
                let (v, _) = self.gen_expr(value)?;
                self.line(&format!("{} = {}", t, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                let v = match e {
                    Some(x) => self.gen_expr(x)?.0,
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                };
                self.line(&format!("return {}", v));
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.line(&format!("if {}:", c));
                self.level += 1;
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.level -= 1;
                if let Some(eb) = else_body {
                    self.line("else:");
                    self.level += 1;
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.level -= 1;
                }
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.line(&format!("while {}:", c));
                self.level += 1;
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.level -= 1;
                Ok(())
            }
            StmtKind::ExprStmt(e) => match &e.kind {
                ExprKind::Call { callee, args } => {
                    if let ExprKind::Ident(n) = &callee.kind {
                        if n == "say" {
                            if args.len() != 1 {
                                return Err(
                                    "say: exactly one argument in core subset; refusing".into()
                                );
                            }
                            let (v, vt) = self.gen_expr(args[0].expr())?;
                            let f = match vt {
                                Ty::Int => "cuni_say_int",
                                Ty::Str => "cuni_say_str",
                                Ty::Bool => "cuni_say_bool",
                            };
                            self.line(&format!("{}({})", f, v));
                            return Ok(());
                        }
                    }
                    Err("bare call (non-say): beyond core subset; refusing".into())
                }
                _ => Err("bare expression: beyond core subset; refusing".into()),
            },
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((n.to_string(), Ty::Int)),
            ExprKind::Bool(b) => Ok((b.to_string(), Ty::Bool)),
            ExprKind::Str(s) => Ok((nim_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let t = self
                    .scope
                    .get(n)
                    .copied()
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((n.clone(), t))
            }
            ExprKind::InterpStr(_) => Err("interpolated string: beyond core subset; refusing".into()),
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self.fn_ret.get(&name).copied().ok_or_else(|| {
                    format!("call to unknown function `{}`: refusing", name)
                })?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("({} & {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        Err("mixed-type `+`: beyond core subset; refusing".into())
                    }
                    BinOp::Sub => {
                        self.require_ints(lt, rt, "-")?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        self.require_ints(lt, rt, "*")?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        self.require_ints(lt, rt, "/")?;
                        // Nim `div` truncates toward zero (CuNi).
                        Ok((format!("({} div {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        self.require_ints(lt, rt, "%")?;
                        // Nim `mod` follows the dividend; CuNi wants floored.
                        Ok((format!("cuni_mod({}, {})", l, r), Ty::Int))
                    }
                    BinOp::Eq => Ok((format!("({} == {})", l, r), Ty::Bool)),
                    BinOp::Ne => Ok((format!("({} != {})", l, r), Ty::Bool)),
                    BinOp::Lt => Ok((format!("({} < {})", l, r), Ty::Bool)),
                    BinOp::Gt => Ok((format!("({} > {})", l, r), Ty::Bool)),
                    BinOp::Le => Ok((format!("({} <= {})", l, r), Ty::Bool)),
                    BinOp::Ge => Ok((format!("({} >= {})", l, r), Ty::Bool)),
                    BinOp::And => {
                        self.require_bools(lt, rt, "and")?;
                        Ok((format!("({} and {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        self.require_bools(lt, rt, "or")?;
                        Ok((format!("({} or {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(not {})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }

    fn require_ints(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Int && r == Ty::Int {
            Ok(())
        } else {
            Err(format!("`{}` on non-int: beyond core subset; refusing", op))
        }
    }

    fn require_bools(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Bool && r == Ty::Bool {
            Ok(())
        } else {
            Err(format!("`{}` on non-bool: beyond core subset; refusing", op))
        }
    }
}

/// Emit a Nim program for the CuNi core subset, or `Err` (honest refusal)
/// for anything outside it.
pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        level: 0,
        fns: HashSet::new(),
        fn_ret: HashMap::new(),
        scope: HashMap::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}
