//! Common Lisp seat (SBCL) — CuNi core subset via a custom emitter.
//!
//! Why custom instead of [`crate::codegen_core`]: the tempting core mapping
//! (`let` → `(defvar x e)`, assign → `(setf x e)`) is a lie for functions.
//! `defvar` inside a `defun` creates a *global* special variable, so a
//! recursive function whose locals are live across the recursive call
//! computes the wrong answer:
//!
//! ```lisp
//! ;; def f(n: int) -> int { let t = n * 10; if n <= 0 { ret t }
//! ;;                        let r = f(n - 1); ret t + r }
//! ;; with defvar-globals: (f 1) → t is clobbered to 0 by the inner call,
//! ;; returns 0 instead of 10. Silent wrong stdout — refused by this seat.
//! ```
//!
//! So this backend uses real lexical scope: `let`/`mut` → `(let ((x e)) …)`
//! wrapping the rest of the sequence (CL `let` bindings are `setf`-able, so
//! `mut` needs nothing fancier), assignment → `(setf x e)`, `while` → the
//! `loop` macro's `while`, and `ret` → `(return-from cuni-ret e)` inside a
//! `(block cuni-ret …)` per `defun` (early returns propagate honestly through
//! `if`/`loop` nesting; top-level statements run inside `(block cuni-top …)`).
//!
//! ## Arithmetic
//! CL `/` on integers yields a ratio — CuNi `/` truncates toward zero, so it
//! goes through `(truncate a b)`. CL `mod` *is* floored like Python
//! (`(mod -7 2) → 1`), so `%` maps directly. `say(true)` prints `True` via
//! an explicit branch (`t`/`nil` are CL's booleans, not CuNi's spellings).
//!
//! Refuses everything beyond the core subset (see `codegen_core` docs), plus
//! `def` names that would collide with the emitted special forms/helpers.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

const HEADER: &str = ";;;; Generated by the CuNi core-subset backend (Common Lisp seat). Do not hand-edit.\n";

/// `def` names that would collide with emitted special forms / helpers.
const RESERVED: &[&str] = &[
    "format", "loop", "concatenate", "truncate", "block", "defun", "setf", "let", "if", "progn",
    "return-from",
];

#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn lisp_str(s: &str) -> String {
    // Portable CL string syntax: only `\"` and `\\` are escapes. Newlines,
    // tabs, and other control characters pass through literally (legal).
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

struct Emitter {
    out: String,
    level: usize,
    fns: HashSet<String>,
    fn_ret: HashMap<String, Ty>,
    /// name -> Ty (mutability needs no tracking: `let` bindings are setf-able
    /// and every reference is the bare name).
    scope: HashMap<String, Ty>,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        level: 0,
        fns: HashSet::new(),
        fn_ret: HashMap::new(),
        scope: HashMap::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

/// Collect `&Stmt` refs out of a `&[Stmt]` for [`Emitter::gen_seq`].
fn r(stmts: &[Stmt]) -> Vec<&Stmt> {
    stmts.iter().collect()
}

impl Emitter {
    /// Prefix variable names to avoid clashing with CL constants (T, NIL).
    fn vname(&self, n: &str) -> String {
        format!("cu-{}", n)
    }
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            self.out.push_str(&"  ".repeat(self.level));
            self.out.push_str(text);
        }
        self.out.push('\n');
    }

    fn check_ann(&self, ann: &Option<Type>, vt: Ty, name: &str, kw: &str) -> Result<(), String> {
        if let Some(t) = ann {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!("{kw} {name}: annotated type disagrees with value; refusing"));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if RESERVED.contains(&f.name.as_str()) {
            return Err(format!("def {}: name reserved by the Lisp seat; refusing", f.name));
        }
        if f.fallible {
            return Err(format!("def {}: fallible functions beyond core subset; refusing", f.name));
        }
        if !f.generics.is_empty() {
            return Err(format!("def {}: generics beyond core subset; refusing", f.name));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn require_ints(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Int && r == Ty::Int {
            Ok(())
        } else {
            Err(format!("`{op}` on non-int: beyond core subset; refusing"))
        }
    }

    fn require_bools(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Bool && r == Ty::Bool {
            Ok(())
        } else {
            Err(format!("`{op}` on non-bool: beyond core subset; refusing"))
        }
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        self.out.push_str(HEADER);
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    self.fns.insert(f.name.clone());
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => return Err(format!("use {}: beyond core subset; refusing", u.name)),
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        self.out.push('\n');
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
            }
        }
        // Top-level statements run directly as SBCL script forms.
        self.line("(block cuni-top");
        self.level += 1;
        self.gen_seq(&script, "cuni-top")?;
        self.level -= 1;
        self.line(")");
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        let rt = ty_of(&f.ret_type)?;
        self.fn_ret.insert(f.name.clone(), rt);
        let outer = std::mem::take(&mut self.scope);
        for p in &f.params {
            let pt = ty_of(&p.ty)?;
            self.scope.insert(p.name.clone(), pt);
        }
        let params = f.params.iter().map(|p| self.vname(&p.name)).collect::<Vec<_>>().join(" ");
        self.line(&format!("(defun {name} ({params})", name = f.name, params = params));
        self.level += 1;
        self.line("(block cuni-ret");
        self.level += 1;
        self.gen_seq(&r(&f.body), "cuni-ret")?;
        self.level -= 1;
        self.line(")");
        self.level -= 1;
        self.line(")");
        self.out.push('\n');
        self.scope = outer;
        Ok(())
    }

    /// Compile a statement list. `let`/`mut` wrap the *rest* of the sequence
    /// in `(let ((x e)) …)` — each one opens a paren that is closed when the
    /// sequence ends (or when a `ret` truncates it); everything else emits as
    /// a sibling form. `block` names the enclosing `(block …)` that `ret`
    /// returns from.
    fn gen_seq(&mut self, stmts: &[&Stmt], block: &str) -> Result<(), String> {
        // How many `(let …)` forms this call opened and must close.
        let mut opened = 0usize;
        for s in stmts {
            match &s.kind {
                StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                    let (v, vt) = self.gen_expr(value)?;
                    // `let` vs `mut` needs no distinction: CL `let` bindings
                    // are mutable via `setf`, and reads are the bare name.
                    let kw = if matches!(&s.kind, StmtKind::Mut { .. }) { "mut" } else { "let" };
                    self.check_ann(ty, vt, name, kw)?;
                    self.scope.insert(name.clone(), vt);
                    self.line(&format!("(let (({name} {v}))", name = self.vname(name), v = v));
                    self.level += 1;
                    opened += 1;
                }
                StmtKind::Assign { target, value } => {
                    let tname = match &target.kind {
                        ExprKind::Ident(n) => n.clone(),
                        _ => return Err("complex assignment target: beyond core subset; refusing".into()),
                    };
                    if !self.scope.contains_key(&tname) {
                        return Err(format!("assign to unknown `{tname}`: refusing", tname = tname));
                    }
                    let (v, _) = self.gen_expr(value)?;
                    self.line(&format!("(setf {tname} {v})", tname = self.vname(&tname), v = v));
                }
                StmtKind::Ret(e) => {
                    let x = e
                        .as_ref()
                        .ok_or_else(|| "bare ret: beyond core subset; refusing".to_string())?;
                    let (v, _) = self.gen_expr(x)?;
                    self.line(&format!("(return-from {block} {v})", block = block, v = v));
                    for _ in 0..opened {
                        self.level -= 1;
                        self.line(")");
                    }
                    return Ok(());
                }
                StmtKind::Fail(_) => return Err("fail: beyond core subset; refusing".into()),
                StmtKind::If { cond, then_body, else_body } => {
                    let (c, ct) = self.gen_expr(cond)?;
                    if ct != Ty::Bool {
                        return Err("if condition must be bool; refusing".into());
                    }
                    self.line(&format!("(if {c}", c = c));
                    self.level += 1;
                    self.line("(progn");
                    self.level += 1;
                    self.gen_seq(&r(then_body), block)?;
                    self.level -= 1;
                    self.line(")");
                    self.line("(progn");
                    self.level += 1;
                    self.gen_seq(&r(else_body.as_deref().unwrap_or(&[])), block)?;
                    self.level -= 1;
                    self.line(")");
                    self.level -= 1;
                    self.line(")");
                }
                StmtKind::For { .. } => return Err("for: beyond core subset; refusing".into()),
                StmtKind::Whl { cond, body } => {
                    let (c, ct) = self.gen_expr(cond)?;
                    if ct != Ty::Bool {
                        return Err("while condition must be bool; refusing".into());
                    }
                    self.line(&format!("(loop while {c} do", c = c));
                    self.level += 1;
                    if body.is_empty() {
                        self.line("nil");
                    } else {
                        self.gen_seq(&r(body), block)?;
                    }
                    self.level -= 1;
                    self.line(")");
                }
                StmtKind::ExprStmt(e) => match &e.kind {
                    ExprKind::Call { callee, args } => match &callee.kind {
                        ExprKind::Ident(n) if n == "say" => {
                            if args.len() != 1 {
                                return Err("say: exactly one argument in core subset; refusing".into());
                            }
                            let (v, vt) = self.gen_expr(args[0].expr())?;
                            // `~a` prints raw (no quoting); bool needs the
                            // explicit True/False branch (`t`/`nil` are CL's
                            // spellings, not CuNi's).
                            let form = match vt {
                                Ty::Bool => format!(
                                    "(format t \"~a~%\" (if {v} \"True\" \"False\"))",
                                    v = v
                                ),
                                _ => format!("(format t \"~a~%\" {v})", v = v),
                            };
                            self.line(&form);
                        }
                        _ => return Err("bare call (non-say): beyond core subset; refusing".into()),
                    },
                    _ => return Err("bare expression: beyond core subset; refusing".into()),
                },
                StmtKind::Todo => return Err("...: beyond core subset; refusing".into()),
            }
        }
        for _ in 0..opened {
            self.level -= 1;
            self.line(")");
        }
        Ok(())
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((format!("{n}", n = n), Ty::Int)),
            ExprKind::Bool(b) => Ok((if *b { "t".into() } else { "nil".into() }, Ty::Bool)),
            ExprKind::Str(s) => Ok((lisp_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let t = self.scope.get(n).copied().ok_or_else(|| {
                    format!("unknown variable `{n}`: refusing", n = n)
                })?;
                Ok((self.vname(n), t))
            }
            ExprKind::InterpStr(_) => Err("interpolated string: beyond core subset; refusing".into()),
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self.fn_ret.get(&name).copied().ok_or_else(|| {
                    format!("call to unknown function `{name}`: refusing", name = name)
                })?;
                if args.iter().any(|a| a.is_named()) {
                    return Err("named arguments: beyond core subset; refusing".into());
                }
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                let call = if as_.is_empty() {
                    format!("({name})", name = name)
                } else {
                    format!("({name} {args})", name = name, args = as_.join(" "))
                };
                Ok((call, ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                let expr = match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("(concatenate 'string {l} {r})", l = l, r = r)
                        } else if lt == Ty::Int && rt == Ty::Int {
                            format!("(+ {l} {r})", l = l, r = r)
                        } else {
                            return Err("mixed-type `+`: beyond core subset; refusing".into());
                        }
                    }
                    BinOp::Sub => {
                        self.require_ints(lt, rt, "-")?;
                        format!("(- {l} {r})", l = l, r = r)
                    }
                    BinOp::Mul => {
                        self.require_ints(lt, rt, "*")?;
                        format!("(* {l} {r})", l = l, r = r)
                    }
                    // CL `/` on integers yields a ratio; `truncate` truncates
                    // toward zero — CuNi `/` semantics.
                    BinOp::Div => {
                        self.require_ints(lt, rt, "/")?;
                        format!("(truncate {l} {r})", l = l, r = r)
                    }
                    // CL `mod` is floored, like Python — CuNi `%` semantics.
                    BinOp::Mod => {
                        self.require_ints(lt, rt, "%")?;
                        format!("(mod {l} {r})", l = l, r = r)
                    }
                    // `equal` covers int/str/bool structurally.
                    BinOp::Eq => format!("(equal {l} {r})", l = l, r = r),
                    BinOp::Ne => format!("(not (equal {l} {r}))", l = l, r = r),
                    BinOp::Lt => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("(string< {l} {r})", l = l, r = r)
                        } else {
                            format!("(< {l} {r})", l = l, r = r)
                        }
                    }
                    BinOp::Gt => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("(string> {l} {r})", l = l, r = r)
                        } else {
                            format!("(> {l} {r})", l = l, r = r)
                        }
                    }
                    BinOp::Le => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("(string<= {l} {r})", l = l, r = r)
                        } else {
                            format!("(<= {l} {r})", l = l, r = r)
                        }
                    }
                    BinOp::Ge => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("(string>= {l} {r})", l = l, r = r)
                        } else {
                            format!("(>= {l} {r})", l = l, r = r)
                        }
                    }
                    BinOp::And => {
                        self.require_bools(lt, rt, "and")?;
                        format!("(and {l} {r})", l = l, r = r)
                    }
                    BinOp::Or => {
                        self.require_bools(lt, rt, "or")?;
                        format!("(or {l} {r})", l = l, r = r)
                    }
                };
                let t = match op {
                    BinOp::Add if lt == Ty::Str => Ty::Str,
                    BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div | BinOp::Mod => Ty::Int,
                    _ => Ty::Bool,
                };
                Ok((expr, t))
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(not {v})", v = v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(- {v})", v = v), Ty::Int))
                    }
                }
            }
        }
    }
}
