use crate::ast::*;
use std::collections::HashMap;

/// A toy, best-effort Python emitter for the CuNi AST. It exists to prove the
/// pipeline (parse -> emit) works end to end for the constructs the spec has
/// fully defined; it is NOT the real "compile-or-refuse" compiler described in
/// SPEC.md — it never rejects a program, it just does its best and leaves a
/// comment where the mapping is genuinely undefined (see NOTES below).
///
/// NOTES / known gaps surfaced by writing this:
/// - `fail expr` (signaling failure from a fallible function body) emits
///   `raise CuNiError(expr)` — `CuNiError` is a single exception class emitted
///   once per program (see gen_program). `??`'s existing `except Exception`
///   handling already catches it, same as any other exception. A still-`...`
///   stub body emits `raise NotImplementedError()` instead, since "not
///   implemented yet" and "this call failed" are different concepts even
///   though Python happens to model both as exceptions.
/// - `iface` methods are modeled as Python ABC abstractmethods (with an
///   implicit `self`), but the spec's own example (`def area(c: Circle) ->
///   float`) implements `Shape.area` as a free function taking the receiver
///   explicitly, not as a method. Nothing in the spec ties the two together,
///   so `typ Circle is Shape` does not actually satisfy Python's ABC contract
///   here. This is a genuine spec gap, not a codegen shortcut.
/// - `??` (Unwrap) is only handled when it's the direct value of a `let`/`mut`
///   statement, matching every example so far. In any other expression
///   position it emits an `# UNSUPPORTED` marker.
/// - `for k, v in m` vs `for i, x in xs` (map vs list iteration) is decided by
///   a lightweight scope-tracked guess (param/annotation type, or literal
///   shape), not real type inference. Good enough for the current examples;
///   not a substitute for the type checker this still needs.
/// - `link` (SPEC.md §19) additionally emits an HTTP handler (stdlib
///   `http.server`-shaped, taking a `BaseHTTPRequestHandler` instance) and an
///   always-fallible `<name>_remote` client stub (stdlib `urllib.request`) —
///   zero third-party dependencies, matching the ratified interop proposal.
///   See `gen_link_handler`/`gen_link_remote` and `py_wire_encode`/`decode`.
pub fn generate(program: &Program) -> String {
    let mut cg = Codegen::new(program);
    cg.gen_program(program);
    cg.out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    List,
    Map,
    Other,
}

struct FnInfo {
    fallible: bool,
}

struct Codegen {
    fn_info: HashMap<String, FnInfo>,
    has_link: bool,
    out: String,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_info = HashMap::new();
        for item in &program.items {
            if let Item::Def(f) = item {
                fn_info.insert(f.name.clone(), FnInfo { fallible: f.fallible });
            }
        }
        for item in &program.items {
            if let Item::Def(f) = item {
                if f.is_link {
                    // The remote client stub is always fallible (a network
                    // call can always fail even if the local body can't) —
                    // registering it here lets the existing `??`/Unwrap
                    // codegen path (gen_binding) handle it for free, exactly
                    // like any other fallible function call.
                    fn_info.insert(format!("{}_remote", f.name), FnInfo { fallible: true });
                }
            }
        }
        let has_link = program.items.iter().any(|i| matches!(i, Item::Def(f) if f.is_link));
        Codegen { fn_info, has_link, out: String::new() }
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) {
        self.line(0, "# Generated by the CuNi toy Python backend. Do not hand-edit.");
        self.line(0, "from __future__ import annotations  # lets generic params like T appear in annotations unevaluated");
        self.line(0, "from typing import List, Dict, Optional");
        self.line(0, "from dataclasses import dataclass");
        self.line(0, "from abc import ABC, abstractmethod");
        self.line(0, "from enum import Enum, auto");
        if self.has_link {
            self.line(0, "import json");
            self.line(0, "import urllib.request");
            self.line(0, "import urllib.error");
        }
        self.out.push('\n');
        self.line(0, "def say(x):");
        self.line(1, "print(x)");
        self.out.push('\n');
        self.line(0, "class CuNiError(Exception):");
        self.line(1, "\"\"\"Raised by `fail` — CuNi's explicit failure-signaling statement.\"\"\"");
        self.out.push('\n');

        // Top-level `ret` (e.g. inside a `??` handler on a top-level `let`)
        // has no enclosing function in CuNi's source, but Python forbids
        // `return` outside one — module-level code isn't a function. So
        // every top-level statement is collected and wrapped in an implicit
        // `main()`, called at the bottom. This is a real gap the spec hasn't
        // addressed yet (see SPEC.md open items): what a top-level `ret`
        // even means is undefined; "the top-level script is one implicit
        // function" is this backend's working assumption, not a ratified
        // spec decision.
        let mut script_stmts: Vec<&Stmt> = Vec::new();
        let mut top_scope: HashMap<String, VarKind> = HashMap::new();
        for item in &program.items {
            if let Item::Stmt(s) = item {
                script_stmts.push(s);
            } else {
                self.gen_item(item, &mut top_scope);
                self.out.push('\n');
            }
        }

        self.line(0, "def main():");
        if script_stmts.is_empty() {
            self.line(1, "pass");
        } else {
            for s in script_stmts {
                self.gen_stmt(1, s, &mut top_scope);
            }
        }
        self.out.push('\n');
        self.line(0, "if __name__ == \"__main__\":");
        self.line(1, "main()");
    }

    fn gen_item(&mut self, item: &Item, scope: &mut HashMap<String, VarKind>) {
        match item {
            Item::Use(name) => {
                self.line(0, &format!("# use {} — portable CuNi module, not resolved by this toy backend", name));
            }
            Item::Ext(ext) => {
                self.line(0, &format!("def {}({}):", ext.name, params_sig(&ext.params)));
                let py_line = ext
                    .targets
                    .iter()
                    .find(|(t, _)| t == "py")
                    .map(|(_, raw)| raw.clone())
                    .unwrap_or_else(|| "raise NotImplementedError('no py: mapping given')".to_string());
                self.line(1, &format!("return {}", py_line));
            }
            Item::Typ(t) => {
                // Do NOT subclass the iface ABC: CuNi realizes iface methods
                // as free functions (`def area(c: Circle)`), not methods on
                // the struct. Inheriting from an ABC with abstract methods
                // would make `Circle(...)` raise TypeError at runtime — the
                // same "is is documentary at the target, checked by CuNi"
                // posture as Go/JS backends. CuNi's typeck enforces `is`.
                self.line(0, "@dataclass");
                if let Some(iface) = &t.implements {
                    self.line(0, &format!("class {}:  # implements {} (checked by CuNi typeck, not via ABC inheritance)", t.name, iface));
                } else {
                    self.line(0, &format!("class {}:", t.name));
                }
                if t.fields.is_empty() {
                    self.line(1, "pass");
                } else {
                    for f in &t.fields {
                        self.line(1, &format!("{}: {}", f.name, py_type(&f.ty)));
                    }
                }
            }
            Item::Iface(i) => {
                self.line(0, &format!("class {}(ABC):", i.name));
                if i.methods.is_empty() {
                    self.line(1, "pass");
                } else {
                    for m in &i.methods {
                        self.line(1, "@abstractmethod");
                        self.line(1, &format!("def {}({}) -> {}:", m.name, self_params_sig(&m.params), py_type(&m.ret_type)));
                        self.line(2, "...");
                    }
                }
            }
            Item::Enum(e) => {
                self.line(0, &format!("class {}(Enum):", e.name));
                if e.variants.is_empty() {
                    self.line(1, "pass");
                } else {
                    for v in &e.variants {
                        self.line(1, &format!("{} = auto()", v));
                    }
                }
            }
            Item::Def(f) => {
                let generics_note = if f.generics.is_empty() {
                    String::new()
                } else {
                    format!("  # generic over {}", f.generics.join(", "))
                };
                self.line(0, &format!("def {}({}) -> {}:{}", f.name, params_sig(&f.params), py_type(&f.ret_type), generics_note));
                let mut fn_scope: HashMap<String, VarKind> = HashMap::new();
                for p in &f.params {
                    fn_scope.insert(p.name.clone(), kind_of_type(&p.ty));
                }
                if f.body.is_empty() {
                    self.line(1, "pass");
                } else {
                    for s in &f.body {
                        self.gen_stmt(1, s, &mut fn_scope);
                    }
                }
                if f.is_link {
                    self.out.push('\n');
                    self.gen_link_handler(f);
                    self.out.push('\n');
                    self.gen_link_remote(f);
                }
            }
            Item::Stmt(s) => self.gen_stmt(0, s, scope),
        }
    }

    /// `link Name(...) -> T [?] do ... end` additionally emits an HTTP
    /// handler (mount it yourself, per the ratified "codegen-only, no
    /// bundled runtime" decision — see INTEROP_PROPOSAL.md item 6) that
    /// decodes a JSON request, calls the local function above, and encodes
    /// the JSON response — or a `{"error": ...}` response on any exception,
    /// which naturally also covers `fail`/stub bodies without any extra
    /// casework, since Python's `except Exception` already catches those.
    fn gen_link_handler(&mut self, f: &FnDecl) {
        self.line(0, &format!("def {}_handler(handler):", f.name));
        self.line(1, &format!("\"\"\"HTTP handler for `link {}` \u{2014} mount at path \"/{}\" (see SPEC.md \u{a7}19).\"\"\"", f.name, f.name));
        self.line(1, "length = int(handler.headers.get(\"Content-Length\", 0))");
        self.line(1, "body = handler.rfile.read(length)");
        self.line(1, "try:");
        self.line(2, "req = json.loads(body)");
        let args = f.params.iter().map(|p| py_wire_decode(&format!("req[{:?}]", p.name), &p.ty)).collect::<Vec<_>>().join(", ");
        self.line(2, &format!("result = {}({})", f.name, args));
        self.line(2, &format!("payload = json.dumps({{\"result\": {}}}).encode()", py_wire_encode("result", &f.ret_type)));
        self.line(2, "handler.send_response(200)");
        self.line(2, "handler.send_header(\"Content-Type\", \"application/json\")");
        self.line(2, "handler.end_headers()");
        self.line(2, "handler.wfile.write(payload)");
        self.line(1, "except Exception as e:");
        self.line(2, "payload = json.dumps({\"error\": str(e)}).encode()");
        self.line(2, "handler.send_response(400)");
        self.line(2, "handler.send_header(\"Content-Type\", \"application/json\")");
        self.line(2, "handler.end_headers()");
        self.line(2, "handler.wfile.write(payload)");
    }

    /// The client side of the same `link`: always fallible regardless of
    /// whether the local function is (a network call can fail even when the
    /// local logic can't), reusing `CuNiError`/`??` rather than inventing a
    /// second error channel for network failures specifically.
    fn gen_link_remote(&mut self, f: &FnDecl) {
        let params_sig = f.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
        self.line(0, &format!("def {}_remote(base_url, {}):", f.name, params_sig));
        let fields = f.params.iter().map(|p| format!("{:?}: {}", p.name, py_wire_encode(&p.name, &p.ty))).collect::<Vec<_>>().join(", ");
        self.line(1, &format!("req_body = json.dumps({{{}}}).encode()", fields));
        self.line(
            1,
            &format!(
                "req = urllib.request.Request(base_url + \"/{}\", data=req_body, headers={{\"Content-Type\": \"application/json\"}}, method=\"POST\")",
                f.name
            ),
        );
        self.line(1, "try:");
        self.line(2, "with urllib.request.urlopen(req) as resp:");
        self.line(3, "data = json.loads(resp.read())");
        self.line(3, &format!("return {}", py_wire_decode("data[\"result\"]", &f.ret_type)));
        self.line(1, "except urllib.error.HTTPError as e:");
        self.line(2, "data = json.loads(e.read())");
        self.line(2, "raise CuNiError(data.get(\"error\", str(e)))");
        self.line(1, "except Exception as e:");
        self.line(2, "raise CuNiError(str(e))");
    }

    fn gen_stmt(&mut self, indent: usize, stmt: &Stmt, scope: &mut HashMap<String, VarKind>) {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                let kind = ty.as_ref().map(kind_of_type).or_else(|| kind_of_literal(value)).unwrap_or(VarKind::Other);
                scope.insert(name.clone(), kind);
                self.gen_binding(indent, name, value, scope);
            }
            StmtKind::Assign { target, value } => {
                self.line(indent, &format!("{} = {}", self.gen_expr(target, scope), self.gen_expr(value, scope)));
            }
            StmtKind::Ret(Some(e)) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("return {}", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("raise CuNiError({})", text));
            }
            StmtKind::If { cond, then_body, else_body } => {
                self.line(indent, &format!("if {}:", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, then_body, scope);
                if let Some(else_body) = else_body {
                    self.line(indent, "else:");
                    self.gen_block(indent + 1, else_body, scope);
                }
            }
            StmtKind::For { binding: (a, b), iter, body } => {
                let iter_kind = if let ExprKind::Ident(name) = &iter.kind { scope.get(name).copied() } else { None };
                let header = match b {
                    Some(b) if iter_kind == Some(VarKind::Map) => {
                        format!("for {}, {} in {}.items():", a, b, self.gen_expr(iter, scope))
                    }
                    Some(b) => format!("for {}, {} in enumerate({}):", a, b, self.gen_expr(iter, scope)),
                    None => format!("for {} in {}:", a, self.gen_expr(iter, scope)),
                };
                self.line(indent, &header);
                self.gen_block(indent + 1, body, scope);
            }
            StmtKind::Whl { cond, body } => {
                self.line(indent, &format!("while {}:", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, body, scope);
            }
            StmtKind::ExprStmt(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &text);
            }
            StmtKind::Todo => {
                self.line(indent, "raise NotImplementedError(\"...\")  # CuNi stub body (`...`) — not yet written");
            }
        }
    }

    fn gen_block(&mut self, indent: usize, stmts: &[Stmt], scope: &mut HashMap<String, VarKind>) {
        if stmts.is_empty() {
            self.line(indent, "pass");
        } else {
            for s in stmts {
                self.gen_stmt(indent, s, scope);
            }
        }
    }

    /// `let name = expr ?? do handler end` is the only Unwrap position this
    /// toy backend supports (see module docs). `name` is only bound on the
    /// success path — the handler is expected to diverge (`ret`), matching
    /// every example program written against the spec so far.
    fn gen_binding(&mut self, indent: usize, name: &str, value: &Expr, scope: &mut HashMap<String, VarKind>) {
        if let ExprKind::Unwrap { expr, handler } = &value.kind {
            let is_fallible_call = matches!(&expr.kind, ExprKind::Call { callee, .. } if matches!(&callee.kind, ExprKind::Ident(fname) if self.fn_info.get(fname).map_or(false, |i| i.fallible))
            );
            let inner = self.gen_expr(expr, scope);
            if is_fallible_call {
                self.line(indent, "try:");
                self.line(indent + 1, &format!("_unwrapped = {}", inner));
                self.line(indent, "except Exception:");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else:");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
            } else {
                self.line(indent, &format!("_unwrapped = {}", inner));
                self.line(indent, "if _unwrapped is None:");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else:");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
            }
        } else {
            self.line(indent, &format!("{} = {}", name, self.gen_expr(value, scope)));
        }
    }

    fn gen_expr(&self, expr: &Expr, scope: &HashMap<String, VarKind>) -> String {
        match &expr.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Float(f) => f.to_string(),
            ExprKind::Bool(b) => if *b { "True".to_string() } else { "False".to_string() },
            ExprKind::Str(s) => format!("{:?}", s),
            ExprKind::InterpStr(parts) => {
                let mut s = String::from("f\"");
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => {
                            let escaped = t.replace('\\', "\\\\").replace('"', "\\\"").replace('{', "{{").replace('}', "}}");
                            s.push_str(&escaped);
                        }
                        StrPartExpr::Expr(e) => {
                            s.push('{');
                            s.push_str(&self.gen_expr(e, scope));
                            s.push('}');
                        }
                    }
                }
                s.push('"');
                s
            }
            ExprKind::NoneLit => "None".to_string(),
            ExprKind::Ident(name) => name.clone(),
            ExprKind::List(items) => format!("[{}]", items.iter().map(|e| self.gen_expr(e, scope)).collect::<Vec<_>>().join(", ")),
            ExprKind::Map(pairs) => format!(
                "{{{}}}",
                pairs.iter().map(|(k, v)| format!("{}: {}", self.gen_expr(k, scope), self.gen_expr(v, scope))).collect::<Vec<_>>().join(", ")
            ),
            ExprKind::Call { callee, args } => {
                if let ExprKind::Field { base, name } = &callee.kind {
                    if name == "push" {
                        return format!("{}.append({})", self.gen_expr(base, scope), args.iter().map(|a| self.gen_expr(a.expr(), scope)).collect::<Vec<_>>().join(", "));
                    }
                    if name == "len" {
                        return format!("len({})", self.gen_expr(base, scope));
                    }
                }
                // Named typ constructor -> kwargs: Circle(r=2.0)
                if args.iter().all(|a| a.is_named()) && !args.is_empty() {
                    let parts: Vec<String> = args
                        .iter()
                        .filter_map(|a| match a {
                            CallArg::Named { name, value, .. } => {
                                Some(format!("{}={}", name, self.gen_expr(value, scope)))
                            }
                            _ => None,
                        })
                        .collect();
                    return format!("{}({})", self.gen_expr(callee, scope), parts.join(", "));
                }
                format!("{}({})", self.gen_expr(callee, scope), args.iter().map(|a| self.gen_expr(a.expr(), scope)).collect::<Vec<_>>().join(", "))
            }
            ExprKind::Index { base, index } => format!("{}[{}]", self.gen_expr(base, scope), self.gen_expr(index, scope)),
            ExprKind::Field { base, name } => format!("{}.{}", self.gen_expr(base, scope), name),
            ExprKind::Binary { op, lhs, rhs } => format!("({} {} {})", self.gen_expr(lhs, scope), py_binop(*op), self.gen_expr(rhs, scope)),
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("(not {})", self.gen_expr(expr, scope)),
                UnOp::Neg => format!("(-{})", self.gen_expr(expr, scope)),
            },
            ExprKind::Unwrap { .. } => "None  # UNSUPPORTED: ?? outside a let/mut binding, see codegen_py.rs docs".to_string(),
        }
    }
}

fn params_sig(params: &[Param]) -> String {
    params.iter().map(|p| format!("{}: {}", p.name, py_type(&p.ty))).collect::<Vec<_>>().join(", ")
}

fn self_params_sig(params: &[Param]) -> String {
    let mut parts = vec!["self".to_string()];
    parts.extend(params.iter().map(|p| format!("{}: {}", p.name, py_type(&p.ty))));
    parts.join(", ")
}

fn py_type(ty: &Type) -> String {
    match ty {
        Type::Named(name) => match name.as_str() {
            "int" => "int".to_string(),
            "float" => "float".to_string(),
            "str" => "str".to_string(),
            "bool" => "bool".to_string(),
            other => other.to_string(),
        },
        Type::Generic(name, args) => match name.as_str() {
            "list" => format!("List[{}]", py_type(&args[0])),
            "map" => format!("Dict[{}, {}]", py_type(&args[0]), py_type(&args[1])),
            "opt" => format!("Optional[{}]", py_type(&args[0])),
            other => format!("{}[{}]", other, args.iter().map(py_type).collect::<Vec<_>>().join(", ")),
        },
    }
}

fn kind_of_type(ty: &Type) -> VarKind {
    match ty {
        Type::Generic(name, _) if name == "list" => VarKind::List,
        Type::Generic(name, _) if name == "map" => VarKind::Map,
        _ => VarKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<VarKind> {
    match &e.kind {
        ExprKind::List(_) => Some(VarKind::List),
        ExprKind::Map(_) => Some(VarKind::Map),
        _ => None,
    }
}

/// `link`'s wire codec (SPEC.md §19): an `int` field is encoded as a JSON
/// *string*, not a JSON number — JSON has no arbitrary-precision integer
/// type, and JS's own `Number` silently loses precision above 2^53, so a
/// decimal-string encoding is the one representation all three v1 targets
/// can round-trip losslessly (checks.rs's `find_bad_link_type` restricts
/// `link` to scalar types specifically so this codec never has to recurse
/// into a `list`/`map`/`typ` shape). float/str/bool pass through as-is —
/// JSON already has a native, lossless representation for each of those on
/// every target this toy backend supports.
fn py_wire_encode(expr: &str, ty: &Type) -> String {
    match ty {
        Type::Named(name) if name == "int" => format!("str({})", expr),
        _ => expr.to_string(),
    }
}

fn py_wire_decode(expr: &str, ty: &Type) -> String {
    match ty {
        Type::Named(name) if name == "int" => format!("int({})", expr),
        _ => expr.to_string(),
    }
}

fn py_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
    }
}
