//! Family-flavored printers (syntax sketches). Exactness does **not** use
//! these — `emit::generate_exact` is the §2 path and runs every catalog id.
#![allow(dead_code)]

use crate::ast::*;
use crate::langs::{Family, Lang};

pub fn generate(program: &Program, lang: &Lang) -> String {
    let mut g = Gen {
        lang: *lang,
        out: String::new(),
    };
    g.header();
    let mut script: Vec<&Stmt> = Vec::new();
    for item in &program.items {
        match item {
            Item::Use(name) => g.comment(&format!("use {name}")),
            Item::Ext(e) => g.ext(e),
            Item::Typ(t) => g.typ(t),
            Item::Iface(i) => g.comment(&format!("iface {}", i.name)),
            Item::Enum(e) => g.enom(e),
            Item::Def(f) => g.func(f),
            Item::Stmt(s) => script.push(s),
        }
    }
    if !script.is_empty() {
        g.main_open();
        for s in script {
            g.stmt(s, 1);
        }
        g.main_close();
    }
    g.out
}

struct Gen {
    lang: Lang,
    out: String,
}

impl Gen {
    fn line(&mut self, indent: usize, s: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn comment(&mut self, s: &str) {
        let c = match self.lang.family {
            Family::Python | Family::Ruby | Family::Perl | Family::R | Family::Julia
            | Family::Elixir | Family::Bash | Family::Powershell | Family::Nim | Family::Crystal
            | Family::Awk | Family::Tcl | Family::Sql => format!("# {s}"),
            Family::Lua | Family::Ada | Family::Haskell => format!("-- {s}"),
            Family::Lisp | Family::Clojure | Family::Erlang | Family::Prolog => format!("; {s}"),
            Family::Fortran => format!("! {s}"),
            Family::Cobol => format!("      * {s}"),
            Family::Matlab => format!("% {s}"),
            Family::Vb => format!("' {s}"),
            _ => format!("// {s}"),
        };
        self.line(0, &c);
    }

    fn header(&mut self) {
        self.comment(&format!(
            "Generated by CuNi → {} ({}). Do not hand-edit.",
            self.lang.name, self.lang.id
        ));
        match self.lang.family {
            Family::C => {
                self.line(0, "#include <stdio.h>");
                self.line(0, "#include <stdlib.h>");
            }
            Family::Cpp => self.line(0, "#include <iostream>"),
            Family::Java => self.line(0, "public class Main {"),
            Family::CSharp => {
                self.line(0, "using System;");
                self.line(0, "class Program {");
            }
            Family::Go => {
                self.line(0, "package main");
                self.line(0, "import \"fmt\"");
            }
            Family::Php => self.line(0, "<?php"),
            Family::Rust => self.line(0, "fn main_shim() {}"),
            Family::Kotlin => self.line(0, "fun main() {"),
            Family::Swift => {}
            Family::Dart => {
                self.line(0, "void main() {");
            }
            Family::Groovy => {}
            Family::Fortran => self.line(0, "program cuni"),
            Family::Pascal => {
                self.line(0, "program Cuni;");
                self.line(0, "begin");
            }
            Family::Cobol => {
                self.line(0, "       IDENTIFICATION DIVISION.");
                self.line(0, "       PROGRAM-ID. CUNI.");
            }
            _ => {}
        }
        self.out.push('\n');
    }

    fn main_open(&mut self) {
        match self.lang.family {
            Family::C => self.line(0, "int main(void) {"),
            Family::Cpp => self.line(0, "int main() {"),
            Family::Go => self.line(0, "func main() {"),
            Family::Rust => self.line(0, "fn main() {"),
            Family::Java => self.line(1, "public static void main(String[] args) {"),
            Family::CSharp => self.line(1, "static void Main() {"),
            Family::Zig => self.line(0, "pub fn main() void {"),
            Family::Nim => self.line(0, "when isMainModule:"),
            Family::D => self.line(0, "void main() {"),
            Family::Vlang => self.line(0, "fn main() {"),
            Family::Ada => {
                self.line(0, "procedure Main is");
                self.line(0, "begin");
            }
            Family::Haskell => self.line(0, "main = do"),
            Family::Ocaml => self.line(0, "let () ="),
            Family::Fsharp => self.line(0, "[<EntryPoint>]"),
            Family::Erlang => self.line(0, "main(_) ->"),
            Family::Elixir => self.line(0, "defmodule Cuni do"),
            Family::Lisp => self.line(0, "(defun main ()"),
            Family::Clojure => self.line(0, "(defn -main [& _]"),
            Family::Solidity => {
                self.line(0, "contract Cuni {");
                self.line(1, "function run() public pure {");
            }
            Family::Objc => self.line(0, "int main(int argc, const char * argv[]) {"),
            Family::Vb => self.line(0, "Module Cuni"),
            Family::Crystal => self.line(0, "# main"),
            Family::Bash => self.line(0, "#!/usr/bin/env bash"),
            Family::Awk => self.line(0, "BEGIN {"),
            Family::Sql => self.line(0, "-- script"),
            Family::Assembly => self.line(0, ".text"),
            Family::Kotlin | Family::Dart | Family::Pascal | Family::Fortran | Family::Cobol => {}
            _ => {}
        }
    }

    fn main_close(&mut self) {
        match self.lang.family {
            Family::C | Family::Cpp | Family::Objc => {
                self.line(1, "return 0;");
                self.line(0, "}");
            }
            Family::Go | Family::Rust | Family::Zig | Family::D | Family::Vlang => self.line(0, "}"),
            Family::Java => {
                self.line(1, "}");
                self.line(0, "}");
            }
            Family::CSharp => {
                self.line(1, "}");
                self.line(0, "}");
            }
            Family::Kotlin | Family::Dart => self.line(0, "}"),
            Family::Pascal => {
                self.line(0, "end.");
            }
            Family::Fortran => self.line(0, "end program cuni"),
            Family::Ada => self.line(0, "end Main;"),
            Family::Lisp | Family::Clojure => self.line(0, ")"),
            Family::Elixir => self.line(0, "end"),
            Family::Erlang => self.line(0, "    ok."),
            Family::Solidity => {
                self.line(1, "}");
                self.line(0, "}");
            }
            Family::Awk => self.line(0, "}"),
            Family::Vb => self.line(0, "End Module"),
            _ => {}
        }
    }

    fn ext(&mut self, e: &ExtDecl) {
        self.comment(&format!(
            "ext {} — add a `{}:` body in the CuNi source for this target",
            e.name, self.lang.id
        ));
        if let Some((_, body)) = e.targets.iter().find(|(t, _)| t == self.lang.id || (*t == "js" && self.lang.id == "ts") || (*t == "py" && self.lang.id == "py")) {
            self.line(0, body.trim());
        }
    }

    fn typ(&mut self, t: &TypDecl) {
        let fields: Vec<String> = t.fields.iter().map(|f| f.name.clone()).collect();
        match self.lang.family {
            Family::Python => self.line(0, &format!("class {}:", t.name)),
            Family::Go => self.line(0, &format!("type {} struct {{ {} }}", t.name, fields.join(" "))),
            Family::Js | Family::Ts => self.line(0, &format!("class {} {{}}", t.name)),
            Family::Rust => self.line(0, &format!("struct {} {{ {} }}", t.name, fields.join(", "))),
            Family::Java | Family::CSharp | Family::Kotlin | Family::Scala | Family::Swift
            | Family::Dart | Family::Groovy => {
                self.line(0, &format!("class {} {{}}", t.name))
            }
            Family::C | Family::Cpp => self.line(0, &format!("typedef struct {{ /* {} */ }} {};", fields.join(", "), t.name)),
            _ => self.comment(&format!("typ {} fields={}", t.name, fields.join(","))),
        }
    }

    fn enom(&mut self, e: &EnumDecl) {
        self.comment(&format!("enum {} = {}", e.name, e.variants.join(" | ")));
    }

    fn func(&mut self, f: &FnDecl) {
        let params = f
            .params
            .iter()
            .map(|p| p.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        match self.lang.family {
            Family::Python | Family::Ruby | Family::Nim => {
                self.line(0, &format!("def {}({}):", f.name, params))
            }
            Family::Lua => self.line(0, &format!("function {}({})", f.name, params)),
            Family::Perl => self.line(0, &format!("sub {} {{", f.name)),
            Family::Php => self.line(0, &format!("function {}({}) {{", f.name, params)),
            Family::R => self.line(0, &format!("{} <- function({}) {{", f.name, params)),
            Family::Julia => self.line(0, &format!("function {}({})", f.name, params)),
            Family::Elixir => self.line(0, &format!("def {}({}) do", f.name, params)),
            Family::Bash => self.line(0, &format!("{}() {{", f.name)),
            Family::Powershell => self.line(0, &format!("function {} {{", f.name)),
            Family::Go => self.line(0, &format!("func {}({}) {{", f.name, params)),
            Family::Rust => self.line(0, &format!("fn {}({}) {{", f.name, params)),
            Family::C | Family::Cpp | Family::Objc => {
                self.line(0, &format!("void {}({}) {{", f.name, params))
            }
            Family::Java => {
                self.line(1, &format!("static void {}({}) {{", f.name, params))
            }
            Family::CSharp => self.line(1, &format!("static void {}({}) {{", f.name, params)),
            Family::Kotlin => self.line(0, &format!("fun {}({}) {{", f.name, params)),
            Family::Scala => self.line(0, &format!("def {}({}): Unit = {{", f.name, params)),
            Family::Swift => self.line(0, &format!("func {}({}) {{", f.name, params)),
            Family::Dart => self.line(0, &format!("void {}({}) {{", f.name, params)),
            Family::Js | Family::Ts => self.line(0, &format!("function {}({}) {{", f.name, params)),
            Family::Zig => self.line(0, &format!("fn {}({}) void {{", f.name, params)),
            Family::Haskell => self.line(0, &format!("{} {} = do", f.name, params)),
            Family::Lisp => self.line(0, &format!("(defun {} ({})", f.name, params)),
            Family::Clojure => self.line(0, &format!("(defn {} [{}]", f.name, params)),
            Family::Ocaml => self.line(0, &format!("let {} {} =", f.name, params)),
            Family::Fsharp => self.line(0, &format!("let {} {} =", f.name, params)),
            Family::Erlang => self.line(0, &format!("{}({}) ->", f.name, params)),
            Family::Matlab => self.line(0, &format!("function {}({})", f.name, params)),
            Family::Pascal => self.line(0, &format!("procedure {}({});", f.name, params)),
            Family::Fortran => self.line(0, &format!("subroutine {}({})", f.name, params)),
            Family::Groovy | Family::Crystal | Family::Haxe | Family::Hack | Family::Vlang
            | Family::D => self.line(0, &format!("fn {}({}) {{", f.name, params)),
            Family::Awk => self.line(0, &format!("function {}({}) {{", f.name, params)),
            Family::Tcl => self.line(0, &format!("proc {} {{{}}} {{", f.name, params)),
            Family::Smalltalk => self.comment(&format!("{} {}", f.name, params)),
            Family::Sql => self.comment(&format!("function {}", f.name)),
            Family::Assembly => self.line(0, &format!("{}:", f.name)),
            Family::Solidity => self.line(1, &format!("function {}() public {{", f.name)),
            Family::Cobol => self.comment(&format!("PROC {}", f.name)),
            Family::Prolog => self.line(0, &format!("{}({}) :-", f.name, params)),
            Family::Ada => self.line(0, &format!("procedure {} is", f.name)),
            Family::Vb => self.line(0, &format!("Sub {name}()", name = f.name)),
        }
        for s in &f.body {
            self.stmt(s, 1);
        }
        match self.lang.family {
            Family::Python | Family::Ruby | Family::Nim | Family::Haskell | Family::Ocaml
            | Family::Fsharp | Family::Erlang | Family::Prolog | Family::Matlab | Family::Fortran
            | Family::Assembly | Family::Sql | Family::Cobol | Family::Smalltalk | Family::Ada => {}
            Family::Lua | Family::Elixir | Family::Pascal => self.line(0, "end"),
            Family::Julia => self.line(0, "end"),
            Family::Lisp | Family::Clojure => self.line(0, ")"),
            Family::Bash => self.line(0, "}"),
            Family::Vb => self.line(0, "End Sub"),
            _ => self.line(0, "}"),
        }
        self.out.push('\n');
    }

    fn stmt(&mut self, s: &Stmt, indent: usize) {
        match &s.kind {
            StmtKind::Let { name, value, .. } | StmtKind::Mut { name, value, .. } => {
                let v = self.expr(value);
                let line = match self.lang.family {
                    Family::Python | Family::Ruby | Family::R | Family::Julia
                    | Family::Nim | Family::Crystal => format!("{name} = {v}"),
                    Family::Js | Family::Ts => format!("const {name} = {v};"),
                    Family::Go => format!("{name} := {v}"),
                    Family::Rust => format!("let {name} = {v};"),
                    Family::C | Family::Cpp | Family::Java | Family::CSharp | Family::Kotlin
                    | Family::Scala | Family::Swift | Family::Dart | Family::Zig | Family::D
                    | Family::Vlang | Family::Groovy | Family::Haxe | Family::Hack | Family::Php => {
                        format!("var {name} = {v};")
                    }
                    Family::Perl => format!("my ${name} = {v};"),
                    Family::Bash => format!("{name}={v}"),
                    Family::Powershell => format!("${name} = {v}"),
                    Family::Haskell => format!("let {name} = {v}"),
                    Family::Lisp => format!("(setq {name} {v})"),
                    Family::Clojure => format!("(def {name} {v})"),
                    Family::Elixir => format!("{name} = {v}"),
                    Family::Ocaml | Family::Fsharp => format!("let {name} = {v}"),
                    Family::Lua => format!("local {name} = {v}"),
                    _ => format!("{name} = {v}"),
                };
                self.line(indent, &line);
            }
            StmtKind::Assign { target, value } => {
                let t = self.expr(target);
                let v = self.expr(value);
                let semi = if matches!(
                    self.lang.family,
                    Family::Python
                        | Family::Ruby
                        | Family::Lua
                        | Family::Go
                        | Family::Haskell
                        | Family::Lisp
                        | Family::Bash
                ) {
                    ""
                } else {
                    ";"
                };
                self.line(indent, &format!("{t} = {v}{semi}"));
            }
            StmtKind::Ret(Some(e)) => {
                let v = self.expr(e);
                let line = match self.lang.family {
                    Family::Python | Family::Ruby | Family::Lua | Family::Julia | Family::Nim => {
                        format!("return {v}")
                    }
                    Family::Go | Family::Rust | Family::C | Family::Cpp | Family::Java
                    | Family::Js | Family::Ts | Family::Php | Family::Kotlin | Family::Swift
                    | Family::Dart | Family::CSharp => format!("return {v};"),
                    Family::Haskell => format!("return {v}"),
                    Family::Lisp => format!("{v}"),
                    Family::Bash => format!("echo {v}; return"),
                    Family::R => format!("return({v})"),
                    _ => format!("return {v}"),
                };
                self.line(indent, &line);
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let v = self.expr(e);
                self.line(indent, &format!("/* fail */ throw {v};"));
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let c = self.expr(cond);
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim => {
                        self.line(indent, &format!("if {c}:"))
                    }
                    Family::Lua => self.line(indent, &format!("if {c} then")),
                    Family::Haskell => self.line(indent, &format!("if {c} then")),
                    Family::Lisp => self.line(indent, &format!("(if {c}")),
                    Family::Bash => self.line(indent, &format!("if [ {c} ]; then")),
                    Family::Go | Family::Rust | Family::Js | Family::Ts | Family::C
                    | Family::Cpp | Family::Java | Family::Php | Family::Kotlin => {
                        self.line(indent, &format!("if ({c}) {{"))
                    }
                    _ => self.line(indent, &format!("if ({c}) {{")),
                }
                for s in then_body {
                    self.stmt(s, indent + 1);
                }
                if let Some(eb) = else_body {
                    match self.lang.family {
                        Family::Python | Family::Ruby | Family::Nim => self.line(indent, "else:"),
                        Family::Lua => self.line(indent, "else"),
                        _ => self.line(indent, "} else {"),
                    }
                    for s in eb {
                        self.stmt(s, indent + 1);
                    }
                }
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim | Family::Haskell => {}
                    Family::Lua | Family::Bash => self.line(indent, "end"),
                    Family::Lisp => self.line(indent, ")"),
                    _ => self.line(indent, "}"),
                }
            }
            StmtKind::For { binding, iter, body } => {
                let it = self.expr(iter);
                let k = &binding.0;
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim => {
                        self.line(indent, &format!("for {k} in {it}:"))
                    }
                    Family::Lua => self.line(indent, &format!("for {k} in {it} do")),
                    Family::Go => self.line(indent, &format!("for _, {k} := range {it} {{")),
                    Family::Js | Family::Ts => {
                        self.line(indent, &format!("for (const {k} of {it}) {{"))
                    }
                    Family::Rust => self.line(indent, &format!("for {k} in {it} {{")),
                    Family::Haskell => self.line(indent, &format!("forM_ {it} $ \\{k} -> do")),
                    Family::Lisp | Family::Clojure => {
                        self.line(indent, &format!("(doseq [{k} {it}]"))
                    }
                    Family::Bash => self.line(indent, &format!("for {k} in {it}; do")),
                    Family::R => self.line(indent, &format!("for ({k} in {it}) {{")),
                    _ => self.line(indent, &format!("for ({k} in {it}) {{")),
                }
                for s in body {
                    self.stmt(s, indent + 1);
                }
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim | Family::Haskell => {}
                    Family::Lua | Family::Bash => self.line(indent, "end"),
                    Family::Lisp | Family::Clojure => self.line(indent, ")"),
                    _ => self.line(indent, "}"),
                }
            }
            StmtKind::Whl { cond, body } => {
                let c = self.expr(cond);
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim => {
                        self.line(indent, &format!("while {c}:"))
                    }
                    Family::Lua => self.line(indent, &format!("while {c} do")),
                    Family::Bash => self.line(indent, &format!("while [ {c} ]; do")),
                    Family::Haskell => self.line(indent, &format!("while {c} do")),
                    Family::Lisp | Family::Clojure => self.line(indent, &format!("(while {c}")),
                    _ => self.line(indent, &format!("while ({c}) {{")),
                }
                for s in body {
                    self.stmt(s, indent + 1);
                }
                match self.lang.family {
                    Family::Python | Family::Ruby | Family::Nim | Family::Haskell => {}
                    Family::Lua | Family::Bash => self.line(indent, "end"),
                    Family::Lisp | Family::Clojure => self.line(indent, ")"),
                    _ => self.line(indent, "}"),
                }
            }
            StmtKind::ExprStmt(e) => {
                if let ExprKind::Call { callee, args } = &e.kind {
                    if let ExprKind::Ident(name) = &callee.kind {
                        if name == "say" {
                            let a = if args.is_empty() {
                                "\"\"".into()
                            } else {
                                self.expr(args[0].expr())
                            };
                            self.line(indent, &self.say(&a));
                            return;
                        }
                    }
                }
                let v = self.expr(e);
                let semi = if matches!(
                    self.lang.family,
                    Family::Python | Family::Ruby | Family::Lua | Family::Go | Family::Haskell
                ) {
                    ""
                } else {
                    ";"
                };
                self.line(indent, &format!("{v}{semi}"));
            }
            StmtKind::Todo => self.comment("..."),
        }
    }

    fn say(&self, e: &str) -> String {
        match self.lang.family {
            Family::Python | Family::Ruby | Family::Nim => format!("print({e})"),
            Family::Js | Family::Ts => format!("console.log({e});"),
            Family::Go => format!("fmt.Println({e})"),
            Family::Rust => format!("println!(\"{{}}\", {e});"),
            Family::C => format!("printf(\"%s\\n\", {e});"),
            Family::Cpp => format!("std::cout << {e} << std::endl;"),
            Family::Java | Family::Groovy => format!("System.out.println({e});"),
            Family::CSharp => format!("Console.WriteLine({e});"),
            Family::Kotlin => format!("println({e})"),
            Family::Scala => format!("println({e})"),
            Family::Swift => format!("print({e})"),
            Family::Dart => format!("print({e});"),
            Family::Php => format!("echo {e}, PHP_EOL;"),
            Family::Lua => format!("print({e})"),
            Family::Perl => format!("print {e}, \"\\n\";"),
            Family::R => format!("cat({e}, \"\\n\")"),
            Family::Julia => format!("println({e})"),
            Family::Elixir => format!("IO.puts({e})"),
            Family::Erlang => format!("io:format(\"~p~n\", [{e}])"),
            Family::Bash => format!("echo {e}"),
            Family::Powershell => format!("Write-Output {e}"),
            Family::Haskell => format!("print {e}"),
            Family::Lisp => format!("(print {e})"),
            Family::Clojure => format!("(println {e})"),
            Family::Ocaml => format!("print_endline (string_of_int {e})"),
            Family::Fsharp => format!("printfn \"%A\" {e}"),
            Family::Matlab => format!("disp({e})"),
            Family::Fortran => format!("print *, {e}"),
            Family::Pascal => format!("writeln({e});"),
            Family::Sql => format!("SELECT {e};"),
            Family::Awk => format!("print {e}"),
            Family::Tcl => format!("puts {e}"),
            Family::Smalltalk => format!("{e} printNl."),
            Family::Zig => format!("std.debug.print(\"{{any}}\\n\", .{{{e}}});"),
            Family::D => format!("writeln({e});"),
            Family::Vlang => format!("println({e})"),
            Family::Crystal => format!("puts {e}"),
            Family::Ada => format!("Ada.Text_IO.Put_Line({e});"),
            Family::Vb => format!("Console.WriteLine({e})"),
            Family::Objc => format!("NSLog(@\"%@\", {e});"),
            Family::Hack => format!("echo {e};"),
            Family::Haxe => format!("trace({e});"),
            Family::Solidity => format!("/* say {e} */;"),
            Family::Assembly => format!("/* say {e} */"),
            Family::Cobol => format!("DISPLAY {e}."),
            Family::Prolog => format!("write({e}), nl"),
        }
    }

    fn expr(&self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Float(f) => f.to_string(),
            ExprKind::Bool(true) => match self.lang.family {
                Family::Python | Family::Nim => "True".into(),
                Family::Lisp | Family::Clojure => "t".into(),
                Family::R => "TRUE".into(),
                Family::Fortran => ".true.".into(),
                Family::Pascal | Family::Ada | Family::Vb => "True".into(),
                _ => "true".into(),
            },
            ExprKind::Bool(false) => match self.lang.family {
                Family::Python | Family::Nim => "False".into(),
                Family::Lisp | Family::Clojure => "nil".into(),
                Family::R => "FALSE".into(),
                Family::Fortran => ".false.".into(),
                Family::Pascal | Family::Ada | Family::Vb => "False".into(),
                _ => "false".into(),
            },
            ExprKind::Str(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
            ExprKind::InterpStr(parts) => {
                let mut out = String::from("\"");
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => out.push_str(&t.replace('"', "\\\"")),
                        StrPartExpr::Expr(ex) => {
                            out.push_str("${");
                            out.push_str(&self.expr(ex));
                            out.push('}');
                        }
                    }
                }
                out.push('"');
                out
            }
            ExprKind::NoneLit => match self.lang.family {
                Family::Python => "None".into(),
                Family::Ruby => "nil".into(),
                Family::Lua | Family::Go | Family::Lisp => "nil".into(),
                Family::Js | Family::Ts => "null".into(),
                Family::Rust => "None".into(),
                Family::Java => "null".into(),
                _ => "null".into(),
            },
            ExprKind::Ident(s) => s.clone(),
            ExprKind::List(xs) => {
                let inner = xs.iter().map(|x| self.expr(x)).collect::<Vec<_>>().join(", ");
                match self.lang.family {
                    Family::Lisp | Family::Clojure => format!("(list {inner})"),
                    Family::Haskell => format!("[{inner}]"),
                    _ => format!("[{inner}]"),
                }
            }
            ExprKind::Map(pairs) => {
                let inner = pairs
                    .iter()
                    .map(|(k, v)| format!("{}: {}", self.expr(k), self.expr(v)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{{{inner}}}")
            }
            ExprKind::Call { callee, args } => {
                let c = self.expr(callee);
                let a = args
                    .iter()
                    .map(|x| self.expr(x.expr()))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{c}({a})")
            }
            ExprKind::Index { base, index } => {
                format!("{}[{}]", self.expr(base), self.expr(index))
            }
            ExprKind::Field { base, name } => format!("{}.{}", self.expr(base), name),
            ExprKind::Binary { op, lhs, rhs } => {
                let o = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::Ne => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Le => "<=",
                    BinOp::Ge => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                format!("({} {} {})", self.expr(lhs), o, self.expr(rhs))
            }
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("!{}", self.expr(expr)),
                UnOp::Neg => format!("-{}", self.expr(expr)),
            },
            ExprKind::Unwrap { expr, .. } => format!("/* ?? */ {}", self.expr(expr)),
        }
    }
}
