//! Fortran backend — custom core-subset native seat (seat id `f90`).
//!
//! Fortran is statically typed with mandatory declarations, so this seat is a
//! custom emitter rather than a [`crate::codegen_core`] spec: it tracks every
//! binding's type (`Int`/`Str`/`Bool`), collects declarations per program unit
//! (specification part before executable statements), and refuses anything
//! outside the core subset with the same honest `Err`s as the core.
//!
//! Emitted shape:
//! ```fortran
//! ! Generated by the CuNi core-subset backend. Do not hand-edit.
//! program main
//!   implicit none
//!   integer(kind=8) :: x
//!   x = 5_8
//!   call cuni_say_int(x)
//! contains
//!   function cuni_mod(a, b) result(r) ... end function cuni_mod
//!   subroutine cuni_say_int(x) ... end subroutine cuni_say_int
//!   function add(a, b) result(r)
//!     integer(kind=8), value :: a
//!     integer(kind=8), value :: b
//!     integer(kind=8) :: r
//!     r = (a + b)
//!     return
//!   end function add
//! end program main
//! ```
//!
//! Semantics notes:
//! - Integer `/` is native Fortran integer division, which truncates toward
//!   zero — CuNi semantics, no helper needed. `%` goes through
//!   `cuni_mod(a, b) = mod(mod(a, b) + b, b)`: Fortran's `mod` truncates like
//!   C, and applying it twice yields Python-floor semantics (verified by hand
//!   for all sign combinations).
//! - Strings are `character(len=:), allocatable`: exact length, never
//!   blank-padded, auto-(re)allocated on assignment. Concatenation is `//`.
//!   Literals escape `'` as `''`; control characters become `achar(n)`
//!   (`'a' // achar(10) // 'b'`).
//! - `say` is type-routed at emit time to `cuni_say_int` / `cuni_say_str` /
//!   `cuni_say_bool`, which print via `write(*,'(i0)')` / `write(*,'(a)')`.
//!   Plain `print *` would prepend a spurious blank to every value, so it is
//!   deliberately avoided. Booleans print `True`/`False`.
//! - Function parameters: `integer(kind=8), value :: a` / `logical, value :: b`
//!   (true copy semantics — rebinding a param never touches the caller) and
//!   `character(len=*), intent(in) :: s` for strings. Assigning to a *string*
//!   parameter is refused at emit time: Fortran has no value-copy for
//!   assumed-length character dummies, and pass-by-reference would leak the
//!   write to the caller.
//! - `ret e` becomes `r = e` followed by `return`. A top-level `ret` or a bare
//!   `ret` is refused — a Fortran `program` has no return slot, and an
//!   uninitialized `r` would be a silent wrong value.
//! - Block-scoped rebinding (`let` of an already-visible name) is renamed
//!   (`x__1`, …) so shadowing cannot collide in Fortran's flat scoping units.
//! - `def main` is refused (case-insensitive clash with `program main`), as is
//!   any `def` starting with `cuni_` (helper collision).
//!
//! Requires a Fortran 2003 compiler (deferred-length allocatable characters,
//! the `value` attribute); written against gfortran's documented semantics.
//! Internal procedures in one `contains` section are mutually visible, so
//! forward references and mutual recursion need no forward declarations.
//!
//! Wiring note: `emit.rs`/`main.rs` dispatch is left to the parent — this file
//! only provides `generate`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn f90_quote_chunk(chunk: &str) -> String {
    let mut r = String::from("'");
    for c in chunk.chars() {
        if c == '\'' {
            r.push_str("''");
        } else {
            r.push(c);
        }
    }
    r.push('\'');
    r
}

/// Fortran string literal: `'`-quoted with `''` doubling; control characters
/// become `achar(n)` joined by `//` (a raw newline may not appear inside a
/// free-form character literal).
fn f90_str(s: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut cur = String::new();
    for c in s.chars() {
        if (c as u32) < 0x20 || (c as u32) == 0x7f {
            if !cur.is_empty() {
                parts.push(f90_quote_chunk(&cur));
                cur.clear();
            }
            parts.push(format!("achar({})", c as u32));
        } else {
            cur.push(c);
        }
    }
    if !cur.is_empty() {
        parts.push(f90_quote_chunk(&cur));
    }
    if parts.is_empty() {
        return "''".to_string();
    }
    parts.join(" // ")
}

fn decl_of(name: &str, ty: Ty) -> String {
    match ty {
        Ty::Int => format!("integer(kind=8) :: {}", name),
        Ty::Str => format!("character(len=:), allocatable :: {}", name),
        Ty::Bool => format!("logical :: {}", name),
    }
}

fn param_decl(name: &str, ty: Ty) -> String {
    match ty {
        Ty::Int => format!("integer(kind=8), value :: {}", name),
        Ty::Str => format!("character(len=*), intent(in) :: {}", name),
        Ty::Bool => format!("logical, value :: {}", name),
    }
}

fn result_decl(ty: Ty) -> String {
    match ty {
        Ty::Int => "integer(kind=8) :: r".to_string(),
        Ty::Str => "character(len=:), allocatable :: r".to_string(),
        Ty::Bool => "logical :: r".to_string(),
    }
}

const HELPERS: &str = concat!(
    "  function cuni_mod(a, b) result(r)\n",
    "    integer(kind=8), value :: a\n",
    "    integer(kind=8), value :: b\n",
    "    integer(kind=8) :: r\n",
    "    r = mod(mod(a, b) + b, b)\n",
    "  end function cuni_mod\n",
    "  subroutine cuni_say_int(x)\n",
    "    integer(kind=8), value :: x\n",
    "    write(*, '(i0)') x\n",
    "  end subroutine cuni_say_int\n",
    "  subroutine cuni_say_str(s)\n",
    "    character(len=*), intent(in) :: s\n",
    "    write(*, '(a)') s\n",
    "  end subroutine cuni_say_str\n",
    "  subroutine cuni_say_bool(b)\n",
    "    logical, value :: b\n",
    "    if (b) then\n",
    "      write(*, '(a)') 'True'\n",
    "    else\n",
    "      write(*, '(a)') 'False'\n",
    "    end if\n",
    "  end subroutine cuni_say_bool\n",
);

/// One scoping unit (the main program or one function): declarations are
/// collected while the body is generated, then emitted ahead of it.
struct Unit {
    body: String,
    decls: Vec<(String, Ty)>,
    declared: HashSet<String>,
    /// Lowercase of every declared name, parameter, and the result variable:
    /// Fortran is case-insensitive, so a new binding that collides only by
    /// case is refused rather than silently aliasing.
    taken_lower: HashSet<String>,
    level: usize,
    /// Scope stack: source name -> (type, emitted name).
    frames: Vec<HashMap<String, (Ty, String)>>,
    /// Emitted names of string parameters (assignment to them is refused).
    str_params: HashSet<String>,
    in_func: bool,
}

impl Unit {
    fn new() -> Self {
        Unit {
            body: String::new(),
            decls: Vec::new(),
            declared: HashSet::new(),
            taken_lower: HashSet::new(),
            level: 0,
            frames: Vec::new(),
            str_params: HashSet::new(),
            in_func: false,
        }
    }

    fn bl(&mut self, text: &str) {
        if !text.is_empty() {
            self.body.push_str(&"  ".repeat(self.level));
            self.body.push_str(text);
        }
        self.body.push('\n');
    }
}

struct Emitter {
    out: String,
    /// Function name -> (params, return type). Fully populated before any
    /// body is generated, so forward references are fine.
    sigs: HashMap<String, (Vec<(String, Ty)>, Ty)>,
    counter: u32,
    unit: Unit,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        sigs: HashMap::new(),
        counter: 0,
        unit: Unit::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

impl Emitter {
    fn lookup(&self, name: &str) -> Option<(Ty, String)> {
        for f in self.unit.frames.iter().rev() {
            if let Some(v) = f.get(name) {
                return Some(v.clone());
            }
        }
        None
    }

    /// Bind `name` to a fresh local. If the name is already visible *or* was
    /// ever declared in this unit (declarations hoist to the specification
    /// part, so a later same-name binding would collide), the emitted name
    /// is renamed (`x__1`). A binding that collides only by case is refused —
    /// Fortran would silently alias it.
    fn bind(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let reuse = self.lookup(name).is_some() || self.unit.declared.contains(name);
        let emitted = if reuse {
            self.counter += 1;
            format!("{}__{}", name, self.counter)
        } else {
            name.to_string()
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "binding `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower);
        if !self.unit.declared.contains(&emitted) {
            self.unit.declared.insert(emitted.clone());
            self.unit.decls.push((emitted.clone(), ty));
        }
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    /// Bind a parameter: enters the scope (with rename on collision, e.g.
    /// against the result variable `r`) but adds no local declaration — the
    /// dummy is declared in the function signature.
    fn bind_param(&mut self, name: &str, ty: Ty) -> Result<String, String> {
        let emitted = match self.lookup(name) {
            Some(_) => {
                self.counter += 1;
                format!("{}__{}", name, self.counter)
            }
            None => name.to_string(),
        };
        let lower = emitted.to_lowercase();
        if self.unit.taken_lower.contains(&lower) {
            return Err(format!(
                "parameter `{}` collides case-insensitively with an existing name; refusing",
                name
            ));
        }
        self.unit.taken_lower.insert(lower);
        if ty == Ty::Str {
            self.unit.str_params.insert(emitted.clone());
        }
        self.unit
            .frames
            .last_mut()
            .expect("scope frame")
            .insert(name.to_string(), (ty, emitted.clone()));
        Ok(emitted)
    }

    fn check_ann(&self, name: &str, ty: &Option<Type>, vt: Ty, kw: &str) -> Result<(), String> {
        if let Some(t) = ty {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!(
                    "{} {}: annotated type disagrees with value type; refusing",
                    kw, name
                ));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            return Err(format!(
                "def {}: fallible functions beyond core subset; refusing",
                f.name
            ));
        }
        if !f.generics.is_empty() {
            return Err(format!(
                "def {}: generics beyond core subset; refusing",
                f.name
            ));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        if f.name.to_lowercase().starts_with("cuni_") {
            return Err(format!(
                "def {}: reserved cuni_ prefix (collides with helpers); refusing",
                f.name
            ));
        }
        if f.name.eq_ignore_ascii_case("main") {
            return Err("def main: collides with the Fortran program unit; refusing".into());
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        // First pass: collect def signatures, refuse non-core items.
        let mut seen_lower: HashSet<String> = HashSet::new();
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    if !seen_lower.insert(f.name.to_lowercase()) {
                        return Err(format!(
                            "def {}: duplicate (case-insensitive) definition; refusing",
                            f.name
                        ));
                    }
                    let mut params = Vec::new();
                    for p in &f.params {
                        params.push((p.name.clone(), ty_of(&p.ty)?));
                    }
                    let ret = ty_of(&f.ret_type)?;
                    self.sigs.insert(f.name.clone(), (params, ret));
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => {
                    return Err(format!("use {}: beyond core subset; refusing", u.name))
                }
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        // Second pass: function bodies (any order — signatures are complete).
        let mut fns = String::new();
        for item in &program.items {
            if let Item::Def(f) = item {
                fns.push_str(&self.gen_def(f)?);
                fns.push('\n');
            }
        }
        // Main program unit.
        self.unit = Unit::new();
        self.unit.level = 1;
        self.unit.frames.push(HashMap::new());
        for s in script {
            self.gen_stmt(s)?;
        }
        let main_unit = std::mem::replace(&mut self.unit, Unit::new());

        self.out
            .push_str("! Generated by the CuNi core-subset backend. Do not hand-edit.\n");
        self.out.push_str("program main\n");
        self.out.push_str("  implicit none\n");
        for (n, t) in &main_unit.decls {
            self.out.push_str(&format!("  {}\n", decl_of(n, *t)));
        }
        self.out.push_str(&main_unit.body);
        self.out.push_str("contains\n");
        self.out.push_str(HELPERS);
        self.out.push_str(&fns);
        self.out.push_str("end program main\n");
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<String, String> {
        let (params, ret) = self
            .sigs
            .get(&f.name)
            .cloned()
            .ok_or_else(|| format!("internal: missing signature for `{}`", f.name))?;
        let saved = std::mem::replace(&mut self.unit, Unit::new());
        self.unit.level = 1;
        self.unit.in_func = true;
        self.unit.frames.push(HashMap::new());
        // Pre-bind the result variable so a user binding named `r` renames.
        self.unit
            .frames[0]
            .insert("r".to_string(), (ret, "r".to_string()));
        self.unit.declared.insert("r".to_string());
        self.unit.taken_lower.insert("r".to_string());
        let mut pinfo: Vec<(String, Ty)> = Vec::new();
        for (n, t) in &params {
            let emitted = self.bind_param(n, *t)?;
            pinfo.push((emitted, *t));
        }
        for s in &f.body {
            self.gen_stmt(s)?;
        }
        let finished = std::mem::replace(&mut self.unit, saved);

        let pnames: Vec<String> = pinfo.iter().map(|(n, _)| n.clone()).collect();
        let mut s = String::new();
        s.push_str(&format!(
            "  recursive function {}({}) result(r)\n",
            f.name,
            pnames.join(", ")
        ));
        for (n, t) in &pinfo {
            s.push_str(&format!("    {}\n", param_decl(n, *t)));
        }
        s.push_str(&format!("    {}\n", result_decl(ret)));
        for (n, t) in &finished.decls {
            s.push_str(&format!("    {}\n", decl_of(n, *t)));
        }
        for line in finished.body.lines() {
            if line.trim().is_empty() {
                s.push('\n');
            } else {
                s.push_str("  ");
                s.push_str(line);
                s.push('\n');
            }
        }
        s.push_str(&format!("  end function {}\n", f.name));
        Ok(s)
    }

    fn gen_stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match &s.kind {
            StmtKind::Let { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "let")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} = {}", emitted, v));
                Ok(())
            }
            StmtKind::Mut { name, ty, value } => {
                let (v, vt) = self.gen_expr(value)?;
                self.check_ann(name, ty, vt, "mut")?;
                let emitted = self.bind(name, vt)?;
                self.unit.bl(&format!("{} = {}", emitted, v));
                Ok(())
            }
            StmtKind::Assign { target, value } => {
                let tname = match &target.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => {
                        return Err(
                            "complex assignment target: beyond core subset; refusing".into()
                        )
                    }
                };
                let (_, emitted) = self
                    .lookup(&tname)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", tname))?;
                if self.unit.str_params.contains(&emitted) {
                    return Err(format!(
                        "assignment to string parameter `{}`: not expressible with Fortran value semantics; refusing",
                        tname
                    ));
                }
                let (v, _) = self.gen_expr(value)?;
                self.unit.bl(&format!("{} = {}", emitted, v));
                Ok(())
            }
            StmtKind::Ret(e) => {
                if !self.unit.in_func {
                    return Err(
                        "top-level ret: no return slot in a Fortran program; refusing".into(),
                    );
                }
                match e {
                    Some(x) => {
                        let (v, _) = self.gen_expr(x)?;
                        self.unit.bl(&format!("r = {}", v));
                        self.unit.bl("return");
                    }
                    None => return Err("bare ret: beyond core subset; refusing".into()),
                }
                Ok(())
            }
            StmtKind::Fail(_) => Err("fail: beyond core subset; refusing".into()),
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("if condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("if ({}) then", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in then_body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                if let Some(eb) = else_body {
                    self.unit.bl("else");
                    self.unit.level += 1;
                    self.unit.frames.push(HashMap::new());
                    for s in eb {
                        self.gen_stmt(s)?;
                    }
                    self.unit.frames.pop();
                    self.unit.level -= 1;
                }
                self.unit.bl("end if");
                Ok(())
            }
            StmtKind::For { .. } => Err("for: beyond core subset; refusing".into()),
            StmtKind::Whl { cond, body } => {
                let (c, ct) = self.gen_expr(cond)?;
                if ct != Ty::Bool {
                    return Err("while condition must be bool; refusing".into());
                }
                self.unit.bl(&format!("do while ({})", c));
                self.unit.level += 1;
                self.unit.frames.push(HashMap::new());
                for s in body {
                    self.gen_stmt(s)?;
                }
                self.unit.frames.pop();
                self.unit.level -= 1;
                self.unit.bl("end do");
                Ok(())
            }
            StmtKind::ExprStmt(e) => {
                // Only `say(...)` calls allowed as bare expression statements.
                match &e.kind {
                    ExprKind::Call { callee, args } => {
                        if let ExprKind::Ident(n) = &callee.kind {
                            if n == "say" {
                                if args.len() != 1 {
                                    return Err(
                                        "say: exactly one argument in core subset; refusing".into()
                                    );
                                }
                                let (v, vt) = self.gen_expr(args[0].expr())?;
                                let helper = match vt {
                                    Ty::Int => "cuni_say_int",
                                    Ty::Str => "cuni_say_str",
                                    Ty::Bool => "cuni_say_bool",
                                };
                                self.unit.bl(&format!("call {}({})", helper, v));
                                return Ok(());
                            }
                        }
                        Err("bare call (non-say): beyond core subset; refusing".into())
                    }
                    _ => Err("bare expression: beyond core subset; refusing".into()),
                }
            }
            StmtKind::Todo => Err("...: beyond core subset; refusing".into()),
        }
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((format!("{}_8", n), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b {
                    ".true.".to_string()
                } else {
                    ".false.".to_string()
                },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((f90_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let (t, emitted) = self
                    .lookup(n)
                    .ok_or_else(|| format!("unknown variable `{}`: refusing", n))?;
                Ok((emitted, t))
            }
            ExprKind::InterpStr(_) => {
                Err("interpolated string: beyond core subset; refusing".into())
            }
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self
                    .sigs
                    .get(&name)
                    .map(|(_, r)| *r)
                    .ok_or_else(|| format!("call to unknown function `{}`: refusing", name))?;
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    if a.is_named() {
                        return Err("named arguments: beyond core subset; refusing".into());
                    }
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                Ok((format!("{}({})", name, as_.join(", ")), ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            return Ok((format!("({} // {})", l, r), Ty::Str));
                        } else if lt == Ty::Int && rt == Ty::Int {
                            return Ok((format!("({} + {})", l, r), Ty::Int));
                        }
                        return Err("mixed-type `+`: beyond core subset; refusing".into());
                    }
                    BinOp::Sub => {
                        require_ints(lt, rt, "-")?;
                        Ok((format!("({} - {})", l, r), Ty::Int))
                    }
                    BinOp::Mul => {
                        require_ints(lt, rt, "*")?;
                        Ok((format!("({} * {})", l, r), Ty::Int))
                    }
                    BinOp::Div => {
                        require_ints(lt, rt, "/")?;
                        // Native Fortran integer division truncates toward zero.
                        Ok((format!("({} / {})", l, r), Ty::Int))
                    }
                    BinOp::Mod => {
                        require_ints(lt, rt, "%")?;
                        // Fortran's mod truncates; the helper floors.
                        Ok((format!("cuni_mod({}, {})", l, r), Ty::Int))
                    }
                    BinOp::Eq => Ok((format!("({} == {})", l, r), Ty::Bool)),
                    BinOp::Ne => Ok((format!("({} /= {})", l, r), Ty::Bool)),
                    BinOp::Lt => Ok((format!("({} < {})", l, r), Ty::Bool)),
                    BinOp::Gt => Ok((format!("({} > {})", l, r), Ty::Bool)),
                    BinOp::Le => Ok((format!("({} <= {})", l, r), Ty::Bool)),
                    BinOp::Ge => Ok((format!("({} >= {})", l, r), Ty::Bool)),
                    BinOp::And => {
                        require_bools(lt, rt, "and")?;
                        Ok((format!("({} .and. {})", l, r), Ty::Bool))
                    }
                    BinOp::Or => {
                        require_bools(lt, rt, "or")?;
                        Ok((format!("({} .or. {})", l, r), Ty::Bool))
                    }
                }
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(.not. {})", v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{})", v), Ty::Int))
                    }
                }
            }
        }
    }
}

fn require_ints(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Int && r == Ty::Int {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-int: beyond core subset; refusing",
            op
        ))
    }
}

fn require_bools(l: Ty, r: Ty, op: &str) -> Result<(), String> {
    if l == Ty::Bool && r == Ty::Bool {
        Ok(())
    } else {
        Err(format!(
            "`{}` on non-bool: beyond core subset; refusing",
            op
        ))
    }
}
