use crate::ast::*;
use std::collections::HashMap;

/// A toy, best-effort Python emitter for the CuNi AST. It exists to prove the
/// pipeline (parse -> emit) works end to end for the constructs the spec has
/// fully defined; it is NOT the real "compile-or-refuse" compiler described in
/// SPEC.md — it never rejects a program, it just does its best and leaves a
/// comment where the mapping is genuinely undefined (see NOTES below).
///
/// NOTES / known gaps surfaced by writing this:
/// - `fail expr` (signaling failure from a fallible function body) emits
///   `raise CuNiError(expr)` — `CuNiError` is a single exception class emitted
///   once per program (see gen_program). `??`'s existing `except Exception`
///   handling already catches it, same as any other exception. A still-`...`
///   stub body emits `raise NotImplementedError()` instead, since "not
///   implemented yet" and "this call failed" are different concepts even
///   though Python happens to model both as exceptions.
/// - `iface` methods are modeled as Python ABC abstractmethods (with an
///   implicit `self`), but the spec's own example (`def area(c: Circle) ->
///   float`) implements `Shape.area` as a free function taking the receiver
///   explicitly, not as a method. Nothing in the spec ties the two together,
///   so `typ Circle is Shape` does not actually satisfy Python's ABC contract
///   here. This is a genuine spec gap, not a codegen shortcut.
/// - `??` (Unwrap) is only handled when it's the direct value of a `let`/`mut`
///   statement, matching every example so far. In any other expression
///   position it emits an `# UNSUPPORTED` marker.
/// - `for k, v in m` vs `for i, x in xs` (map vs list iteration) is decided by
///   a lightweight scope-tracked guess (param/annotation type, or literal
///   shape), not real type inference. Good enough for the current examples;
///   not a substitute for the type checker this still needs.
/// - `link` (SPEC.md §19) additionally emits an HTTP handler (stdlib
///   `http.server`-shaped, taking a `BaseHTTPRequestHandler` instance) and an
///   always-fallible `<name>_remote` client stub (stdlib `urllib.request`) —
///   zero third-party dependencies, matching the ratified interop proposal.
///   See `gen_link_handler`/`gen_link_remote` and `py_wire_encode`/`decode`.
pub fn generate(program: &Program) -> String {
    let mut cg = Codegen::new(program);
    cg.gen_program(program);
    cg.out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    List,
    Map,
    Other,
}

struct FnInfo {
    fallible: bool,
}

struct Codegen {
    fn_info: HashMap<String, FnInfo>,
    has_link: bool,
    out: String,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_info = HashMap::new();
        for item in &program.items {
            if let Item::Def(f) = item {
                fn_info.insert(
                    f.name.clone(),
                    FnInfo {
                        fallible: f.fallible,
                    },
                );
            }
        }
        for item in &program.items {
            if let Item::Def(f) = item {
                if f.is_link {
                    // The remote client stub is always fallible (a network
                    // call can always fail even if the local body can't) —
                    // registering it here lets the existing `??`/Unwrap
                    // codegen path (gen_binding) handle it for free, exactly
                    // like any other fallible function call.
                    fn_info.insert(format!("{}_remote", f.name), FnInfo { fallible: true });
                }
            }
        }
        let has_link = program
            .items
            .iter()
            .any(|i| matches!(i, Item::Def(f) if f.is_link));
        Codegen {
            fn_info,
            has_link,
            out: String::new(),
        }
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) {
        self.line(
            0,
            "# Generated by the CuNi toy Python backend. Do not hand-edit.",
        );
        self.line(0, "from __future__ import annotations  # lets generic params like T appear in annotations unevaluated");
        self.line(0, "from typing import List, Dict, Optional");
        self.line(0, "from dataclasses import dataclass");
        self.line(0, "from abc import ABC, abstractmethod");
        self.line(0, "from enum import Enum, auto");
        if self.has_link {
            self.line(0, "import json");
            self.line(0, "import urllib.request");
            self.line(0, "import urllib.error");
        }
        self.out.push('\n');
        self.line(0, "def say(x):");
        self.line(1, "print(x)");
        self.out.push('\n');
        self.line(0, "def range(n):");
        self.line(1, "n = int(n)");
        self.line(1, "if n <= 0:");
        self.line(2, "return []");
        self.line(1, "out = []");
        self.line(1, "i = 0");
        self.line(1, "while i < n:");
        self.line(2, "out.append(i)");
        self.line(2, "i += 1");
        self.line(1, "return out");
        self.out.push('\n');
        self.line(0, "def abs(n):");
        self.line(1, "n = int(n)");
        self.line(1, "return n if n >= 0 else -n");
        self.out.push('\n');
        self.line(0, "def min(a, b):");
        self.line(1, "a, b = int(a), int(b)");
        self.line(1, "return a if a <= b else b");
        self.out.push('\n');
        self.line(0, "def max(a, b):");
        self.line(1, "a, b = int(a), int(b)");
        self.line(1, "return a if a >= b else b");
        self.out.push('\n');
        self.line(0, "def _cuni_slice(xs, a, b):");
        self.line(1, "a, b = int(a), int(b)");
        self.line(1, "n = len(xs)");
        self.line(1, "if a < 0 or b < 0 or a > n or b > n or a > b:");
        self.line(2, "return \"\" if isinstance(xs, str) else []");
        self.line(1, "return xs[a:b]");
        self.out.push('\n');
        self.line(0, "def _cuni_div(a, b):");
        self.line(1, "if type(a) is CuniDec and type(b) is CuniDec:");
        self.line(2, "return a / b  # CuniDec.__truediv__: trunc(a*10000/b) toward zero, exact");
        self.line(1, "if type(a) is int and type(b) is int and b != 0:");
        self.line(2, "return int(a / b) if a * b < 0 else a // b");
        self.line(1, "return a / b");
        self.out.push('\n');
        self.line(0, "def _cuni_tdiv(a, b):");
        self.line(1, "# Truncation toward zero (docs/DECIMAL.md §3) — Python's // floors.");
        self.line(1, "q = abs(a) // abs(b)");
        self.line(1, "return -q if (a < 0) != (b < 0) else q");
        self.out.push('\n');
        self.line(0, "def _cuni_dec_str(v):");
        self.line(1, "# Canonical dec rendering of a scaled int (docs/DECIMAL.md §6).");
        self.line(1, "neg = v < 0");
        self.line(1, "mag = -v if neg else v");
        self.line(1, "i, f = divmod(mag, 10000)");
        self.line(1, "fs = (\"%04d\" % f).rstrip(\"0\") or \"0\"");
        self.line(1, "return (\"-\" if neg else \"\") + str(i) + \".\" + fs");
        self.out.push('\n');
        self.line(0, "def _cuni_dec_of_int(n):");
        self.line(1, "return CuniDec(int(n) * 10000)");
        self.out.push('\n');
        self.line(0, "def _cuni_int_of_dec(d):");
        self.line(1, "return _cuni_tdiv(int(d), 10000)");
        self.out.push('\n');
        self.line(0, "class CuniDec(int):");
        self.line(1, "# CuNi `dec`: fixed-point decimal, scale 10^4, exact (docs/DECIMAL.md).");
        self.line(1, "# Stored as a scaled int; every operator keeps the tag and the scale,");
        self.line(1, "# so plain `+ - * /` in emitted code stay exact with no codegen");
        self.line(1, "# type inference. Mixing with plain int is refused (TypeError) — the");
        self.line(1, "# typeck already rejected it; this is defense in depth.");
        self.line(1, "__slots__ = ()");
        self.line(1, "def __str__(self):");
        self.line(2, "return _cuni_dec_str(int(self))");
        self.line(1, "def __repr__(self):");
        self.line(2, "return _cuni_dec_str(int(self))");
        self.line(1, "def __format__(self, spec):");
        self.line(2, "return _cuni_dec_str(int(self)) if not spec else format(_cuni_dec_str(int(self)), spec)");
        self.line(1, "def __add__(self, o):");
        self.line(2, "if not isinstance(o, CuniDec):");
        self.line(3, "raise TypeError(\"cuni: cannot mix dec and non-dec — convert explicitly\")");
        self.line(2, "return CuniDec(int(self) + int(o))");
        self.line(1, "def __sub__(self, o):");
        self.line(2, "if not isinstance(o, CuniDec):");
        self.line(3, "raise TypeError(\"cuni: cannot mix dec and non-dec — convert explicitly\")");
        self.line(2, "return CuniDec(int(self) - int(o))");
        self.line(1, "def __mul__(self, o):");
        self.line(2, "if not isinstance(o, CuniDec):");
        self.line(3, "raise TypeError(\"cuni: cannot mix dec and non-dec — convert explicitly\")");
        self.line(2, "return CuniDec(_cuni_tdiv(int(self) * int(o), 10000))");
        self.line(1, "def __truediv__(self, o):");
        self.line(2, "if not isinstance(o, CuniDec):");
        self.line(3, "raise TypeError(\"cuni: cannot mix dec and non-dec — convert explicitly\")");
        self.line(2, "if int(o) == 0:");
        self.line(3, "raise ZeroDivisionError(\"cuni: dec division by zero\")");
        self.line(2, "return CuniDec(_cuni_tdiv(int(self) * 10000, int(o)))");
        self.line(1, "def __neg__(self):");
        self.line(2, "return CuniDec(-int(self))");
        self.out.push('\n');
        // ---- CuNi `time`: int64 unix epoch seconds, UTC (docs/TIME.md) ----
        self.line(0, "def _cuni_time_str(v):");
        self.line(1, "# Canonical ISO-8601 UTC rendering of an epoch (docs/TIME.md §4).");
        self.line(1, "# Pure integer civil-from-days; divmod floors, so negatives work.");
        self.line(1, "days, sod = divmod(v, 86400)");
        self.line(1, "z = days + 719468");
        self.line(1, "era = z // 146097");
        self.line(1, "doe = z - era * 146097");
        self.line(1, "yoe = (doe - doe // 1460 + doe // 36524 - doe // 146096) // 365");
        self.line(1, "y = yoe + era * 400");
        self.line(1, "doy = doe - (365 * yoe + yoe // 4 - yoe // 100)");
        self.line(1, "mp = (5 * doy + 2) // 153");
        self.line(1, "d = doy - (153 * mp + 2) // 5 + 1");
        self.line(1, "m = mp + 3 if mp < 10 else mp - 9");
        self.line(1, "if m <= 2: y += 1");
        self.line(1, "hh, rem = divmod(sod, 3600)");
        self.line(1, "mi, ss = divmod(rem, 60)");
        self.line(1, "ys = (\"-\" if y < 0 else \"\") + str(abs(y)).zfill(4)");
        self.line(1, "return f\"{ys}-{m:02d}-{d:02d}T{hh:02d}:{mi:02d}:{ss:02d}Z\"");
        self.out.push('\n');
        self.line(0, "def _cuni_parse_time(s):");
        self.line(1, "# Strict ISO-8601 UTC -> CuniTime (docs/TIME.md §2, §5). Bad input");
        self.line(1, "# raises loudly — never a silent value.");
        self.line(1, "def _bad(): raise ValueError(\"cuni: parse_time: bad ISO-8601 UTC timestamp — refused\")");
        self.line(1, "if not isinstance(s, str) or len(s) != 20: _bad()");
        self.line(1, "if s[4] != \"-\" or s[7] != \"-\" or s[10] != \"T\" or s[13] != \":\" or s[16] != \":\" or s[19] != \"Z\": _bad()");
        self.line(1, "for i in (0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18):");
        self.line(2, "if not (\"0\" <= s[i] <= \"9\"): _bad()");
        self.line(1, "y, mo, d = int(s[0:4]), int(s[5:7]), int(s[8:10])");
        self.line(1, "h, mi, sec = int(s[11:13]), int(s[14:16]), int(s[17:19])");
        self.line(1, "if not (1 <= y <= 9999): _bad()");
        self.line(1, "if not (1 <= mo <= 12): _bad()");
        self.line(1, "dim = 31");
        self.line(1, "if mo in (4, 6, 9, 11): dim = 30");
        self.line(1, "elif mo == 2: dim = 29 if (y % 4 == 0 and (y % 100 != 0 or y % 400 == 0)) else 28");
        self.line(1, "if not (1 <= d <= dim): _bad()");
        self.line(1, "if not (0 <= h <= 23 and 0 <= mi <= 59 and 0 <= sec <= 59): _bad()");
        self.line(1, "y0 = y - 1 if mo <= 2 else y");
        self.line(1, "era = y0 // 400");
        self.line(1, "yoe = y0 - era * 400");
        self.line(1, "mp = (mo + 9) % 12");
        self.line(1, "doy = (153 * mp + 2) // 5 + d - 1");
        self.line(1, "doe = yoe * 365 + yoe // 4 - yoe // 100 + doy");
        self.line(1, "days = era * 146097 + doe - 719468");
        self.line(1, "return CuniTime(days * 86400 + h * 3600 + mi * 60 + sec)");
        self.out.push('\n');
        self.line(0, "def _cuni_add_seconds(t, s):");
        self.line(1, "return t + s  # CuniTime.__add__: time + int -> time, loud on misuse");
        self.out.push('\n');
        self.line(0, "def _cuni_days_between(a, b):");
        self.line(1, "# (a - b) is int seconds (CuniTime.__sub__); trunc toward zero.");
        self.line(1, "return _cuni_tdiv(a - b, 86400)");
        self.out.push('\n');
        self.line(0, "class CuniTime(int):");
        self.line(1, "# CuNi `time`: int64 unix epoch seconds, UTC (docs/TIME.md).");
        self.line(1, "# Stored as a plain int (the epoch); every operator keeps the tag,");
        self.line(1, "# so plain `+`/`-` in emitted code stay exact with no codegen");
        self.line(1, "# type inference. `int + time` works via __radd__ (CuniTime is an");
        self.line(1, "# int subclass, so Python tries the reflected op first). Mixing");
        self.line(1, "# with anything but a plain int duration is refused (TypeError) —");
        self.line(1, "# the typeck already rejected it; this is defense in depth.");
        self.line(1, "__slots__ = ()");
        self.line(1, "def __str__(self):");
        self.line(2, "return _cuni_time_str(int(self))");
        self.line(1, "def __repr__(self):");
        self.line(2, "return _cuni_time_str(int(self))");
        self.line(1, "def __format__(self, spec):");
        self.line(2, "s = _cuni_time_str(int(self))");
        self.line(2, "return s if not spec else format(s, spec)");
        self.line(1, "def __add__(self, o):");
        self.line(2, "if isinstance(o, CuniTime):");
        self.line(3, "raise TypeError(\"cuni: cannot add time + time — refusing\")");
        self.line(2, "if not isinstance(o, int):");
        self.line(3, "raise TypeError(\"cuni: cannot mix time and non-int — refusing\")");
        self.line(2, "return CuniTime(int(self) + int(o))");
        self.line(1, "def __radd__(self, o):");
        self.line(2, "if isinstance(o, CuniTime) or not isinstance(o, int):");
        self.line(3, "raise TypeError(\"cuni: cannot mix time and non-int — refusing\")");
        self.line(2, "return CuniTime(int(o) + int(self))");
        self.line(1, "def __sub__(self, o):");
        self.line(2, "if isinstance(o, CuniTime):");
        self.line(3, "return int(self) - int(o)  # time - time -> int seconds");
        self.line(2, "if not isinstance(o, int):");
        self.line(3, "raise TypeError(\"cuni: cannot mix time and non-int — refusing\")");
        self.line(2, "return CuniTime(int(self) - int(o))");
        self.line(1, "def __neg__(self):");
        self.line(2, "return CuniTime(-int(self))");
        self.out.push('\n');
        // ---- Wave-1 stdlib (docs/STDLIB.md). Module imports are lazy
        // (inside the helpers) so programs that don't use the stdlib pay
        // nothing and emit no extra imports.
        self.line(0, "_CUNI_JSON_INT_MAX = 9007199254740991");
        self.out.push('\n');
        self.line(0, "def _cuni_json_int_value(tok):");
        self.line(1, "\"\"\"Value-based integer rule (docs/STDLIB.md §1.1): accept iff the");
        self.line(1, "number's exact value is an integer in ±(2^53−1).\"\"\"");
        self.line(1, "t = tok.strip()");
        self.line(1, "neg = t.startswith(\"-\")");
        self.line(1, "if neg: t = t[1:]");
        self.line(1, "if \"e\" in t or \"E\" in t:");
        self.line(2, "mant, _, exp_s = t.replace(\"E\", \"e\").partition(\"e\")");
        self.line(2, "exp = int(exp_s)");
        self.line(1, "else: mant, exp = t, 0");
        self.line(1, "if \".\" in mant:");
        self.line(2, "ip, _, fp = mant.partition(\".\")");
        self.line(2, "f = len(fp)");
        self.line(2, "digits = (ip + fp).lstrip(\"0\")");
        self.line(1, "else: digits, f = mant.lstrip(\"0\"), 0");
        self.line(1, "if not digits: return 0");
        self.line(1, "if len(digits) > 16: raise CuNiError(\"json.parse: number is not an integer in ±(2^53−1)\")");
        self.line(1, "d = int(digits)");
        self.line(1, "while d % 10 == 0 and d != 0: d //= 10; f -= 1");
        self.line(1, "k = f - exp");
        self.line(1, "if k <= 0: v = d * (10 ** (-k))");
        self.line(1, "else:");
        self.line(2, "if k > 16 or d % (10 ** k) != 0: raise CuNiError(\"json.parse: number is not an integer in ±(2^53−1)\")");
        self.line(2, "v = d // (10 ** k)");
        self.line(1, "if neg: v = -v");
        self.line(1, "if abs(v) > _CUNI_JSON_INT_MAX: raise CuNiError(\"json.parse: number is not an integer in ±(2^53−1)\")");
        self.line(1, "return v");
        self.out.push('\n');
        self.line(0, "def _cuni_json_parse(s):");
        self.line(1, "import json as _json");
        self.line(1, "if not isinstance(s, str): raise CuNiError(\"json.parse needs a str\")");
        self.line(1, "try:");
        self.line(2, "v = _json.loads(s, parse_int=_cuni_json_int_value, parse_float=_cuni_json_int_value)");
        self.line(1, "except ValueError: raise CuNiError(\"json.parse: invalid JSON\")");
        self.line(1, "if not isinstance(v, dict): raise CuNiError(\"json.parse: top-level JSON value must be an object\")");
        self.line(1, "return v");
        self.out.push('\n');
        self.line(0, "def _cuni_json_norm(v):");
        self.line(1, "if isinstance(v, bool): return v");
        self.line(1, "if isinstance(v, int): return v");
        self.line(1, "if isinstance(v, float): raise CuNiError(\"json.emit: floats have no JSON integer form\")");
        self.line(1, "if isinstance(v, str): return v");
        self.line(1, "if v is None: return None");
        self.line(1, "if isinstance(v, list): return [_cuni_json_norm(x) for x in v]");
        self.line(1, "if isinstance(v, dict):");
        self.line(2, "for k in v:");
        self.line(3, "if not isinstance(k, str): raise CuNiError(\"json.emit: map keys must be strings\")");
        self.line(2, "return {k: _cuni_json_norm(x) for k, x in v.items()}");
        self.line(1, "raise CuNiError(\"json.emit: value has no JSON form\")");
        self.out.push('\n');
        self.line(0, "def _cuni_json_emit(m):");
        self.line(1, "import json as _json");
        self.line(1, "if not isinstance(m, dict): raise CuNiError(\"json.emit needs a map\")");
        self.line(1, "return _json.dumps(_cuni_json_norm(m), sort_keys=True, separators=(\",\", \":\"), ensure_ascii=False)");
        self.out.push('\n');
        self.line(0, "def _cuni_days_from_civil(y, m, d):");
        self.line(1, "y0 = y - 1 if m <= 2 else y");
        self.line(1, "era = y0 // 400");
        self.line(1, "yoe = y0 - era * 400");
        self.line(1, "mp = (m + 9) % 12");
        self.line(1, "doy = (153 * mp + 2) // 5 + d - 1");
        self.line(1, "doe = yoe * 365 + yoe // 4 - yoe // 100 + doy");
        self.line(1, "return era * 146097 + doe - 719468");
        self.out.push('\n');
        self.line(0, "def _cuni_civil_from_days(z):");
        self.line(1, "z += 719468");
        self.line(1, "era = z // 146097");
        self.line(1, "doe = z - era * 146097");
        self.line(1, "yoe = (doe - doe // 1460 + doe // 36524 - doe // 146096) // 365");
        self.line(1, "y = yoe + era * 400");
        self.line(1, "doy = doe - (365 * yoe + yoe // 4 - yoe // 100)");
        self.line(1, "mp = (5 * doy + 2) // 153");
        self.line(1, "d = doy - (153 * mp + 2) // 5 + 1");
        self.line(1, "m = mp + 3 if mp < 10 else mp - 9");
        self.line(1, "return (y + 1 if m <= 2 else y, m, d)");
        self.out.push('\n');
        self.line(0, "def _cuni_time_epoch(y, mo, d, h, mi, s):");
        self.line(1, "for v, lo, hi, nm in ((y,1,9999,\"year\"),(mo,1,12,\"month\"),(h,0,23,\"hour\"),(mi,0,59,\"minute\"),(s,0,59,\"second\")):");
        self.line(2, "if not (lo <= v <= hi): raise CuNiError(\"time.epoch: %s out of range\" % nm)");
        self.line(1, "dim = [31, 29 if y % 4 == 0 and (y % 100 != 0 or y % 400 == 0) else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][mo - 1]");
        self.line(1, "if not (1 <= d <= dim): raise CuNiError(\"time.epoch: day out of range for month\")");
        self.line(1, "return _cuni_days_from_civil(y, mo, d) * 86400 + h * 3600 + mi * 60 + s");
        self.out.push('\n');
        self.line(0, "def _cuni_time_parts(e):");
        self.line(1, "lo = _cuni_days_from_civil(1, 1, 1) * 86400");
        self.line(1, "hi = _cuni_days_from_civil(9999, 12, 31) * 86400 + 86399");
        self.line(1, "if not (lo <= e <= hi): raise CuNiError(\"time.parts: epoch out of range 1..9999\")");
        self.line(1, "days, secs = divmod(e, 86400)");
        self.line(1, "y, mo, d = _cuni_civil_from_days(days)");
        self.line(1, "return {\"year\": y, \"month\": mo, \"day\": d, \"hour\": secs // 3600, \"min\": (secs % 3600) // 60, \"sec\": secs % 60}");
        self.out.push('\n');
        self.line(0, "def sha256(s):");
        self.line(1, "import hashlib as _hashlib");
        self.line(1, "if not isinstance(s, str): raise CuNiError(\"sha256 needs a str\")");
        self.line(1, "return _hashlib.sha256(s.encode(\"utf-8\")).hexdigest()");        self.out.push('\n');
        self.line(0, "class CuNiError(Exception):");
        self.line(
            1,
            "\"\"\"Raised by `fail` — CuNi's explicit failure-signaling statement.\"\"\"",
        );
        self.out.push('\n');

        // Top-level `ret` (e.g. inside a `??` handler on a top-level `let`)
        // has no enclosing function in CuNi's source, but Python forbids
        // `return` outside one — module-level code isn't a function. So
        // every top-level statement is collected and wrapped in an implicit
        // `main()`, called at the bottom. This is a real gap the spec hasn't
        // addressed yet (see SPEC.md open items): what a top-level `ret`
        // even means is undefined; "the top-level script is one implicit
        // function" is this backend's working assumption, not a ratified
        // spec decision.
        let mut script_stmts: Vec<&Stmt> = Vec::new();
        let mut top_scope: HashMap<String, VarKind> = HashMap::new();
        for item in &program.items {
            if let Item::Stmt(s) = item {
                script_stmts.push(s);
            } else {
                self.gen_item(item, &mut top_scope);
                self.out.push('\n');
            }
        }

        self.line(0, "def main():");
        if script_stmts.is_empty() {
            self.line(1, "pass");
        } else {
            for s in script_stmts {
                self.gen_stmt(1, s, &mut top_scope);
            }
        }
        self.out.push('\n');
        self.line(0, "if __name__ == \"__main__\":");
        self.line(1, "main()");
    }

    fn gen_item(&mut self, item: &Item, scope: &mut HashMap<String, VarKind>) {
        match item {
            Item::Use(u) => {
                self.line(
                    0,
                    &format!(
                        "# use {} — portable CuNi module, not resolved by this toy backend",
                        u.name
                    ),
                );
            }
            Item::Ext(ext) => {
                self.line(
                    0,
                    &format!("def {}({}):", ext.name, params_sig(&ext.params)),
                );
                let py_line = ext
                    .targets
                    .iter()
                    .find(|(t, _)| t == "py")
                    .map(|(_, raw)| raw.clone())
                    .unwrap_or_else(|| {
                        "raise NotImplementedError('no py: mapping given')".to_string()
                    });
                self.line(1, &format!("return {}", py_line));
            }
            Item::Typ(t) => {
                // Do NOT subclass the iface ABC: CuNi realizes iface methods
                // as free functions (`def area(c: Circle)`), not methods on
                // the struct. Inheriting from an ABC with abstract methods
                // would make `Circle(...)` raise TypeError at runtime — the
                // same "is is documentary at the target, checked by CuNi"
                // posture as Go/JS backends. CuNi's typeck enforces `is`.
                self.line(0, "@dataclass");
                if let Some(iface) = &t.implements {
                    self.line(0, &format!("class {}:  # implements {} (checked by CuNi typeck, not via ABC inheritance)", t.name, iface));
                } else {
                    self.line(0, &format!("class {}:", t.name));
                }
                if t.fields.is_empty() {
                    self.line(1, "pass");
                } else {
                    for f in &t.fields {
                        self.line(1, &format!("{}: {}", f.name, py_type(&f.ty)));
                    }
                }
            }
            Item::Iface(i) => {
                self.line(0, &format!("class {}(ABC):", i.name));
                if i.methods.is_empty() {
                    self.line(1, "pass");
                } else {
                    for m in &i.methods {
                        self.line(1, "@abstractmethod");
                        self.line(
                            1,
                            &format!(
                                "def {}({}) -> {}:",
                                m.name,
                                self_params_sig(&m.params),
                                py_type(&m.ret_type)
                            ),
                        );
                        self.line(2, "...");
                    }
                }
            }
            Item::Enum(e) => {
                self.line(0, &format!("class {}(Enum):", e.name));
                if e.variants.is_empty() {
                    self.line(1, "pass");
                } else {
                    for v in &e.variants {
                        self.line(1, &format!("{} = auto()", v.name));
                    }
                }
            }
            Item::Def(f) => {
                let generics_note = if f.generics.is_empty() {
                    String::new()
                } else {
                    format!("  # generic over {}", f.generics.join(", "))
                };
                self.line(
                    0,
                    &format!(
                        "def {}({}) -> {}:{}",
                        f.name,
                        params_sig(&f.params),
                        py_type(&f.ret_type),
                        generics_note
                    ),
                );
                let mut fn_scope: HashMap<String, VarKind> = HashMap::new();
                for p in &f.params {
                    fn_scope.insert(p.name.clone(), kind_of_type(&p.ty));
                }
                if f.body.is_empty() {
                    self.line(1, "pass");
                } else {
                    for s in &f.body {
                        self.gen_stmt(1, s, &mut fn_scope);
                    }
                }
                if f.is_link {
                    self.out.push('\n');
                    self.gen_link_handler(f);
                    self.out.push('\n');
                    self.gen_link_remote(f);
                }
            }
            Item::Stmt(s) => self.gen_stmt(0, s, scope),
        }
    }

    /// `link Name(...) -> T [?] do ... end` additionally emits an HTTP
    /// handler (mount it yourself, per the ratified "codegen-only, no
    /// bundled runtime" decision — see INTEROP_PROPOSAL.md item 6) that
    /// decodes a JSON request, calls the local function above, and encodes
    /// the JSON response — or a `{"error": ...}` response on any exception,
    /// which naturally also covers `fail`/stub bodies without any extra
    /// casework, since Python's `except Exception` already catches those.
    fn gen_link_handler(&mut self, f: &FnDecl) {
        self.line(0, &format!("def {}_handler(handler):", f.name));
        self.line(1, &format!("\"\"\"HTTP handler for `link {}` \u{2014} mount at path \"/{}\" (see SPEC.md \u{a7}19).\"\"\"", f.name, f.name));
        self.line(
            1,
            "length = int(handler.headers.get(\"Content-Length\", 0))",
        );
        self.line(1, "body = handler.rfile.read(length)");
        self.line(1, "try:");
        self.line(2, "req = json.loads(body)");
        let args = f
            .params
            .iter()
            .map(|p| py_wire_decode(&format!("req[{:?}]", p.name), &p.ty))
            .collect::<Vec<_>>()
            .join(", ");
        self.line(2, &format!("result = {}({})", f.name, args));
        self.line(
            2,
            &format!(
                "payload = json.dumps({{\"result\": {}}}).encode()",
                py_wire_encode("result", &f.ret_type)
            ),
        );
        self.line(2, "handler.send_response(200)");
        self.line(
            2,
            "handler.send_header(\"Content-Type\", \"application/json\")",
        );
        self.line(2, "handler.end_headers()");
        self.line(2, "handler.wfile.write(payload)");
        self.line(1, "except Exception as e:");
        self.line(2, "payload = json.dumps({\"error\": str(e)}).encode()");
        self.line(2, "handler.send_response(400)");
        self.line(
            2,
            "handler.send_header(\"Content-Type\", \"application/json\")",
        );
        self.line(2, "handler.end_headers()");
        self.line(2, "handler.wfile.write(payload)");
    }

    /// The client side of the same `link`: always fallible regardless of
    /// whether the local function is (a network call can fail even when the
    /// local logic can't), reusing `CuNiError`/`??` rather than inventing a
    /// second error channel for network failures specifically.
    fn gen_link_remote(&mut self, f: &FnDecl) {
        let params_sig = f
            .params
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        self.line(
            0,
            &format!("def {}_remote(base_url, {}):", f.name, params_sig),
        );
        let fields = f
            .params
            .iter()
            .map(|p| format!("{:?}: {}", p.name, py_wire_encode(&p.name, &p.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        self.line(
            1,
            &format!("req_body = json.dumps({{{}}}).encode()", fields),
        );
        self.line(
            1,
            &format!(
                "req = urllib.request.Request(base_url + \"/{}\", data=req_body, headers={{\"Content-Type\": \"application/json\"}}, method=\"POST\")",
                f.name
            ),
        );
        self.line(1, "try:");
        self.line(2, "with urllib.request.urlopen(req) as resp:");
        self.line(3, "data = json.loads(resp.read())");
        self.line(
            3,
            &format!("return {}", py_wire_decode("data[\"result\"]", &f.ret_type)),
        );
        self.line(1, "except urllib.error.HTTPError as e:");
        self.line(2, "data = json.loads(e.read())");
        self.line(2, "raise CuNiError(data.get(\"error\", str(e)))");
        self.line(1, "except Exception as e:");
        self.line(2, "raise CuNiError(str(e))");
    }

    fn gen_stmt(&mut self, indent: usize, stmt: &Stmt, scope: &mut HashMap<String, VarKind>) {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                let kind = ty
                    .as_ref()
                    .map(kind_of_type)
                    .or_else(|| kind_of_literal(value))
                    .unwrap_or(VarKind::Other);
                scope.insert(name.clone(), kind);
                self.gen_binding(indent, name, value, scope);
            }
            StmtKind::Assign { target, value } => {
                self.line(
                    indent,
                    &format!(
                        "{} = {}",
                        self.gen_expr(target, scope),
                        self.gen_expr(value, scope)
                    ),
                );
            }
            StmtKind::Ret(Some(e)) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("return {}", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("raise CuNiError({})", text));
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                self.line(indent, &format!("if {}:", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, then_body, scope);
                if let Some(else_body) = else_body {
                    self.line(indent, "else:");
                    self.gen_block(indent + 1, else_body, scope);
                }
            }
            StmtKind::For {
                binding: (a, b),
                iter,
                body,
            } => {
                let iter_kind = if let ExprKind::Ident(name) = &iter.kind {
                    scope.get(name).copied()
                } else {
                    None
                };
                let header = match b {
                    Some(b) if iter_kind == Some(VarKind::Map) => {
                        format!(
                            "for {}, {} in {}.items():",
                            a,
                            b,
                            self.gen_expr(iter, scope)
                        )
                    }
                    Some(b) => format!(
                        "for {}, {} in enumerate({}):",
                        a,
                        b,
                        self.gen_expr(iter, scope)
                    ),
                    None => format!("for {} in {}:", a, self.gen_expr(iter, scope)),
                };
                self.line(indent, &header);
                self.gen_block(indent + 1, body, scope);
            }
            StmtKind::Whl { cond, body } => {
                self.line(indent, &format!("while {}:", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, body, scope);
            }
            StmtKind::ExprStmt(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &text);
            }
            StmtKind::Todo => {
                self.line(indent, "raise NotImplementedError(\"...\")  # CuNi stub body (`...`) — not yet written");
            }
        }
    }

    fn gen_block(&mut self, indent: usize, stmts: &[Stmt], scope: &mut HashMap<String, VarKind>) {
        if stmts.is_empty() {
            self.line(indent, "pass");
        } else {
            for s in stmts {
                self.gen_stmt(indent, s, scope);
            }
        }
    }

    /// `let name = expr ?? do handler end` is the only Unwrap position this
    /// toy backend supports (see module docs). `name` is only bound on the
    /// success path — the handler is expected to diverge (`ret`), matching
    /// every example program written against the spec so far.
    fn gen_binding(
        &mut self,
        indent: usize,
        name: &str,
        value: &Expr,
        scope: &mut HashMap<String, VarKind>,
    ) {
        if let ExprKind::Unwrap { expr, handler } = &value.kind {
            let is_fallible_call = matches!(&expr.kind, ExprKind::Call { callee, .. } if matches!(&callee.kind, ExprKind::Ident(fname) if self.fn_info.get(fname).map_or(false, |i| i.fallible))
            );
            let inner = self.gen_expr(expr, scope);
            if is_fallible_call {
                self.line(indent, "try:");
                self.line(indent + 1, &format!("_unwrapped = {}", inner));
                self.line(indent, "except Exception:");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else:");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
            } else {
                self.line(indent, &format!("_unwrapped = {}", inner));
                self.line(indent, "if _unwrapped is None:");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else:");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
            }
        } else {
            self.line(
                indent,
                &format!("{} = {}", name, self.gen_expr(value, scope)),
            );
        }
    }

    fn gen_expr(&self, expr: &Expr, scope: &HashMap<String, VarKind>) -> String {
        match &expr.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Dec(s) => format!("CuniDec({s})"),
            ExprKind::Time(e) => format!("CuniTime({e})"),
            ExprKind::Float(f) => f.to_string(),
            ExprKind::Bool(b) => {
                if *b {
                    "True".to_string()
                } else {
                    "False".to_string()
                }
            }
            ExprKind::Str(s) => format!("{:?}", s),
            ExprKind::InterpStr(parts) => {
                let mut s = String::from("f\"");
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => {
                            let escaped = t
                                .replace('\\', "\\\\")
                                .replace('"', "\\\"")
                                .replace('{', "{{")
                                .replace('}', "}}");
                            s.push_str(&escaped);
                        }
                        StrPartExpr::Expr(e) => {
                            s.push('{');
                            s.push_str(&self.gen_expr(e, scope));
                            s.push('}');
                        }
                    }
                }
                s.push('"');
                s
            }
            ExprKind::NoneLit => "None".to_string(),
            ExprKind::Ident(name) => name.clone(),
            ExprKind::List(items) => format!(
                "[{}]",
                items
                    .iter()
                    .map(|e| self.gen_expr(e, scope))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Map(pairs) => format!(
                "{{{}}}",
                pairs
                    .iter()
                    .map(|(k, v)| format!(
                        "{}: {}",
                        self.gen_expr(k, scope),
                        self.gen_expr(v, scope)
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Call { callee, args } => {
                // `dec` explicit conversions (docs/DECIMAL.md §5).
                if let ExprKind::Ident(n) = &callee.kind {
                    let one = || {
                        args.first()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .unwrap_or_else(|| "None".to_string())
                    };
                    match n.as_str() {
                        "dec_of_int" => return format!("_cuni_dec_of_int({})", one()),
                        "int_of_dec" => return format!("_cuni_int_of_dec({})", one()),
                        // `time` builtins (docs/TIME.md §5).
                        "parse_time" => return format!("_cuni_parse_time({})", one()),
                        "add_seconds" => {
                            let a = args.first().map(|a| self.gen_expr(a.expr(), scope)).unwrap_or_else(|| "None".to_string());
                            let b = args.get(1).map(|a| self.gen_expr(a.expr(), scope)).unwrap_or_else(|| "None".to_string());
                            return format!("_cuni_add_seconds({a}, {b})");
                        }
                        "days_between" => {
                            let a = args.first().map(|a| self.gen_expr(a.expr(), scope)).unwrap_or_else(|| "None".to_string());
                            let b = args.get(1).map(|a| self.gen_expr(a.expr(), scope)).unwrap_or_else(|| "None".to_string());
                            return format!("_cuni_days_between({a}, {b})");
                        }
                        _ => {}
                    }
                }
                if let ExprKind::Field { base, name } = &callee.kind {
                    // Wave-1 stdlib namespaces (docs/STDLIB.md).
                    if let ExprKind::Ident(ns) = &base.kind {
                        if ns == "json" || ns == "time" {
                            let a = args
                                .iter()
                                .map(|a| self.gen_expr(a.expr(), scope))
                                .collect::<Vec<_>>()
                                .join(", ");
                            let f = match (ns.as_str(), name.as_str()) {
                                ("json", "parse") => "_cuni_json_parse",
                                ("json", "emit") => "_cuni_json_emit",
                                ("time", "epoch") => "_cuni_time_epoch",
                                ("time", "parts") => "_cuni_time_parts",
                                _ => "json.time.unknown",
                            };
                            return format!("{f}({a})");
                        }
                    }
                    if name == "push" {
                        return format!(
                            "{}.append({})",
                            self.gen_expr(base, scope),
                            args.iter()
                                .map(|a| self.gen_expr(a.expr(), scope))
                                .collect::<Vec<_>>()
                                .join(", ")
                        );
                    }
                    if name == "len" {
                        return format!("len({})", self.gen_expr(base, scope));
                    }
                    if name == "slice" && args.len() == 2 {
                        return format!(
                            "_cuni_slice({}, {}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope),
                            self.gen_expr(args[1].expr(), scope)
                        );
                    }
                    // Wave-1 string ops (docs/STDLIB.md §3). `split` with an
                    // empty separator raises ValueError natively (a runtime
                    // refusal, as specified); `trim` uses the explicit
                    // ASCII-whitespace set, not str.strip()'s Unicode set.
                    if name == "split" && args.len() == 1 {
                        return format!(
                            "{}.split({})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope)
                        );
                    }
                    if name == "join" && args.len() == 1 {
                        return format!(
                            "{}.join({})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope)
                        );
                    }
                    if name == "trim" && args.is_empty() {
                        return format!(
                            "{}.strip(' \\t\\n\\r\\x0b\\x0c')",
                            self.gen_expr(base, scope)
                        );
                    }
                    if name == "contains" && args.len() == 1 {
                        return format!(
                            "({} in {})",
                            self.gen_expr(args[0].expr(), scope),
                            self.gen_expr(base, scope)
                        );
                    }
                }
                // Named typ constructor -> kwargs: Circle(r=2.0)
                if args.iter().all(|a| a.is_named()) && !args.is_empty() {
                    let parts: Vec<String> = args
                        .iter()
                        .filter_map(|a| match a {
                            CallArg::Named { name, value, .. } => {
                                Some(format!("{}={}", name, self.gen_expr(value, scope)))
                            }
                            _ => None,
                        })
                        .collect();
                    return format!("{}({})", self.gen_expr(callee, scope), parts.join(", "));
                }
                format!(
                    "{}({})",
                    self.gen_expr(callee, scope),
                    args.iter()
                        .map(|a| self.gen_expr(a.expr(), scope))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
            ExprKind::Index { base, index } => format!(
                "{}[{}]",
                self.gen_expr(base, scope),
                self.gen_expr(index, scope)
            ),
            ExprKind::Field { base, name } => format!("{}.{}", self.gen_expr(base, scope), name),
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_expr(lhs, scope);
                let r = self.gen_expr(rhs, scope);
                if matches!(op, BinOp::Div) {
                    format!("_cuni_div({}, {})", l, r)
                } else {
                    format!("({} {} {})", l, py_binop(*op), r)
                }
            }
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("(not {})", self.gen_expr(expr, scope)),
                UnOp::Neg => format!("(-{})", self.gen_expr(expr, scope)),
            },
            ExprKind::Unwrap { .. } => {
                "None  # UNSUPPORTED: ?? outside a let/mut binding, see codegen_py.rs docs"
                    .to_string()
            }
        }
    }
}

fn params_sig(params: &[Param]) -> String {
    params
        .iter()
        .map(|p| format!("{}: {}", p.name, py_type(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn self_params_sig(params: &[Param]) -> String {
    let mut parts = vec!["self".to_string()];
    parts.extend(
        params
            .iter()
            .map(|p| format!("{}: {}", p.name, py_type(&p.ty))),
    );
    parts.join(", ")
}

fn py_type(ty: &Type) -> String {
    match ty {
        Type::Named(name) => match name.as_str() {
            "int" => "int".to_string(),
            "dec" => "CuniDec".to_string(),
            "time" => "CuniTime".to_string(),
            "float" => "float".to_string(),
            "str" => "str".to_string(),
            "bool" => "bool".to_string(),
            other => other.to_string(),
        },
        Type::Generic(name, args) => match name.as_str() {
            "list" => format!("List[{}]", py_type(&args[0])),
            "map" => format!("Dict[{}, {}]", py_type(&args[0]), py_type(&args[1])),
            "opt" => format!("Optional[{}]", py_type(&args[0])),
            other => format!(
                "{}[{}]",
                other,
                args.iter().map(py_type).collect::<Vec<_>>().join(", ")
            ),
        },
    }
}

fn kind_of_type(ty: &Type) -> VarKind {
    match ty {
        Type::Generic(name, _) if name == "list" => VarKind::List,
        Type::Generic(name, _) if name == "map" => VarKind::Map,
        _ => VarKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<VarKind> {
    match &e.kind {
        ExprKind::List(_) => Some(VarKind::List),
        ExprKind::Map(_) => Some(VarKind::Map),
        _ => None,
    }
}

/// `link`'s wire codec (SPEC.md §19): an `int` field is encoded as a JSON
/// *string*, not a JSON number — JSON has no arbitrary-precision integer
/// type, and JS's own `Number` silently loses precision above 2^53, so a
/// decimal-string encoding is the one representation all three v1 targets
/// can round-trip losslessly (checks.rs's `find_bad_link_type` restricts
/// `link` to scalar types specifically so this codec never has to recurse
/// into a `list`/`map`/`typ` shape). float/str/bool pass through as-is —
/// JSON already has a native, lossless representation for each of those on
/// every target this toy backend supports.
fn py_wire_encode(expr: &str, ty: &Type) -> String {
    match ty {
        Type::Named(name) if name == "int" => format!("str({})", expr),
        _ => expr.to_string(),
    }
}

fn py_wire_decode(expr: &str, ty: &Type) -> String {
    match ty {
        Type::Named(name) if name == "int" => format!("int({})", expr),
        _ => expr.to_string(),
    }
}

fn py_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
    }
}
