//! Solidity backend — the blockchain contract writer.
//!
//! Emits a real, deployable Solidity smart contract (pragma ^0.8.0) from CuNi
//! source. This is genuine Solidity, not a Python lowering: `def` becomes a
//! `public pure` function, top-level statements become a public `run()`
//! function, and `say` becomes `emit Log*` events.
//!
//! Exactness notes:
//! - CuNi `int` is i64 with truncated `/` and `%` (Rust semantics).
//!   Solidity `int256` `/` and `%` are also truncated toward zero, so integer
//!   arithmetic matches exactly with no helpers.
//! - `float`, `list`, `map`, `opt`, and `??` (unwrap) are honestly refused:
//!   Solidity has no floats, and try/catch only works on external calls.
//! - `fail` becomes `revert`, matching CuNi's failure semantics.

use crate::ast::{
    BinOp, CallArg, EnumDecl, Expr, ExprKind, FnDecl, Item, Program, Stmt, StmtKind, StrPartExpr,
    Type, TypDecl, UnOp,
};
use std::collections::{HashMap, HashSet};

/// Solidity type of a CuNi variable, for `say` -> event routing.
#[derive(Clone, Copy, PartialEq, Eq)]
enum SolKind {
    Int,
    Str,
    Bool,
    Other,
}

pub struct Codegen {
    fn_names: HashSet<String>,
    fn_ret: HashMap<String, SolKind>,
    typ_names: HashSet<String>,
    enum_names: HashSet<String>,
    /// Does any emitted function body use `say` (needs events, not pure)?
    uses_emit: bool,
    /// Is `_cuni_itoa` needed (int interpolation)?
    needs_itoa: bool,
    out: String,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_names = HashSet::new();
        let mut fn_ret = HashMap::new();
        let mut typ_names = HashSet::new();
        let mut enum_names = HashSet::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    fn_names.insert(f.name.clone());
                    fn_ret.insert(f.name.clone(), kind_of_type(&f.ret_type));
                }
                Item::Typ(t) => {
                    typ_names.insert(t.name.clone());
                }
                Item::Enum(e) => {
                    enum_names.insert(e.name.clone());
                }
                _ => {}
            }
        }
        Codegen {
            fn_names,
            fn_ret,
            typ_names,
            enum_names,
            uses_emit: false,
            needs_itoa: false,
            out: String::new(),
        }
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn esc(s: &str) -> String {
        let mut r = String::with_capacity(s.len() + 2);
        for c in s.chars() {
            match c {
                '"' => r.push_str("\\\""),
                '\\' => r.push_str("\\\\"),
                '\n' => r.push_str("\\n"),
                '\t' => r.push_str("\\t"),
                c => r.push(c),
            }
        }
        r
    }
}

/// Map a CuNi type to its Solidity declaration type.
fn sol_type(ty: &Type) -> Result<String, String> {
    match ty {
        Type::Named(n) => match n.as_str() {
            "int" => Ok("int256".into()),
            "str" => Ok("string".into()),
            "bool" => Ok("bool".into()),
            "float" => Err("Solidity has no float type; refusing float".into()),
            other => Err(format!(
                "type `{}` has no Solidity mapping; refusing",
                other
            )),
        },
        Type::Generic(name, _) => Err(format!(
            "generic type `{}` has no Solidity mapping; refusing",
            name
        )),
    }
}

fn kind_of_type(ty: &Type) -> SolKind {
    match ty {
        Type::Named(n) => match n.as_str() {
            "int" => SolKind::Int,
            "str" => SolKind::Str,
            "bool" => SolKind::Bool,
            _ => SolKind::Other,
        },
        _ => SolKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<SolKind> {
    match &e.kind {
        ExprKind::Int(_) => Some(SolKind::Int),
        ExprKind::Str(_) | ExprKind::InterpStr(_) => Some(SolKind::Str),
        ExprKind::Bool(_) => Some(SolKind::Bool),
        _ => None,
    }
}

pub fn generate(program: &Program) -> Result<String, String> {
    generate_named(program, "CuniContract")
}

pub fn generate_named(program: &Program, contract: &str) -> Result<String, String> {
    let mut g = Codegen::new(program);
    g.gen_program(program, contract)?;
    Ok(g.out)
}

impl Codegen {
    fn gen_program(&mut self, program: &Program, contract: &str) -> Result<(), String> {
        self.line(0, "// SPDX-License-Identifier: MIT");
        self.line(0, "pragma solidity ^0.8.0;");
        self.out.push('\n');
        self.line(0, "/// @title");
        self.line(0, "/// @notice Generated by the CuNi Solidity backend. Same source, same");
        self.line(0, "/// behavior on every CuNi seat — or CuNi refuses to emit it.");
        // Structs first (types used by functions).
        for item in &program.items {
            if let Item::Typ(t) = item {
                self.gen_struct(t)?;
            }
        }
        // Enums.
        for item in &program.items {
            if let Item::Enum(e) = item {
                self.gen_enum(e);
            }
        }
        self.line(0, &format!("contract {} {{", contract));
        self.line(1, "event LogInt(int256 value);");
        self.line(1, "event LogString(string value);");
        self.line(1, "event LogBool(bool value);");
        self.out.push('\n');
        // Functions.
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
                self.out.push('\n');
            }
        }
        // _cuni_itoa helper if any interpolation needs it.
        if self.needs_itoa {
            self.line(1, "/// @notice int256 -> decimal string (for interpolated output).");
            self.line(1, "function _cuni_itoa(int256 v) internal pure returns (string memory) {");
            self.line(2, "if (v == 0) return \"0\";");
            self.line(2, "bool neg = v < 0;");
            self.line(2, "uint256 u = neg ? uint256(-v) : uint256(v);");
            self.line(2, "bytes memory b = new bytes(78);");
            self.line(2, "uint256 i = 78;");
            self.line(2, "while (u > 0) { i--; b[i] = bytes1(uint8(48 + u % 10)); u /= 10; }");
            self.line(2, "bytes memory s = new bytes(78 - i + (neg ? 1 : 0));");
            self.line(2, "if (neg) s[0] = \"-\";");
            self.line(2, "for (uint256 j = 0; j < 78 - i; j++) s[j + (neg ? 1 : 0)] = b[i + j];");
            self.line(2, "return string(s);");
            self.line(1, "}");
            self.out.push('\n');
        }
        // Top-level statements -> run().
        let top: Vec<&Stmt> = program
            .items
            .iter()
            .filter_map(|i| match i {
                Item::Stmt(s) => Some(s),
                _ => None,
            })
            .collect();
        if !top.is_empty() {
            self.line(1, "/// @notice Executes the contract's top-level program. Emits events.");
            self.line(1, "function run() public {");
            let mut scope = HashMap::new();
            for s in top {
                self.gen_stmt(2, s, &mut scope)?;
            }
            self.line(1, "}");
        }
        self.line(0, "}");
        Ok(())
    }

    fn gen_struct(&mut self, t: &TypDecl) -> Result<(), String> {
        let mut fields = Vec::new();
        for f in &t.fields {
            fields.push(format!("{} {};", sol_type(&f.ty)?, f.name));
        }
        self.line(0, &format!("struct {} {{", t.name));
        for f in fields {
            self.line(1, &f);
        }
        self.line(0, "}");
        self.out.push('\n');
        Ok(())
    }

    fn gen_enum(&mut self, e: &EnumDecl) {
        let names: Vec<&str> = e.variants.iter().map(|v| v.name.as_str()).collect();
        self.line(0, &format!("enum {} {{ {} }}", e.name, names.join(", ")));
        self.out.push('\n');
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        if f.fallible {
            // Fallible functions use revert; callers cannot try/catch internal
            // calls, so `??` on them is refused at the use site.
        }
        let mut params = Vec::new();
        for p in &f.params {
            let t = sol_type(&p.ty)?;
            let mem = if t == "string" { " memory" } else { "" };
            params.push(format!("{}{} {}", t, mem, p.name));
        }
        let ret = sol_type(&f.ret_type)?;
        let ret_mem = if ret == "string" { " memory" } else { "" };
        // A body that says anything is not pure.
        let pure = !body_uses_say(&f.body);
        let purity = if pure { " pure" } else { "" };
        self.line(
            1,
            &format!(
                "function {}({}) public{} returns ({}{}) {{",
                f.name,
                params.join(", "),
                purity,
                ret,
                ret_mem
            ),
        );
        let mut scope: HashMap<String, SolKind> = HashMap::new();
        for p in &f.params {
            scope.insert(p.name.clone(), kind_of_type(&p.ty));
        }
        for s in &f.body {
            self.gen_stmt(2, s, &mut scope)?;
        }
        self.line(1, "}");
        Ok(())
    }

    fn gen_stmt(
        &mut self,
        indent: usize,
        stmt: &Stmt,
        scope: &mut HashMap<String, SolKind>,
    ) -> Result<(), String> {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                if matches!(value.kind, ExprKind::Unwrap { .. }) {
                    return Err("`??` has no Solidity equivalent for internal calls; refusing".into());
                }
                let kind = ty.as_ref().map(kind_of_type).unwrap_or(SolKind::Other);
                let kind = if kind == SolKind::Other {
                    // Infer from the value expression (literals and arithmetic).
                    self.expr_kind(value, scope)
                } else {
                    kind
                };
                // Declared type wins; otherwise infer from literal.
                let decl_ty = match ty {
                    Some(t) => sol_type(t)?,
                    None => match kind {
                        SolKind::Int => "int256".into(),
                        SolKind::Str => "string".into(),
                        SolKind::Bool => "bool".into(),
                        SolKind::Other => {
                            return Err(format!(
                                "cannot infer a Solidity type for `{}`; annotate it",
                                name
                            ))
                        }
                    },
                };
                // Memory annotation for strings.
                let mem = if decl_ty == "string" { " memory" } else { "" };
                scope.insert(name.clone(), kind);
                let v = self.gen_expr(value, scope)?;
                // String concat needs abi.encodePacked; gen_expr handles it.
                self.line(
                    indent,
                    &format!("{}{} {} = {};", decl_ty, mem, name, v),
                );
            }
            StmtKind::Assign { target, value } => {
                let t = self.gen_expr(target, scope)?;
                let v = self.gen_expr(value, scope)?;
                self.line(indent, &format!("{} = {};", t, v));
            }
            StmtKind::Ret(Some(e)) => {
                let text = self.gen_expr(e, scope)?;
                self.line(indent, &format!("return {};", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return;"),
            StmtKind::Fail(e) => match &e.kind {
                ExprKind::Str(s) => {
                    self.line(indent, &format!("revert(\"{}\");", Self::esc(s)));
                }
                _ => {
                    return Err(
                        "fail with a non-string has no clean Solidity revert; refusing".into(),
                    )
                }
            },
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let cond_s = self.gen_expr(cond, scope)?;
                self.line(indent, &format!("if ({}) {{", cond_s));
                self.gen_block(indent + 1, then_body, scope)?;
                if let Some(else_body) = else_body {
                    self.line(indent, "} else {");
                    self.gen_block(indent + 1, else_body, scope)?;
                }
                self.line(indent, "}");
            }
            StmtKind::For {
                binding: (a, b),
                iter,
                body,
            } => {
                if b.is_some() {
                    return Err("two-binding for has no Solidity form; refusing".into());
                }
                // Only range() iteration is supported.
                let (start_s, end_e) = match &iter.kind {
                    ExprKind::Call { callee, args } => {
                        let is_range = matches!(&callee.kind, ExprKind::Ident(n) if n == "range");
                        if !is_range {
                            return Err(
                                "for over non-range iterables has no Solidity form; refusing".into(),
                            );
                        }
                        let vals: Vec<&Expr> = args.iter().map(|a| a.expr()).collect();
                        match vals.as_slice() {
                            [_] => (None, vals[0]),
                            [s, e] => (Some(*s), *e),
                            _ => {
                                return Err(
                                    "range() with step has no Solidity form; refusing".into()
                                )
                            }
                        }
                    }
                    _ => {
                        return Err(
                            "for over non-range iterables has no Solidity form; refusing".into(),
                        )
                    }
                };
                let s = match start_s {
                    Some(se) => self.gen_expr(se, scope)?,
                    None => "0".to_string(),
                };
                let e = self.gen_expr(end_e, scope)?;
                scope.insert(a.clone(), SolKind::Int);
                self.line(
                    indent,
                    &format!("for (int256 {} = {}; {} < {}; {}++) {{", a, s, a, e, a),
                );
                self.gen_block(indent + 1, body, scope)?;
                self.line(indent, "}");
            }
            StmtKind::Whl { cond, body } => {
                let cond_s = self.gen_expr(cond, scope)?;
                self.line(indent, &format!("while ({}) {{", cond_s));
                self.gen_block(indent + 1, body, scope)?;
                self.line(indent, "}");
            }
            StmtKind::ExprStmt(e) => {
                self.gen_expr_stmt(indent, e, scope)?;
            }
            StmtKind::Todo => {
                return Err("`...` placeholder body cannot become a contract; refusing".into())
            }
        }
        Ok(())
    }

    fn gen_block(
        &mut self,
        indent: usize,
        body: &[Stmt],
        scope: &mut HashMap<String, SolKind>,
    ) -> Result<(), String> {
        for s in body {
            self.gen_stmt(indent, s, scope)?;
        }
        Ok(())
    }

    /// Expression statements: only `say(...)` calls are meaningful at the top
    /// level of a contract; anything else is a no-op pure call.
    fn gen_expr_stmt(
        &mut self,
        indent: usize,
        e: &Expr,
        scope: &mut HashMap<String, SolKind>,
    ) -> Result<(), String> {
        if let ExprKind::Call { callee, args } = &e.kind {
            if matches!(&callee.kind, ExprKind::Ident(n) if n == "say") {
                let vals: Vec<&Expr> = args.iter().map(|a| a.expr()).collect();
                if vals.len() != 1 {
                    return Err("say takes exactly one argument".into());
                }
                let v = vals[0];
                let kind = self.expr_kind(v, scope);
                let text = self.gen_expr(v, scope)?;
                self.uses_emit = true;
                match kind {
                    SolKind::Int => self.line(indent, &format!("emit LogInt({});", text)),
                    SolKind::Str => self.line(indent, &format!("emit LogString({});", text)),
                    SolKind::Bool => self.line(indent, &format!("emit LogBool({});", text)),
                    SolKind::Other => {
                        return Err(
                            "say of this value has no event mapping; refusing".into()
                        )
                    }
                }
                return Ok(());
            }
        }
        // A bare call with no effect: emit it so internal pure calls still run.
        let text = self.gen_expr(e, scope)?;
        self.line(indent, &format!("{};", text));
        Ok(())
    }

    fn gen_expr(
        &mut self,
        e: &Expr,
        scope: &HashMap<String, SolKind>,
    ) -> Result<String, String> {
        match &e.kind {
            ExprKind::Int(n) => Ok(n.to_string()),
            ExprKind::Float(_) => Err("float literals have no Solidity form; refusing".into()),
            ExprKind::Bool(b) => Ok(b.to_string()),
            ExprKind::Str(s) => Ok(format!("\"{}\"", Self::esc(s))),
            ExprKind::InterpStr(parts) => {
                let mut items = Vec::new();
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => items.push(format!("\"{}\"", Self::esc(t))),
                        StrPartExpr::Expr(ie) => {
                            let k = self.expr_kind(ie, scope);
                            let t = self.gen_expr(ie, scope)?;
                            items.push(match k {
                                SolKind::Int => {
                                    self.needs_itoa = true;
                                    format!("_cuni_itoa({})", t)
                                }
                                SolKind::Bool => {
                                    format!("({} ? \"true\" : \"false\")", t)
                                }
                                SolKind::Str => t,
                                SolKind::Other => {
                                    return Err(
                                        "interpolating this value has no Solidity form; refusing"
                                            .into(),
                                    )
                                }
                            });
                        }
                    }
                }
                Ok(format!("string(abi.encodePacked({}))", items.join(", ")))
            }
            ExprKind::NoneLit => Err("None has no Solidity form; refusing".into()),
            ExprKind::Ident(n) => Ok(n.clone()),
            ExprKind::List(_) | ExprKind::Map(_) => {
                Err("lists and maps have no v1 Solidity form; refusing".into())
            }
            ExprKind::Call { callee, args } => self.gen_call(callee, args, scope),
            ExprKind::Index { .. } => Err("indexing has no v1 Solidity form; refusing".into()),
            ExprKind::Field { base, name } => {
                let b = self.gen_expr(base, scope)?;
                // Enum access Color.Green works as-is in Solidity.
                Ok(format!("{}.{}", b, name))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_expr(lhs, scope)?;
                let r = self.gen_expr(rhs, scope)?;
                let lk = self.expr_kind(lhs, scope);
                // String + is concatenation.
                if matches!(*op, BinOp::Add) && lk == SolKind::Str {
                    return Ok(format!("string(abi.encodePacked({}, {}))", l, r));
                }
                let o = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::Ne => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::Le => "<=",
                    BinOp::Ge => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                Ok(format!("({} {} {})", l, o, r))
            }
            ExprKind::Unary { op, expr } => {
                let t = self.gen_expr(expr, scope)?;
                match op {
                    UnOp::Not => Ok(format!("(!{})", t)),
                    UnOp::Neg => Ok(format!("(-{})", t)),
                }
            }
            ExprKind::Unwrap { .. } => {
                Err("`??` has no Solidity equivalent for internal calls; refusing".into())
            }
        }
    }

    fn gen_call(
        &mut self,
        callee: &Expr,
        args: &[CallArg],
        scope: &HashMap<String, SolKind>,
    ) -> Result<String, String> {
        let name = match &callee.kind {
            ExprKind::Ident(n) => n.clone(),
            _ => return Err("only direct function calls have a Solidity form; refusing".into()),
        };
        if args.iter().any(|a| !matches!(a, CallArg::Pos(_))) {
            return Err("named arguments have no Solidity form; refusing".into());
        }
        // Builtins.
        match name.as_str() {
            "say" => return Err("say is a statement, not an expression; refusing".into()),
            "range" => return Err("range() outside for has no Solidity form; refusing".into()),
            "len" => {
                let vals: Vec<String> = args
                    .iter()
                    .map(|a| self.gen_expr(a.expr(), scope))
                    .collect::<Result<_, _>>()?;
                if vals.len() != 1 {
                    return Err("len takes one argument".into());
                }
                let k = self.expr_kind(args[0].expr(), scope);
                return match k {
                    SolKind::Str => Ok(format!("(int256(bytes({}).length))", vals[0])),
                    _ => Err("len() of this value has no Solidity form; refusing".into()),
                };
            }
            "abs" | "min" | "max" => {
                return Err(format!(
                    "builtin `{}` needs a v1 helper; refusing for now",
                    name
                ))
            }
            _ => {}
        }
        // Struct construction: Circle(2) or Circle(r=2) — positional only here.
        if self.typ_names.contains(&name) {
            let vals: Vec<String> = args
                .iter()
                .map(|a| self.gen_expr(a.expr(), scope))
                .collect::<Result<_, _>>()?;
            return Ok(format!("{}({})", name, vals.join(", ")));
        }
        if !self.fn_names.contains(&name) {
            return Err(format!("unknown call `{}`; refusing", name));
        }
        let vals: Vec<String> = args
            .iter()
            .map(|a| self.gen_expr(a.expr(), scope))
            .collect::<Result<_, _>>()?;
        Ok(format!("{}({})", name, vals.join(", ")))
    }

    /// Best-effort kind of an expression for event routing.
    fn expr_kind(&self, e: &Expr, scope: &HashMap<String, SolKind>) -> SolKind {
        match &e.kind {
            ExprKind::Int(_) => SolKind::Int,
            ExprKind::Str(_) | ExprKind::InterpStr(_) => SolKind::Str,
            ExprKind::Bool(_) => SolKind::Bool,
            ExprKind::Ident(n) => scope.get(n).copied().unwrap_or(SolKind::Other),
            ExprKind::Call { callee, .. } => match &callee.kind {
                ExprKind::Ident(n) if n == "len" => SolKind::Int,
                ExprKind::Ident(n) => self.fn_ret.get(n).copied().unwrap_or(SolKind::Other),
                _ => SolKind::Other,
            },
            ExprKind::Binary { op, lhs, .. } => match op {
                BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Gt | BinOp::Le | BinOp::Ge
                | BinOp::And | BinOp::Or => SolKind::Bool,
                BinOp::Add if self.expr_kind(lhs, scope) == SolKind::Str => SolKind::Str,
                _ => SolKind::Int,
            },
            ExprKind::Unary { op, .. } => match op {
                UnOp::Not => SolKind::Bool,
                UnOp::Neg => SolKind::Int,
            },
            _ => SolKind::Other,
        }
    }
}

fn body_uses_say(body: &[Stmt]) -> bool {
    body.iter().any(stmt_uses_say)
}

fn stmt_uses_say(s: &Stmt) -> bool {
    match &s.kind {
        StmtKind::ExprStmt(e) => expr_uses_say(e),
        StmtKind::If {
            then_body,
            else_body,
            ..
        } => {
            body_uses_say(then_body)
                || else_body.as_ref().map(|b| body_uses_say(b)).unwrap_or(false)
        }
        StmtKind::For { body, .. } | StmtKind::Whl { body, .. } => body_uses_say(body),
        _ => false,
    }
}

fn expr_uses_say(e: &Expr) -> bool {
    match &e.kind {
        ExprKind::Call { callee, args } => {
            (matches!(&callee.kind, ExprKind::Ident(n) if n == "say"))
                || args.iter().any(|a| expr_uses_say(a.expr()))
        }
        ExprKind::Binary { lhs, rhs, .. } => expr_uses_say(lhs) || expr_uses_say(rhs),
        ExprKind::Unary { expr, .. } => expr_uses_say(expr),
        ExprKind::InterpStr(parts) => parts.iter().any(|p| match p {
            StrPartExpr::Expr(ie) => expr_uses_say(ie),
            _ => false,
        }),
        _ => false,
    }
}
