//! OCaml seat — CuNi core subset via a custom emitter.
//!
//! Why custom instead of [`crate::codegen_core`]: the core renders every
//! variable reference as a bare name, but an OCaml `ref` cell reads as `!x`
//! and writes as `x := v` — a read/write asymmetry the core's uniform name
//! rendering cannot express. (Making *every* binding a `ref` does not help:
//! reads would still need `!`.) So this backend tracks mutability in its
//! scope instead.
//!
//! ## Model
//! Statements compile to one OCaml expression via `let … in` chaining
//! (`gen_seq`): `let`/`mut` extend the chain, everything else sequences with
//! `;`. Concretely:
//!
//! - `let x = e` → `let x = e in …` (immutable, read as bare `x`)
//! - `mut x = e` → `let x = ref (e) in …`, read as `!x`, `x = e` → `x := e`
//! - `while c body` → native `while c do … done` — the condition is
//!   re-evaluated each test, so `!x` reads see every update
//! - early `ret` → `raise (CuniRetInt v)` (one exception per return type),
//!   caught once per `def` by `try … with` — OCaml has no non-local `return`,
//!   and the exception propagates honestly through `if`/`while` nesting
//! - a body that falls off the end raises `CuniFellOff` (loud, unreachable
//!   if the type checker did its job); a top-level `ret` raises `CuniTopDone`
//!
//! ## Arithmetic
//! OCaml `/` on `int` truncates toward zero — CuNi `/` semantics, no helper.
//! OCaml `mod` truncates like C (`-7 mod 2 = -1`), so CuNi's Python-floored
//! `%` goes through `cuni_mod a b = ((a mod b) + b) mod b`.
//! `say(true)` prints `True` via the `cuni_say_*` helpers below.
//!
//! Refuses everything beyond the core subset (see `codegen_core` docs), plus
//! `def` names that would collide with the emitted helpers.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

const HEADER: &str = "(* Generated by the CuNi core-subset backend (OCaml seat). Do not hand-edit. *)\nexception CuniRetInt of int\n\
exception CuniRetStr of string\n\
exception CuniRetBool of bool\n\
exception CuniFellOff\n\
exception CuniTopDone\n\
let cuni_mod a b = ((a mod b) + b) mod b\n\
let cuni_say_int x = Stdlib.print_endline (Stdlib.string_of_int x)\n\
let cuni_say_str x = Stdlib.print_endline x\n\
let cuni_say_bool x = Stdlib.print_endline (if x then \"True\" else \"False\")\n";

/// `def` names that would collide with the emitted helpers.
const RESERVED: &[&str] = &[
    "cuni_mod",
    "cuni_say_int",
    "cuni_say_str",
    "cuni_say_bool",
];

#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Str,
    Bool,
}

fn ty_of(ty: &Type) -> Result<Ty, String> {
    match ty {
        Type::Named(n) if n == "int" => Ok(Ty::Int),
        Type::Named(n) if n == "str" => Ok(Ty::Str),
        Type::Named(n) if n == "bool" => Ok(Ty::Bool),
        _ => Err("type beyond core subset; refusing".into()),
    }
}

fn ml_str(s: &str) -> String {
    let mut r = String::from('"');
    for c in s.chars() {
        match c {
            '"' => r.push_str("\\\""),
            '\\' => r.push_str("\\\\"),
            '\n' => r.push_str("\\n"),
            '\t' => r.push_str("\\t"),
            '\r' => r.push_str("\\r"),
            c if (c as u32) < 0x20 => r.push_str(&format!("\\x{:02x}", c as u32)),
            c => r.push(c),
        }
    }
    r.push('"');
    r
}

/// What a `ret` inside the current sequence means: raise the enclosing def's
/// exception, or (at top level) end the script.
enum RetCtx {
    Def(Ty),
    Top,
}

struct Emitter {
    out: String,
    level: usize,
    fns: HashSet<String>,
    fn_ret: HashMap<String, Ty>,
    /// name -> (Ty, is_mut)
    scope: HashMap<String, (Ty, bool)>,
}

pub fn generate(program: &Program) -> Result<String, String> {
    let mut e = Emitter {
        out: String::new(),
        level: 0,
        fns: HashSet::new(),
        fn_ret: HashMap::new(),
        scope: HashMap::new(),
    };
    e.gen_program(program)?;
    Ok(e.out)
}

/// Collect `&Stmt` refs out of a `&[Stmt]` for [`Emitter::gen_seq`].
fn r(stmts: &[Stmt]) -> Vec<&Stmt> {
    stmts.iter().collect()
}

impl Emitter {
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            self.out.push_str(&"  ".repeat(self.level));
            self.out.push_str(text);
        }
        self.out.push('\n');
    }

    fn check_ann(&self, ann: &Option<Type>, vt: Ty, name: &str, kw: &str) -> Result<(), String> {
        if let Some(t) = ann {
            let at = ty_of(t)?;
            if at != vt {
                return Err(format!("{kw} {name}: annotated type disagrees with value; refusing"));
            }
        }
        Ok(())
    }

    fn check_def(&self, f: &FnDecl) -> Result<(), String> {
        if RESERVED.contains(&f.name.as_str()) {
            return Err(format!("def {}: name reserved by the OCaml seat; refusing", f.name));
        }
        if f.fallible {
            return Err(format!("def {}: fallible functions beyond core subset; refusing", f.name));
        }
        if !f.generics.is_empty() {
            return Err(format!("def {}: generics beyond core subset; refusing", f.name));
        }
        if f.is_link {
            return Err(format!("link {}: beyond core subset; refusing", f.name));
        }
        ty_of(&f.ret_type)?;
        for p in &f.params {
            ty_of(&p.ty)?;
        }
        Ok(())
    }

    fn require_ints(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Int && r == Ty::Int {
            Ok(())
        } else {
            Err(format!("`{op}` on non-int: beyond core subset; refusing"))
        }
    }

    fn require_bools(&self, l: Ty, r: Ty, op: &str) -> Result<(), String> {
        if l == Ty::Bool && r == Ty::Bool {
            Ok(())
        } else {
            Err(format!("`{op}` on non-bool: beyond core subset; refusing"))
        }
    }

    fn gen_program(&mut self, program: &Program) -> Result<(), String> {
        self.out.push_str(HEADER);
        let mut script: Vec<&Stmt> = Vec::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    self.check_def(f)?;
                    self.fns.insert(f.name.clone());
                }
                Item::Stmt(s) => script.push(s),
                Item::Use(u) => return Err(format!("use {}: beyond core subset; refusing", u.name)),
                Item::Enum(_) => return Err("enum: beyond core subset; refusing".into()),
                Item::Typ(_) => return Err("typ: beyond core subset; refusing".into()),
                Item::Iface(_) => return Err("iface: beyond core subset; refusing".into()),
                Item::Ext(_) => return Err("ext: beyond core subset; refusing".into()),
            }
        }
        self.out.push('\n');
        for item in &program.items {
            if let Item::Def(f) = item {
                self.gen_def(f)?;
            }
        }
        self.line("let () =");
        self.level += 1;
        self.line("try");
        self.level += 1;
        self.gen_seq(&script, &RetCtx::Top, "()")?;
        self.level -= 1;
        self.line("with CuniTopDone -> ()");
        self.level -= 1;
        Ok(())
    }

    fn gen_def(&mut self, f: &FnDecl) -> Result<(), String> {
        let rt = ty_of(&f.ret_type)?;
        self.fn_ret.insert(f.name.clone(), rt);
        let outer = std::mem::take(&mut self.scope);
        let mut ps = Vec::new();
        for p in &f.params {
            let pt = ty_of(&p.ty)?;
            ps.push(p.name.clone());
            self.scope.insert(p.name.clone(), (pt, false));
        }
        // A zero-parameter CuNi def becomes `let f () = …`, called as `f ()`.
        let params = if ps.is_empty() { "()".to_string() } else { ps.join(" ") };
        let exn = match rt {
            Ty::Int => "CuniRetInt",
            Ty::Str => "CuniRetStr",
            Ty::Bool => "CuniRetBool",
        };
        self.line(&format!("let rec {name} {params} =", name = f.name, params = params));
        self.level += 1;
        self.line("try");
        self.level += 1;
        // `raise CuniFellOff` is the loud, unreachable fall-through: every
        // well-typed CuNi def ends in (or throws via) `ret`.
        self.gen_seq(&r(&f.body), &RetCtx::Def(rt), "raise CuniFellOff")?;
        self.level -= 1;
        self.line(&format!("with {exn} v -> v", exn = exn));
        self.level -= 1;
        self.out.push('\n');
        self.scope = outer;
        Ok(())
    }

    /// Compile a statement list to one OCaml expression. `let`/`mut` extend a
    /// `let … in` chain; everything else sequences with `;`. `tail` is emitted
    /// when the list is exhausted; a `ret` truncates the rest (unreachable).
    /// The indent level is restored to its entry value on every exit.
    fn gen_seq(&mut self, stmts: &[&Stmt], ret: &RetCtx, tail: &str) -> Result<(), String> {
        let entry = self.level;
        if stmts.is_empty() {
            self.line(tail);
            return Ok(());
        }
        for s in stmts {
            match &s.kind {
                StmtKind::Let { name, ty, value } => {
                    let (v, vt) = self.gen_expr(value)?;
                    self.check_ann(ty, vt, name, "let")?;
                    self.scope.insert(name.clone(), (vt, false));
                    self.line(&format!("let {name} = {v} in", name = name, v = v));
                    self.level += 1;
                }
                StmtKind::Mut { name, ty, value } => {
                    let (v, vt) = self.gen_expr(value)?;
                    self.check_ann(ty, vt, name, "mut")?;
                    self.scope.insert(name.clone(), (vt, true));
                    self.line(&format!("let {name} = ref ({v}) in", name = name, v = v));
                    self.level += 1;
                }
                StmtKind::Assign { target, value } => {
                    let tname = match &target.kind {
                        ExprKind::Ident(n) => n.clone(),
                        _ => return Err("complex assignment target: beyond core subset; refusing".into()),
                    };
                    match self.scope.get(&tname) {
                        // Only `mut` bindings are assignable; anything else
                        // is a type error upstream — refuse loudly here.
                        Some((_, true)) => {}
                        _ => return Err(format!("assign to non-mut `{tname}`: refusing", tname = tname)),
                    }
                    let (v, _) = self.gen_expr(value)?;
                    self.line(&format!("({tname} := {v});", tname = tname, v = v));
                }
                StmtKind::Ret(e) => {
                    match ret {
                        RetCtx::Def(rt) => {
                            let x = e
                                .as_ref()
                                .ok_or_else(|| "bare ret: beyond core subset; refusing".to_string())?;
                            let (v, _) = self.gen_expr(x)?;
                            let exn = match rt {
                                Ty::Int => "CuniRetInt",
                                Ty::Str => "CuniRetStr",
                                Ty::Bool => "CuniRetBool",
                            };
                            self.line(&format!("(raise ({exn} {v}))", exn = exn, v = v));
                        }
                        RetCtx::Top => {
                            // Core expressions are pure, but evaluate anyway
                            // (a diverging call must still diverge), then end
                            // the script.
                            let eval = match e {
                                Some(x) => {
                                    let (v, _) = self.gen_expr(x)?;
                                    format!("let _ = {v} in ", v = v)
                                }
                                None => String::new(),
                            };
                            self.line(&format!("({eval}raise CuniTopDone)", eval = eval));
                        }
                    }
                    self.level = entry;
                    return Ok(());
                }
                StmtKind::Fail(_) => return Err("fail: beyond core subset; refusing".into()),
                StmtKind::If { cond, then_body, else_body } => {
                    let (c, ct) = self.gen_expr(cond)?;
                    if ct != Ty::Bool {
                        return Err("if condition must be bool; refusing".into());
                    }
                    self.line(&format!("(if {c} then begin", c = c));
                    self.level += 1;
                    self.gen_seq(&r(then_body), ret, "()")?;
                    self.level -= 1;
                    self.line("end else begin");
                    self.level += 1;
                    self.gen_seq(&r(else_body.as_deref().unwrap_or(&[])), ret, "()")?;
                    self.level -= 1;
                    self.line("end);");
                }
                StmtKind::For { .. } => return Err("for: beyond core subset; refusing".into()),
                StmtKind::Whl { cond, body } => {
                    let (c, ct) = self.gen_expr(cond)?;
                    if ct != Ty::Bool {
                        return Err("while condition must be bool; refusing".into());
                    }
                    self.line(&format!("(while {c} do", c = c));
                    self.level += 1;
                    self.gen_seq(&r(body), ret, "()")?;
                    self.level -= 1;
                    self.line("done);");
                }
                StmtKind::ExprStmt(e) => match &e.kind {
                    ExprKind::Call { callee, args } => match &callee.kind {
                        ExprKind::Ident(n) if n == "say" => {
                            if args.len() != 1 {
                                return Err("say: exactly one argument in core subset; refusing".into());
                            }
                            let (v, vt) = self.gen_expr(args[0].expr())?;
                            let f = match vt {
                                Ty::Int => "cuni_say_int",
                                Ty::Str => "cuni_say_str",
                                Ty::Bool => "cuni_say_bool",
                            };
                            self.line(&format!("({f} ({v}));", f = f, v = v));
                        }
                        _ => return Err("bare call (non-say): beyond core subset; refusing".into()),
                    },
                    _ => return Err("bare expression: beyond core subset; refusing".into()),
                },
                StmtKind::Todo => return Err("...: beyond core subset; refusing".into()),
            }
        }
        self.line(tail);
        self.level = entry;
        Ok(())
    }

    fn gen_expr(&mut self, e: &Expr) -> Result<(String, Ty), String> {
        match &e.kind {
            ExprKind::Int(n) => Ok((format!("({n})", n = n), Ty::Int)),
            ExprKind::Bool(b) => Ok((
                if *b { "(true)".into() } else { "(false)".into() },
                Ty::Bool,
            )),
            ExprKind::Str(s) => Ok((ml_str(s), Ty::Str)),
            ExprKind::Float(_) => Err("float: beyond core subset; refusing".into()),
            ExprKind::Dec(_) => Err("dec: beyond core subset; refusing".into()),
            ExprKind::Time(_) => Err("time: beyond core subset; refusing".into()),
            ExprKind::NoneLit => Err("none: beyond core subset; refusing".into()),
            ExprKind::Ident(n) => {
                let (t, is_mut) = self.scope.get(n).copied().ok_or_else(|| {
                    format!("unknown variable `{n}`: refusing", n = n)
                })?;
                let r = if is_mut {
                    format!("(!{n})", n = n)
                } else {
                    format!("({n})", n = n)
                };
                Ok((r, t))
            }
            ExprKind::InterpStr(_) => Err("interpolated string: beyond core subset; refusing".into()),
            ExprKind::List(_) => Err("list: beyond core subset; refusing".into()),
            ExprKind::Map(_) => Err("map: beyond core subset; refusing".into()),
            ExprKind::Index { .. } => Err("indexing: beyond core subset; refusing".into()),
            ExprKind::Field { .. } => Err("field access: beyond core subset; refusing".into()),
            ExprKind::Unwrap { .. } => Err("??: beyond core subset; refusing".into()),
            ExprKind::Call { callee, args } => {
                let name = match &callee.kind {
                    ExprKind::Ident(n) => n.clone(),
                    _ => return Err("indirect call: beyond core subset; refusing".into()),
                };
                if name == "say" {
                    return Err("say: use as a statement, not an expression; refusing".into());
                }
                let ret = self.fn_ret.get(&name).copied().ok_or_else(|| {
                    format!("call to unknown function `{name}`: refusing", name = name)
                })?;
                if args.iter().any(|a| a.is_named()) {
                    return Err("named arguments: beyond core subset; refusing".into());
                }
                let mut as_: Vec<String> = Vec::new();
                for a in args {
                    as_.push(self.gen_expr(a.expr())?.0);
                }
                // OCaml application is space-separated; zero-arg defs take `()`.
                let call = if as_.is_empty() {
                    format!("({name} ())", name = name)
                } else {
                    format!("({name} {args})", name = name, args = as_.join(" "))
                };
                Ok((call, ret))
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let (l, lt) = self.gen_expr(lhs)?;
                let (r, rt) = self.gen_expr(rhs)?;
                let expr = match op {
                    BinOp::Add => {
                        if lt == Ty::Str && rt == Ty::Str {
                            format!("({l} ^ {r})", l = l, r = r)
                        } else if lt == Ty::Int && rt == Ty::Int {
                            format!("({l} + {r})", l = l, r = r)
                        } else {
                            return Err("mixed-type `+`: beyond core subset; refusing".into());
                        }
                    }
                    BinOp::Sub => {
                        self.require_ints(lt, rt, "-")?;
                        format!("({l} - {r})", l = l, r = r)
                    }
                    BinOp::Mul => {
                        self.require_ints(lt, rt, "*")?;
                        format!("({l} * {r})", l = l, r = r)
                    }
                    // OCaml `/` truncates toward zero: CuNi `/`, no helper.
                    BinOp::Div => {
                        self.require_ints(lt, rt, "/")?;
                        format!("({l} / {r})", l = l, r = r)
                    }
                    // OCaml `mod` truncates (C-like); CuNi wants floored.
                    BinOp::Mod => {
                        self.require_ints(lt, rt, "%")?;
                        format!("(cuni_mod {l} {r})", l = l, r = r)
                    }
                    // Polymorphic `=`/`<>` cover int/str/bool structurally.
                    BinOp::Eq => format!("({l} = {r})", l = l, r = r),
                    BinOp::Ne => format!("({l} <> {r})", l = l, r = r),
                    BinOp::Lt => format!("({l} < {r})", l = l, r = r),
                    BinOp::Gt => format!("({l} > {r})", l = l, r = r),
                    BinOp::Le => format!("({l} <= {r})", l = l, r = r),
                    BinOp::Ge => format!("({l} >= {r})", l = l, r = r),
                    BinOp::And => {
                        self.require_bools(lt, rt, "and")?;
                        format!("({l} && {r})", l = l, r = r)
                    }
                    BinOp::Or => {
                        self.require_bools(lt, rt, "or")?;
                        format!("({l} || {r})", l = l, r = r)
                    }
                };
                let t = match op {
                    BinOp::Add if lt == Ty::Str => Ty::Str,
                    BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div | BinOp::Mod => Ty::Int,
                    _ => Ty::Bool,
                };
                Ok((expr, t))
            }
            ExprKind::Unary { op, expr } => {
                let (v, t) = self.gen_expr(expr)?;
                match op {
                    UnOp::Not => {
                        if t != Ty::Bool {
                            return Err("`not` on non-bool: beyond core subset; refusing".into());
                        }
                        Ok((format!("(not {v})", v = v), Ty::Bool))
                    }
                    UnOp::Neg => {
                        if t != Ty::Int {
                            return Err("unary `-` on non-int: beyond core subset; refusing".into());
                        }
                        Ok((format!("(-{v})", v = v), Ty::Int))
                    }
                }
            }
        }
    }
}
