//! Native Ruby backend for the CuNi AST.
//!
//! Emits idiomatic Ruby that runs under `ruby` with no dependencies.
//! Stdout must be byte-identical to the Python backend (the exactness
//! reference): `say` prints via a `_cuni_repr` that mirrors Python's
//! `repr` for containers/bools/None, integer division truncates toward
//! zero like `_cuni_div`, and `fail`/`??` reuse one `CuNiError`.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub fn generate(program: &Program) -> String {
    let mut cg = Codegen::new(program);
    cg.gen_program(program);
    cg.out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    List,
    Map,
    Other,
}

struct FnInfo {
    fallible: bool,
}

struct Codegen {
    fn_info: HashMap<String, FnInfo>,
    typ_names: HashSet<String>,
    enum_names: HashSet<String>,
    out: String,
}

impl Codegen {
    fn new(program: &Program) -> Self {
        let mut fn_info = HashMap::new();
        let mut typ_names = HashSet::new();
        let mut enum_names = HashSet::new();
        for item in &program.items {
            match item {
                Item::Def(f) => {
                    fn_info.insert(
                        f.name.clone(),
                        FnInfo {
                            fallible: f.fallible,
                        },
                    );
                }
                Item::Typ(t) => {
                    typ_names.insert(t.name.clone());
                }
                Item::Enum(e) => {
                    enum_names.insert(e.name.clone());
                }
                _ => {}
            }
        }
        Codegen {
            fn_info,
            typ_names,
            enum_names,
            out: String::new(),
        }
    }

    fn line(&mut self, indent: usize, text: &str) {
        self.out.push_str(&"    ".repeat(indent));
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn gen_program(&mut self, program: &Program) {
        self.line(0, "# Generated by the CuNi Ruby backend. Do not hand-edit.");
        self.line(0, "require \"delegate\"  # CuniDec < SimpleDelegator");
        self.out.push('\n');
        // ---- stdlib shims (mirror codegen_py's semantics exactly) ----
        self.line(0, "def say(x)");
        self.line(1, "puts(x.is_a?(String) ? x : _cuni_repr(x))");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_repr(x)");
        self.line(1, "case x");
        self.line(1, "when String then x.inspect.tr('\"', \"'\")");
        self.line(1, "when TrueClass then \"True\"");
        self.line(1, "when FalseClass then \"False\"");
        self.line(1, "when NilClass then \"None\"");
        self.line(
            1,
            "when Array then \"[\" + x.map { |e| _cuni_repr(e) }.join(\", \") + \"]\"",
        );
        self.line(
            1,
            "when Hash then \"{\" + x.map { |k, v| \"#{_cuni_repr(k)}: #{_cuni_repr(v)}\" }.join(\", \") + \"}\"",
        );
        self.line(1, "when Float then _cuni_float_str(x)");
        self.line(1, "else x.to_s");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        // Interpolation prints like Python f-strings (str(), not repr()):
        // bare strings stay bare, containers keep their repr.
        self.line(0, "def _cuni_interp_str(x)");
        self.line(1, "x.is_a?(String) ? x : _cuni_repr(x)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_float_str(x)");
        self.line(1, "s = x.to_s");
        self.line(1, "s.include?(\".\") || s.include?(\"e\") ? s : s + \".0\"");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def range(n)");
        self.line(1, "n = n.to_i");
        self.line(1, "return [] if n <= 0");
        self.line(1, "(0...n).to_a");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def abs(n)");
        self.line(1, "n.to_i.abs");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def min(a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "a <= b ? a : b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def max(a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "a >= b ? a : b");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_slice(xs, a, b)");
        self.line(1, "a = a.to_i; b = b.to_i");
        self.line(1, "n = xs.length");
        self.line(
            1,
            "return (xs.is_a?(String) ? \"\" : []) if a < 0 || b < 0 || a > n || b > n || a > b",
        );
        self.line(1, "xs[a...b] || (xs.is_a?(String) ? \"\" : [])");
        self.line(0, "end");
        self.out.push('\n');
        // Integer division truncates toward zero (matches _cuni_div in py).
        self.line(0, "def _cuni_div(a, b)");
        self.line(1, "return a / b if a.is_a?(CuniDec) && b.is_a?(CuniDec)  # CuniDec#/ truncates toward zero, exact");
        self.line(1, "if a.is_a?(Integer) && b.is_a?(Integer) && b != 0");
        self.line(2, "q = a.div(b)");
        self.line(2, "r = a % b");
        self.line(2, "return (r != 0 && (a < 0) != (b < 0)) ? q + 1 : q");
        self.line(1, "end");
        self.line(1, "a.to_f / b");
        self.line(0, "end");
        self.out.push('\n');
<<<<<<< HEAD
        self.line(0, "# CuNi `dec`: fixed-point decimal, scale 10^4, exact (docs/DECIMAL.md).");
        self.line(0, "# Stored as a scaled Integer; operators keep the tag and the scale, so");
        self.line(0, "# plain `+ - * /` in emitted code stay exact with no codegen type");
        self.line(0, "# inference. Mixing with plain Integer is refused (TypeError) — the");
        self.line(0, "# typeck already rejected it; this is defense in depth.");
        self.line(0, "def _cuni_tdiv(a, b)");
        self.line(1, "# Truncation toward zero (docs/DECIMAL.md §3) — Integer#div floors.");
        self.line(1, "q = a.div(b)");
        self.line(1, "r = a - q * b");
        self.line(1, "(r != 0 && (a < 0) != (b < 0)) ? q + 1 : q");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_dec_of_int(n)");
        self.line(1, "CuniDec.new(n.to_i * 10000)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_int_of_dec(d)");
        self.line(1, "CuniDec.tdiv(d.__getobj__, 10000)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "class CuniDec < SimpleDelegator");
        self.line(1, "include Comparable");
        self.line(1, "SCALE = 10000");
        self.line(1, "def self.check!(o)");
        self.line(2, "raise TypeError, \"cuni: cannot mix dec and non-dec — convert explicitly\" unless o.is_a?(CuniDec)");
        self.line(2, "o");
        self.line(1, "end");
        // Truncation toward zero (docs/DECIMAL.md §3) — Integer#div floors.
        // A class method because Delegator < BasicObject: top-level Object
        // helpers are invisible inside this class.
        self.line(1, "def self.tdiv(a, b)");
        self.line(2, "q = a.div(b)");
        self.line(2, "r = a - q * b");
        self.line(2, "(r != 0 && (a < 0) != (b < 0)) ? q + 1 : q");
        self.line(1, "end");
        // Canonical dec rendering of a scaled Integer (docs/DECIMAL.md §6).
        // A class method (same BasicObject reason as tdiv above).
        self.line(1, "def self.dec_str(v)");
        self.line(2, "neg = v < 0");
        self.line(2, "mag = neg ? -v : v");
        self.line(2, "i, f = mag.divmod(10000)");
        self.line(2, "fs = (\"%04d\" % f).sub(/0+\\z/, \"\")");
        self.line(2, "fs = \"0\" if fs.empty?");
        self.line(2, "(neg ? \"-\" : \"\") + i.to_s + \".\" + fs");
        self.line(1, "end");
        self.line(1, "def +(o); CuniDec.new(__getobj__ + CuniDec.check!(o).__getobj__); end");
        self.line(1, "def -(o); CuniDec.new(__getobj__ - CuniDec.check!(o).__getobj__); end");
        self.line(1, "def *(o); CuniDec.new(CuniDec.tdiv(__getobj__ * CuniDec.check!(o).__getobj__, SCALE)); end");
        self.line(1, "def /(o)");
        self.line(2, "o = CuniDec.check!(o)");
        self.line(2, "raise ZeroDivisionError, \"cuni: dec division by zero\" if o.__getobj__ == 0");
        self.line(2, "CuniDec.new(CuniDec.tdiv(__getobj__ * SCALE, o.__getobj__))");
        self.line(1, "end");
        self.line(1, "def -@; CuniDec.new(-__getobj__); end");
        self.line(1, "def <=>(o); __getobj__ <=> (o.is_a?(CuniDec) ? o.__getobj__ : o); end");
        self.line(1, "def ==(o); o.is_a?(CuniDec) && __getobj__ == o.__getobj__; end");
        self.line(1, "def to_s; CuniDec.dec_str(__getobj__); end");
        self.line(1, "def inspect; to_s; end");
=======
        // ---- Wave-1 stdlib (docs/STDLIB.md). `require`s are lazy (inside
        // the helpers) so non-stdlib programs emit no extra dependencies.
        self.line(0, "CUNI_JSON_INT_MAX = 9007199254740991");
        self.out.push('\n');
        self.line(0, "def _cuni_json_num(n)");
        self.line(1, "# Integer or Float from JSON.parse; the value-based integer rule");
        self.line(1, "# (docs/STDLIB.md §1.1). Ruby Integers are exact (bignum).");
        self.line(1, "if n.is_a?(Integer)");
        self.line(2, "raise CuNiError, \"json.parse: number is not an integer in ±(2^53−1)\" if n.abs > CUNI_JSON_INT_MAX");
        self.line(2, "return n");
        self.line(1, "elsif n.is_a?(Float)");
        self.line(2, "raise CuNiError, \"json.parse: number is not an integer in ±(2^53−1)\" unless n == n.to_i && n.abs <= CUNI_JSON_INT_MAX");
        self.line(2, "return n.to_i");
        self.line(1, "else");
        self.line(2, "raise CuNiError, \"json.parse: unexpected value\"");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_json_walk(v)");
        self.line(1, "case v");
        self.line(1, "when Hash then v.each_with_object({}) { |(k, x), o| o[k] = _cuni_json_walk(x) }");
        self.line(1, "when Array then v.map { |x| _cuni_json_walk(x) }");
        self.line(1, "when Integer, Float then _cuni_json_num(v)");
        self.line(1, "when String, TrueClass, FalseClass, NilClass then v");
        self.line(1, "else raise CuNiError, \"json.parse: unexpected value\"");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_json_parse(s)");
        self.line(1, "require \"json\"");
        self.line(1, "raise CuNiError, \"json.parse needs a str\" unless s.is_a?(String)");
        self.line(1, "begin");
        self.line(2, "v = JSON.parse(s)");
        self.line(1, "rescue JSON::ParserError");
        self.line(2, "raise CuNiError, \"json.parse: invalid JSON\"");
        self.line(1, "end");
        self.line(1, "raise CuNiError, \"json.parse: top-level JSON value must be an object\" unless v.is_a?(Hash)");
        self.line(1, "_cuni_json_walk(v)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_json_emit_norm(v)");
        self.line(1, "case v");
        self.line(1, "when Hash");
        self.line(2, "v.each_key { |k| raise CuNiError, \"json.emit: map keys must be strings\" unless k.is_a?(String) }");
        self.line(2, "v.each_with_object({}) { |(k, x), o| o[k] = _cuni_json_emit_norm(x) }");
        self.line(1, "when Array then v.map { |x| _cuni_json_emit_norm(x) }");
        self.line(1, "when Integer then v");
        self.line(1, "when Float then raise CuNiError, \"json.emit: floats have no JSON integer form\"");
        self.line(1, "when String, TrueClass, FalseClass, NilClass then v");
        self.line(1, "else raise CuNiError, \"json.emit: value has no JSON form\"");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_json_sort(v)");
        self.line(1, "# Sort keys in UTF-8 byte order (docs/STDLIB.md §1.3).");
        self.line(1, "case v");
        self.line(1, "when Hash");
        self.line(2, "o = {}");
        self.line(2, "v.keys.sort_by { |k| k.bytes }.each { |k| o[k] = _cuni_json_sort(v[k]) }");
        self.line(2, "o");
        self.line(1, "when Array then v.map { |x| _cuni_json_sort(x) }");
        self.line(1, "else v");
        self.line(1, "end");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_json_emit(m)");
        self.line(1, "require \"json\"");
        self.line(1, "raise CuNiError, \"json.emit needs a map\" unless m.is_a?(Hash)");
        self.line(1, "JSON.generate(_cuni_json_sort(_cuni_json_emit_norm(m)))");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_days_from_civil(y, m, d)");
        self.line(1, "y0 = m <= 2 ? y - 1 : y");
        self.line(1, "era = y0 / 400");
        self.line(1, "yoe = y0 - era * 400");
        self.line(1, "mp = (m + 9) % 12");
        self.line(1, "doy = (153 * mp + 2) / 5 + d - 1");
        self.line(1, "doe = yoe * 365 + yoe / 4 - yoe / 100 + doy");
        self.line(1, "era * 146097 + doe - 719468");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_civil_from_days(z)");
        self.line(1, "z += 719468");
        self.line(1, "era = z / 146097");
        self.line(1, "doe = z - era * 146097");
        self.line(1, "yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365");
        self.line(1, "y = yoe + era * 400");
        self.line(1, "doy = doe - (365 * yoe + yoe / 4 - yoe / 100)");
        self.line(1, "mp = (5 * doy + 2) / 153");
        self.line(1, "d = doy - (153 * mp + 2) / 5 + 1");
        self.line(1, "m = mp < 10 ? mp + 3 : mp - 9");
        self.line(1, "y += 1 if m <= 2");
        self.line(1, "[y, m, d]");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_time_epoch(y, mo, d, h, mi, s)");
        self.line(1, "raise CuNiError, \"time.epoch: year out of range 1..9999\" unless (1..9999).cover?(y)");
        self.line(1, "raise CuNiError, \"time.epoch: month out of range 1..12\" unless (1..12).cover?(mo)");
        self.line(1, "raise CuNiError, \"time.epoch: hour out of range 0..23\" unless (0..23).cover?(h)");
        self.line(1, "raise CuNiError, \"time.epoch: minute out of range 0..59\" unless (0..59).cover?(mi)");
        self.line(1, "raise CuNiError, \"time.epoch: second out of range 0..59\" unless (0..59).cover?(s)");
        self.line(1, "leap = y % 4 == 0 && (y % 100 != 0 || y % 400 == 0)");
        self.line(1, "dim = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][mo - 1]");
        self.line(1, "raise CuNiError, \"time.epoch: day out of range for month\" unless (1..dim).cover?(d)");
        self.line(1, "_cuni_days_from_civil(y, mo, d) * 86400 + h * 3600 + mi * 60 + s");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_time_parts(e)");
        self.line(1, "lo = _cuni_days_from_civil(1, 1, 1) * 86400");
        self.line(1, "hi = _cuni_days_from_civil(9999, 12, 31) * 86400 + 86399");
        self.line(1, "raise CuNiError, \"time.parts: epoch out of range 1..9999\" unless e >= lo && e <= hi");
        self.line(1, "days = e.div(86400)");
        self.line(1, "secs = e - days * 86400");
        self.line(1, "y, mo, d = _cuni_civil_from_days(days)");
        self.line(1, "{ \"year\" => y, \"month\" => mo, \"day\" => d, \"hour\" => secs / 3600, \"min\" => (secs % 3600) / 60, \"sec\" => secs % 60 }");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_split(s, sep)");
        self.line(1, "raise CuNiError, \".split needs strings\" unless s.is_a?(String) && sep.is_a?(String)");
        self.line(1, "raise CuNiError, \".split: empty separator; refusing\" if sep.empty?");
        self.line(1, "# Ruby drops the single empty part of \"\".split; the spec keeps it.");
        self.line(1, "return [\"\"] if s.empty?");
        self.line(1, "s.split(sep, -1)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_join(sep, parts)");
        self.line(1, "raise CuNiError, \".join needs a str separator\" unless sep.is_a?(String)");
        self.line(1, "raise CuNiError, \".join needs a list<str>\" unless parts.is_a?(Array)");
        self.line(1, "parts.each { |x| raise CuNiError, \".join: all parts must be str\" unless x.is_a?(String) }");
        self.line(1, "parts.join(sep)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_trim(s)");
        self.line(1, "raise CuNiError, \".trim needs a str\" unless s.is_a?(String)");
        self.line(1, "# ASCII whitespace only (docs/STDLIB.md §3.3) — not String#strip's set.");
        self.line(1, "s.gsub(/\\A[ \\t\\n\\v\\f\\r]+|[ \\t\\n\\v\\f\\r]+\\z/, \"\")");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_contains(s, sub)");
        self.line(1, "raise CuNiError, \".contains needs strings\" unless s.is_a?(String) && sub.is_a?(String)");
        self.line(1, "s.include?(sub)");
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "def _cuni_sha256(s)");
        self.line(1, "require \"digest\"");
        self.line(1, "raise CuNiError, \"sha256 needs a str\" unless s.is_a?(String)");
        self.line(1, "Digest::SHA256.hexdigest(s)");
>>>>>>> wt-stdlib
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "class CuNiError < StandardError; end");
        self.out.push('\n');

        let mut script_stmts: Vec<&Stmt> = Vec::new();
        let mut top_scope: HashMap<String, VarKind> = HashMap::new();
        for item in &program.items {
            if let Item::Stmt(s) = item {
                script_stmts.push(s);
            } else {
                self.gen_item(item, &mut top_scope);
                self.out.push('\n');
            }
        }

        self.line(0, "def main");
        if script_stmts.is_empty() {
            self.line(1, "# no top-level statements");
        } else {
            for s in script_stmts {
                self.gen_stmt(1, s, &mut top_scope);
            }
        }
        self.line(0, "end");
        self.out.push('\n');
        self.line(0, "main");
    }

    fn gen_item(&mut self, item: &Item, scope: &mut HashMap<String, VarKind>) {
        match item {
            Item::Use(u) => {
                self.line(
                    0,
                    &format!(
                        "# use {} — portable CuNi module, not resolved by this backend",
                        u.name
                    ),
                );
            }
            Item::Ext(ext) => {
                let params = ext
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(0, &format!("def {}({})", ext.name, params));
                let rb_line = ext
                    .targets
                    .iter()
                    .find(|(t, _)| *t == "rb")
                    .map(|(_, raw)| raw.clone())
                    .unwrap_or_else(|| {
                        "raise NotImplementedError('no rb: mapping given')".to_string()
                    });
                self.line(1, &rb_line);
                self.line(0, "end");
            }
            Item::Typ(t) => {
                self.line(0, &format!("class {}", t.name));
                if !t.fields.is_empty() {
                    let attrs = t
                        .fields
                        .iter()
                        .map(|f| format!(":{}", f.name))
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(1, &format!("attr_accessor {}", attrs));
                    // Accept both positional (field order) and keyword construction.
                    self.line(1, "def initialize(*args, **kwargs)");
                    for (i, f) in t.fields.iter().enumerate() {
                        self.line(
                            2,
                            &format!("@{0} = kwargs.fetch(:{0}, args[{1}])", f.name, i),
                        );
                    }
                    self.line(1, "end");
                }
                self.line(0, "end");
            }
            Item::Iface(i) => {
                self.line(0, &format!("module {}", i.name));
                for m in &i.methods {
                    let params = m
                        .params
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(1, &format!("def {}({})", m.name, params));
                    self.line(2, "raise NotImplementedError");
                    self.line(1, "end");
                }
                self.line(0, "end");
            }
            Item::Enum(e) => {
                self.line(0, &format!("module {}", e.name));
                for (i, v) in e.variants.iter().enumerate() {
                    self.line(1, &format!("{} = {}", v.name, i));
                }
                self.line(0, "end");
            }
            Item::Def(f) => {
                let params = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(0, &format!("def {}({})", f.name, params));
                let mut fn_scope: HashMap<String, VarKind> = HashMap::new();
                if f.body.is_empty() {
                    self.line(1, "raise NotImplementedError  # CuNi stub body (`...`)");
                } else {
                    for s in &f.body {
                        self.gen_stmt(1, s, &mut fn_scope);
                    }
                }
                self.line(0, "end");
                if f.is_link {
                    self.line(
                        0,
                        &format!(
                            "# link {}: HTTP handler/client not emitted by the Ruby backend v1",
                            f.name
                        ),
                    );
                }
            }
            Item::Stmt(s) => self.gen_stmt(0, s, scope),
        }
    }

    fn gen_stmt(&mut self, indent: usize, stmt: &Stmt, scope: &mut HashMap<String, VarKind>) {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } | StmtKind::Mut { name, ty, value } => {
                let kind = ty
                    .as_ref()
                    .map(kind_of_type)
                    .or_else(|| kind_of_literal(value))
                    .unwrap_or(VarKind::Other);
                scope.insert(name.clone(), kind);
                self.gen_binding(indent, name, value, scope);
            }
            StmtKind::Assign { target, value } => {
                self.line(
                    indent,
                    &format!(
                        "{} = {}",
                        self.gen_expr(target, scope),
                        self.gen_expr(value, scope)
                    ),
                );
            }
            StmtKind::Ret(Some(e)) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("return {}", text));
            }
            StmtKind::Ret(None) => self.line(indent, "return"),
            StmtKind::Fail(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &format!("raise CuNiError.new({})", text));
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                self.line(indent, &format!("if {}", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, then_body, scope);
                if let Some(else_body) = else_body {
                    self.line(indent, "else");
                    self.gen_block(indent + 1, else_body, scope);
                }
                self.line(indent, "end");
            }
            StmtKind::For {
                binding: (a, b),
                iter,
                body,
            } => {
                let iter_kind = if let ExprKind::Ident(name) = &iter.kind {
                    scope.get(name).copied()
                } else {
                    None
                };
                let it = self.gen_expr(iter, scope);
                let header = match b {
                    Some(b) if iter_kind == Some(VarKind::Map) => {
                        format!("{}.each do |{}, {}|", it, a, b)
                    }
                    Some(b) => format!("{}.each_with_index do |{}, {}|", it, b, a),
                    None => format!("{}.each do |{}|", it, a),
                };
                // Note: `for i, x in xs` binds (i, x); each_with_index yields
                // |element, index|, so the block params are swapped to |x, i|.
                self.line(indent, &header);
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::Whl { cond, body } => {
                self.line(indent, &format!("while {}", self.gen_expr(cond, scope)));
                self.gen_block(indent + 1, body, scope);
                self.line(indent, "end");
            }
            StmtKind::ExprStmt(e) => {
                let text = self.gen_expr(e, scope);
                self.line(indent, &text);
            }
            StmtKind::Todo => {
                self.line(
                    indent,
                    "raise NotImplementedError  # CuNi stub body (`...`) — not yet written",
                );
            }
        }
    }

    fn gen_block(&mut self, indent: usize, stmts: &[Stmt], scope: &mut HashMap<String, VarKind>) {
        if stmts.is_empty() {
            self.line(indent, "# pass");
        } else {
            for s in stmts {
                self.gen_stmt(indent, s, scope);
            }
        }
    }

    fn gen_binding(
        &mut self,
        indent: usize,
        name: &str,
        value: &Expr,
        scope: &mut HashMap<String, VarKind>,
    ) {
        if let ExprKind::Unwrap { expr, handler } = &value.kind {
            let is_fallible_call = matches!(&expr.kind, ExprKind::Call { callee, .. } if matches!(&callee.kind, ExprKind::Ident(fname) if self.fn_info.get(fname).map_or(false, |i| i.fallible))
            );
            let inner = self.gen_expr(expr, scope);
            if is_fallible_call {
                self.line(indent, "begin");
                self.line(indent + 1, &format!("_unwrapped = {}", inner));
                self.line(indent, "rescue StandardError");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
                self.line(indent, "end");
            } else {
                self.line(indent, &format!("_unwrapped = {}", inner));
                self.line(indent, "if _unwrapped.nil?");
                self.gen_block(indent + 1, handler, scope);
                self.line(indent, "else");
                self.line(indent + 1, &format!("{} = _unwrapped", name));
                self.line(indent, "end");
            }
        } else {
            self.line(
                indent,
                &format!("{} = {}", name, self.gen_expr(value, scope)),
            );
        }
    }

    fn gen_expr(&self, expr: &Expr, scope: &HashMap<String, VarKind>) -> String {
        match &expr.kind {
            ExprKind::Int(n) => n.to_string(),
            ExprKind::Dec(s) => format!("CuniDec.new({s})"),
            ExprKind::Float(f) => {
                let s = f.to_string();
                if s.contains('.') || s.contains('e') {
                    s
                } else {
                    format!("{}.0", s)
                }
            }
            ExprKind::Bool(true) => "true".to_string(),
            ExprKind::Bool(false) => "false".to_string(),
            ExprKind::Str(s) => format!("{:?}", s),
            ExprKind::InterpStr(parts) => {
                let mut s = String::from("\"");
                for p in parts {
                    match p {
                        StrPartExpr::Text(t) => {
                            s.push_str(
                                &t.replace('\\', "\\\\")
                                    .replace('"', "\\\"")
                                    .replace("#{", "\\#{"),
                            );
                        }
                        StrPartExpr::Expr(e) => {
                            s.push_str("#{");
                            s.push_str(&_cuni_interp(e, scope, self));
                            s.push('}');
                        }
                    }
                }
                s.push('"');
                s
            }
            ExprKind::NoneLit => "nil".to_string(),
            ExprKind::Ident(name) => name.clone(),
            ExprKind::List(items) => format!(
                "[{}]",
                items
                    .iter()
                    .map(|e| self.gen_expr(e, scope))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Map(pairs) => format!(
                "{{{}}}",
                pairs
                    .iter()
                    .map(|(k, v)| format!(
                        "{} => {}",
                        self.gen_expr(k, scope),
                        self.gen_expr(v, scope)
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            ExprKind::Call { callee, args } => {
                // `dec` explicit conversions (docs/DECIMAL.md §5).
                if let ExprKind::Ident(n) = &callee.kind {
                    let one = || {
                        args.first()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .unwrap_or_else(|| "nil".to_string())
                    };
                    match n.as_str() {
                        "dec_of_int" => return format!("_cuni_dec_of_int({})", one()),
                        "int_of_dec" => return format!("_cuni_int_of_dec({})", one()),
                        _ => {}
                    }
                }
                if let ExprKind::Field { base, name } = &callee.kind {
                    if name == "push" {
                        return format!(
                            "{}.push({})",
                            self.gen_expr(base, scope),
                            args.iter()
                                .map(|a| self.gen_expr(a.expr(), scope))
                                .collect::<Vec<_>>()
                                .join(", ")
                        );
                    }
                    if name == "len" {
                        return format!("{}.length", self.gen_expr(base, scope));
                    }
                    if name == "slice" && args.len() == 2 {
                        return format!(
                            "_cuni_slice({}, {}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope),
                            self.gen_expr(args[1].expr(), scope)
                        );
                    }
                    // Wave-1 stdlib namespaces (docs/STDLIB.md).
                    if let ExprKind::Ident(ns) = &base.kind {
                        if ns == "json" || ns == "time" {
                            let a = args
                                .iter()
                                .map(|x| self.gen_expr(x.expr(), scope))
                                .collect::<Vec<_>>()
                                .join(", ");
                            let f = match (ns.as_str(), name.as_str()) {
                                ("json", "parse") => "_cuni_json_parse",
                                ("json", "emit") => "_cuni_json_emit",
                                ("time", "epoch") => "_cuni_time_epoch",
                                ("time", "parts") => "_cuni_time_parts",
                                _ => "_cuni_stdlib_unknown",
                            };
                            return format!("{f}({a})");
                        }
                    }
                    // Wave-1 string ops (docs/STDLIB.md §3).
                    if name == "split" && args.len() == 1 {
                        return format!(
                            "_cuni_split({}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope)
                        );
                    }
                    if name == "join" && args.len() == 1 {
                        return format!(
                            "_cuni_join({}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope)
                        );
                    }
                    if name == "trim" && args.is_empty() {
                        return format!("_cuni_trim({})", self.gen_expr(base, scope));
                    }
                    if name == "contains" && args.len() == 1 {
                        return format!(
                            "_cuni_contains({}, {})",
                            self.gen_expr(base, scope),
                            self.gen_expr(args[0].expr(), scope)
                        );
                    }
                }
                let callee_s = self.gen_expr(callee, scope);
                // Wave-1 stdlib free function (docs/STDLIB.md §4).
                if callee_s == "sha256" {
                    let a = args
                        .iter()
                        .map(|x| self.gen_expr(x.expr(), scope))
                        .collect::<Vec<_>>()
                        .join(", ");
                    return format!("_cuni_sha256({a})");
                }
                // Typ constructor -> .new (positional or keyword).
                if self.typ_names.contains(&callee_s) {
                    if args.iter().all(|a| a.is_named()) && !args.is_empty() {
                        let parts: Vec<String> = args
                            .iter()
                            .filter_map(|a| match a {
                                CallArg::Named { name, value, .. } => {
                                    Some(format!("{}: {}", name, self.gen_expr(value, scope)))
                                }
                                _ => None,
                            })
                            .collect();
                        return format!("{}.new({})", callee_s, parts.join(", "));
                    }
                    return format!(
                        "{}.new({})",
                        callee_s,
                        args.iter()
                            .map(|a| self.gen_expr(a.expr(), scope))
                            .collect::<Vec<_>>()
                            .join(", ")
                    );
                }
                format!(
                    "{}({})",
                    callee_s,
                    args.iter()
                        .map(|a| self.gen_expr(a.expr(), scope))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
            ExprKind::Index { base, index } => format!(
                "{}[{}]",
                self.gen_expr(base, scope),
                self.gen_expr(index, scope)
            ),
            ExprKind::Field { base, name } => {
                let b = self.gen_expr(base, scope);
                // Enum variant access: Color.Green -> Color::Green
                if matches!(&base.kind, ExprKind::Ident(n) if self.enum_names.contains(n)) {
                    format!("{}::{}", b, name)
                } else {
                    format!("{}.{}", b, name)
                }
            }
            ExprKind::Binary { op, lhs, rhs } => {
                let l = self.gen_expr(lhs, scope);
                let r = self.gen_expr(rhs, scope);
                if matches!(op, BinOp::Div) {
                    format!("_cuni_div({}, {})", l, r)
                } else {
                    format!("({} {} {})", l, rb_binop(*op), r)
                }
            }
            ExprKind::Unary { op, expr } => match op {
                UnOp::Not => format!("(!{})", self.gen_expr(expr, scope)),
                UnOp::Neg => format!("(-{})", self.gen_expr(expr, scope)),
            },
            ExprKind::Unwrap { .. } => {
                "nil  # UNSUPPORTED: ?? outside a let/mut binding".to_string()
            }
        }
    }
}

/// Interpolated values print like `say` (no quotes around strings).
fn _cuni_interp(e: &Expr, scope: &HashMap<String, VarKind>, cg: &Codegen) -> String {
    let v = cg.gen_expr(e, scope);
    format!("_cuni_interp_str({})", v)
}

fn kind_of_type(ty: &Type) -> VarKind {
    match ty {
        Type::Generic(name, _) if name == "list" => VarKind::List,
        Type::Generic(name, _) if name == "map" => VarKind::Map,
        _ => VarKind::Other,
    }
}

fn kind_of_literal(e: &Expr) -> Option<VarKind> {
    match &e.kind {
        ExprKind::List(_) => Some(VarKind::List),
        ExprKind::Map(_) => Some(VarKind::Map),
        _ => None,
    }
}

fn rb_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}
